### ISSUE TITLE
ssh escape sequences?

### ISSUE THREAD

**Issue by aelavender** [MisterTea/EternalTerminal#101]
Hi, I was wondering if ssh escape sequences (like these: https://pleiades.ucsc.edu/hyades/SSH_Escape_Sequences) are supported?  I'm used to being able to jump back to my local shell with `~ ctrl-Z`.  Thanks!

**Comment by jsravn** [comment]
I assume this isn't implemented? Really missing `~.` in et for those dead servers, etc.
