### ISSUE TITLE
It appears there are no Ubuntu Trusty builds available

### ISSUE THREAD

**Issue by cquinn** [MisterTea/EternalTerminal#105]
The dists/ directory lists trusty, but there are no trusty debs in pool. Is it possible to build ET for trusty?

**Comment by ailzhang** [comment]
ubuntu 14.04 doesn't have some dependencies in the official pool like libsodium. So on ubuntus < 16.06, building from source is the best way to install.

**Comment by MisterTea** [comment]
Yep, Launchpad doesn't even support pushing packages for trusty.  IIRC the new Ubuntu LTS version should be out any week now.

**Comment by cquinn** [comment]
Thanks. I'm still stuck on Trusty for dev until my company updates. (so many old dependencies). But I did manage to get ET building with a tiny gflags namespace hack.
