### ISSUE TITLE
Flow Control

### ISSUE THREAD

**Issue by eschwim** [MisterTea/EternalTerminal#108]
I use a single ET (which is awesome, btw) instance to wrap all of my tmux windows.  Occasionally, I do something ill advised that spews a ton of text to my terminal (usually something like tailing a very busy job's stderr), which ends up completely paralyzing my TTY (i.e. it displays output but stops accepting input, most notably SIGINT).

I usually end up having to open a throwaway SSH session to kill the offending process, and a short time later my ET session is usable again.  This is especially problematic when I have multiple tmux windows that are all sharing a single ET session, since they all become paralyzed when this occurs.
Repro is pretty simple.  Connecting to my development server via ET (eg `et foo.com:8080`) and running `yes` is enough to trigger the behavior.  Ctrl-C no longer works; I have to SSH in to kill the yes process.

**Comment by ailzhang** [comment]
Thanks for reporting the issue! I can repro this on et 5.0.7. Any idea how we can fix it? @MisterTea

**Comment by MisterTea** [comment]
I'm not saying this is a solution, but to help me understand: ctrl-c literally never works?  Or it just takes 10+ minutes?  Trying to figure out where the bottleneck is.

**Comment by ailzhang** [comment]
@MisterTea Great point! I didn't wait long enough but killed the `yes` process through an ssh session. Started it again and plan to wait about 30mins. :) Will report back.

**Comment by MisterTea** [comment]
This should be fixed in 5.1.0: we added a delay.  Feel free to re-open if I'm wrong.
