### ISSUE TITLE
Can't find etserver during initial connection

### ISSUE THREAD

**Issue by zefei** [MisterTea/EternalTerminal#109]
I'm a first time user of et and is currently trying to use v4.2.1. During connection (after ssh password), et returns with error:
    bash: etserver: command not found
    Error:  The Eternal Terminal daemon is not running.  Please (re)start the et daemon on the server.

Doing `which etserver` on my server, I got `/usr/local/bin/etserver`.

**Comment by ailzhang** [comment]
@zefei , could you double check if there's a etserver daemon running? `ps aux | grep etserver`

**Comment by zefei** [comment]
I tried on two servers, one has etserver daemon running `/usr/local/opt/et/bin/etserver --cfgfile /usr/local/etc/et.cfg --daemon` and one has not. Connecting either server results in the same error `bash: etserver: command not found`.

**Comment by MisterTea** [comment]
@zefei Latest master now runs the etserver in interactive mode.

**Comment by zefei** [comment]
@MisterTea @ailzhang thank you for the quick fix!

**Comment by phord** [comment]
Gah!  ssh shouldn't run in interactive mode unless you are running an interactive shell.  You are not.

Interactive mode has many other implications, including which shell is started, what profiles are loaded, etc.  A better option would be to include a config option specifying the server location, a client-side switch to let me specify the full path on the remote, or some intelligent search/retry option on the remote.
