### ISSUE TITLE
Can't connect after upgrade

### ISSUE THREAD

**Issue by fdmgit** [MisterTea/EternalTerminal#115]
Just upgraded et on Ubuntu from version 42.1 to 5.0.6. And did an 'brew install MisterTea/et/et' which mainly upgrades the OS X client version.

After having done that I'm getting the message:

bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

and after a few seconds the session will be closed. 

Any hints what I could do to fix the issue?

With version 4.2.1 it was working fine and stable.

**Comment by MisterTea** [comment]
@azhang Could this be related to the interactive mode change?

**Comment by MisterTea** [comment]
@fdmgit Can you tell us which version of ubuntu you are running?

**Comment by fdmgit** [comment]
I'm using Ubuntu 16.04.1

**Comment by MisterTea** [comment]
@fdmgit Thanks, I'm able to duplicate.  Pushing out a new version with a fix now.

**Comment by MisterTea** [comment]
@fdmgit  I just pushed 5.0.7 with a fix.  Try that version and let me know if there are still issues, thanks for reporting!

**Comment by MisterTea** [comment]
(BTW you can follow the push status here: https://launchpad.net/~jgmath2000/+archive/ubuntu/et/+packages )

**Comment by fdmgit** [comment]
It works. 👍
