### ISSUE TITLE
Dependencies for Centos 6-based systems like Amazon Linux

### ISSUE THREAD

**Issue by oorrwullie** [MisterTea/EternalTerminal#118]
Here is a little information you can add to your installation section for compiling on Centos 6 based systems like Amazon Linux if you want:

glog, gflags, protobuf, and libsodium all need to be compiled from source. The rpm packages are too old and will not allow ET to compile.

gflags needs to be compiled with the namespace=gflags NOT google, or it will break and you’ll have to edit src/terminal/LogHandler.cpp and change the namespace.

**Comment by MisterTea** [comment]
Closing since it isn't an issue, but feel free to submit a wiki/PR to add this info!

**Comment by CmdQ** [comment]
I would love to have this information. I worked on Ubuntu quite a bit but I'm no expert when it comes to the other Linuxes. I would love to have EternalTerminal for working with Amazon's machines, but the compilation descriptions for general Linux don't work here.

My system (`uname -srvm`) is a `Linux 5.4.209-129.367.amzn2int.x86_64 #1 SMP Wed Aug 31 17:08:13 UTC 2022 x86_64`.

Any chance of expanding the description for that?
