### ISSUE TITLE
`echo` in .bash_profile breaks ET

### ISSUE THREAD

**Issue by 20015jjw** [MisterTea/EternalTerminal#122]
Issue: as et relies on some info echoed out upon the connection is established, echoing other stuff manually breaks it.

[![asciicast](https://asciinema.org/a/LkiuIZvhkbX64deokR1Zlv96r.png)](https://asciinema.org/a/LkiuIZvhkbX64deokR1Zlv96r)

**Comment by ailzhang** [comment]
@20015jjw  Yea this is kinda expected since ET uses the content `echo`ed back from server side to do an "authentication".

**Comment by ailzhang** [comment]
I will close this issue for now, please feel free to reopen if you have a use case where `echo` is necessary in `.bashrc`.
