### ISSUE TITLE
core dumped on Fedora 28

### ISSUE THREAD

**Issue by philtreF** [MisterTea/EternalTerminal#125]
Hi, 

I'm trying to make run `et` on Fedora 28. It already works with sudo but when launched as non-sudo user `et` is crashing. 

https://pastebin.com/j509Swu9

Like said previously everything is working fine when I launch the same command with `sudo` before. This is the lsof output regarding et process running with sudo : 

https://pastebin.com/UktQBHuT

So we are looking for some file or socket permission. I double checked, my user is able to create files and directories in /tmp directory. 

Could someone advise on which permissions I should have a look ? 

Fred

**Comment by MisterTea** [comment]
If you ran etserver as root, then you need to clean up some files before running as another user. Try: sudo rm /tmp/etserver*

**Comment by MisterTea** [comment]
Why do you need to run etserver as a normal user?

**Comment by fhilpert** [comment]
Hi MisterTea, 

Thank you so much for your answer. 
etserver is running as root no issues with that for now. It is the `et` client I want to run as a non-root user. I got the previous traces when running `et` as a non-root user. Everything is working fine when I  run `et` with sudo. 

Fred

**Comment by MisterTea** [comment]
Oh, it may be because you ran et as root once?  Try: sudo rm /tmp/et*
Then restart the et service and it should work as nonroot. 
@ailzhang maybe we should chmod the log files as a+re this way non-root users can delete logs created by root

**Comment by ailzhang** [comment]
@MisterTea sure that sounds good to me! I will add it sometime this week

**Comment by ailzhang** [comment]
Hmmm after a second thought I'm not sure if this is safe. Currently we rotate the log file every 20M, (old file is deleted). And etserver daemon log is only writable by sudo. That sounds safer than everyone else can delete/modify the daemon log to me. 
The etjump* and etterminal* logs belongs to users.

**Comment by MisterTea** [comment]
Yeah that's a fair point. Can we chmod the et log and leave the etserver log as is?

**Comment by fhilpert** [comment]
Hi, 

Yes, I can confirm that removing the et* files in /tmp/ is making it working as a non-root user. 
+1 for the chmod patch! 

Thank you !

**Comment by ailzhang** [comment]
@MisterTea Right now the only log need root is the daemon log. Other than than terminal logs are all belong to users. I think these are the expected behavior?

**Comment by MisterTea** [comment]
Oh, all the client logs have the user id in the filename?  Hmm, I wonder why he had that error then. I'll try to reproduce tomorrow.

**Comment by ailzhang** [comment]
Client logs are named as etclient-time.log, and terminal logs have userid in the name. 

I think it's possible caused by some minor files like etclient_err, after using sudo to run, this file is changed to sudo user and normal et would fail to open it. @fhilpert did cleaning /tmp/* on client side or server side fix the issue?

**Comment by fhilpert** [comment]
Steps to reproduce : 

1. Clean all the et files in /tmp
2. run as sudo
3. try to run as a non-root user

**Comment by fhilpert** [comment]
@ailzhang cleaning client-side files made the trick.

**Comment by ailzhang** [comment]
@fhilpert  Yea I think that aligns with my guess. https://github.com/MisterTea/EternalTerminal/blob/master/src/terminal/TerminalClient.cpp#L300 This file belongs to sudo after the first attempt, and the following sessions were not able to write to it. I will issue a fix (either write to /dev/null or name it randomly) this week :D

**Comment by fhilpert** [comment]
@ailzhang Sorry for the late reply. Instead of naming it randomly, you could name it `etclient_err_username_date`   or somehow like this ? Other files are named this way  : `etclient_err-date.log` 

These solutions could be better for debuging purposes, according to me.
