### ISSUE TITLE
Incorrect error message on connection issue

### ISSUE THREAD

**Issue by michel-slm** [MisterTea/EternalTerminal#128]
I attempted to connect to a remote host when my `.ssh/config` (synced from Dropbox) has an incorrect permission, and et wrongly claimed the daemon is not running:

```
❯ et fedora-desktop
Bad owner or permissions on /home/michel/.ssh/config
Error:  The Eternal Terminal daemon is not running.  Please (re)start the et daemon on the server.

~
❯ chmod 644 ~/.ssh/config 

~
❯ et fedora-desktop 
(now works)
```

this is et-5.0.7-2.fc28 which just got imported into Fedora

**Comment by philtreF** [comment]
Hi, michel-slm, 

I also noticed that. This seems to be some kind of a generic error wich appears  everytime `et` is unable to connect. I agree with you, this could be improved somehow, but this may not be the current focus @ailzhang @MisterTea  ?

**Comment by ailzhang** [comment]
@michel-slm  @philtreF Yea agree that the err message was not clear enough. I will prepare a patch to improve it. :)

**Comment by ailzhang** [comment]
@michel-slm  I tried to repro this by changing file permission but my ssh still connects. Could you let me know what was your file permission when you couldn't connect?

**Comment by michel-slm** [comment]
@alizhang try 664
