### ISSUE TITLE
Add support to kill an et session from the client side

### ISSUE THREAD

**Issue by chipturner** [MisterTea/EternalTerminal#131]
ssh allows a connection to be killed by entering '\~.' (this is part of a generic command menu supported by ssh; see '\~?' for a list of other commands).

On rare occasions, et seems to get stuck on the client side.  I would like to close that session without (a) killing the terminal tab, and (b) having to find the pid to send a kill signal.  '~.' is ideal for this in SSH, so a similar feature would be nice for et.

**Comment by MisterTea** [comment]
Maybe this is a dumb question, but: what's to prevent someone from accidentally killing their session by typing ~.?  I guess it's not something people ever type normally?

**Comment by chipturner** [comment]
It's an infrequent combination but ssh only listens for the \~ command when it is preceded by a newline, so effectively the sequence is <newline>-<tilde>-COMMAND where command is any of

```
$ ssh <somehost>
$ ~?
Supported escape sequences:
 ~.   - terminate connection (and any multiplexed sessions)
 ~B   - send a BREAK to the remote system
 ~C   - open a command line
 ~R   - request rekey
 ~V/v - decrease/increase verbosity (LogLevel)
 ~^Z  - suspend ssh
 ~#   - list forwarded connections
 ~&   - background ssh (when waiting for connections to terminate)
 ~?   - this message
 ~~   - send the escape character by typing it twice
(Note that escapes are only recognized immediately after newline.)
```

**Comment by MisterTea** [comment]
Dupes #101

**Comment by dimaqq** [comment]
Both #131 and #101 got closed, but was the feature actually implemented?

I just found 2 sessions hopelessly stuck.
I've worked around that with `killall -9 et` at which point my shell received the `~.` sequences. Apparently et wasn't listening to input.
