### ISSUE TITLE
Use a random TCP port

### ISSUE THREAD

**Issue by vvug** [MisterTea/EternalTerminal#139]
It seems to me that `et` uses a static port by default (port 2022), meaning that two users using `et` on the same system will experience conflicts. I know it can be changed, but it is inconvenient. Please make the connection use a random ephemeral port in the range 49152–65535, see:

https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Dynamic,_private_or_ephemeral_ports

**Comment by ailzhang** [comment]
@vvug Although etserver daemon (running by root user) is shared on port 2022. Different users have connect to the same port and their traffic are separate. We have been using it this way for a long time. What inconvenience did you see?

**Comment by vvug** [comment]
@vvug the inconvenience is when `etserver` is *not* run by user root, and two users try to run their own `etserver`.

Moreover, isn't the documentation a bit confusing on this point? From the user manual (https://mistertea.github.io/EternalTerminal/usermanual/) and README.md it seems that it is sufficient to have etserver installed in order to be able to connect (like with mosh), while this is not true: the service has to be running.

**Comment by ailzhang** [comment]
Hi @vvug , I agree that the user manual should mention that service running is required. It's usually not a problem because when user install from apt-get/yum the service should be started automatically. @MisterTea  Maybe we can update the website? 
In general etserver is designed to be started by root user, and the conflict between normal users should be gone.

**Comment by MisterTea** [comment]
@vvug Why would two users each run their own etserver?  If two users try to run their own sshd, the same problem will happen.

I'll update the documentation to be more clear.

**Comment by phord** [comment]
Two users might run their own sshd if they do not have root access to install sshd to run as root.  This would be a nice feature of et, too, imho.
