### ISSUE TITLE
[Feature Request] `-N` like ssh

### ISSUE THREAD

**Issue by NightMachinary** [MisterTea/EternalTerminal#152]
It's useful when I use `et` for port forwarding.

**Comment by MisterTea** [comment]
I don't understand what -N does.  The doc says "Do not execute a remote command", but how is that different from "ssh XXX.com"?  I guess you don't get a shell or something?  Do you use it like this:  "ssh -N XXX.com &" and this way you can keep using your original terminal for something else?

**Comment by NightMachinary** [comment]
You can use it like that, I just use it not to get a shell. This way I
don’t accidentally close an ssh tunnel that is doing port forwarding.
