### ISSUE TITLE
Documentation needs work

### ISSUE THREAD

**Issue by phord** [MisterTea/EternalTerminal#161]
A "what it does" page to tell users why they need this and what it does for them.  The one-line project description really isn't enough.

A "troubleshooting" page to help users through common issues.  Just copying the default "new issue" text would be a good start.

A "faq/features" page to tell people what et does and does not do; for example, are sessions encrypted using ssh or something proprietary to et?  What safeguards are in place to protect my open port on 2022? Why is a server required at all?  Why is the ssh connection abandoned in favor of the TCP connection?

A roadmap would be nice; currently I find myself digging through closed issues to see what you've decided is worth doing or not.

**Comment by MisterTea** [comment]
@phord Please champion this?  Our site is accessible here: https://github.com/MisterTea/EternalTerminal/tree/gh-pages

I can fill in any details that you don't have if you put TODOs

**Comment by marc-h38** [comment]
Please delete the out of date https://eternalterminal.dev/download page and replace with a link to github. Because of https://eternalterminal.dev/download I started trying to compile from source when I didn't need to: already packaged by my distribution!

**Comment by MisterTea** [comment]
@marc-h38 Done!
