### ISSUE TITLE
apt-get ubuntu 18 not supported

### ISSUE THREAD

**Issue by hxrts** [MisterTea/EternalTerminal#162]
no apt-repository for latest ubuntu version

**Comment by hxrts** [comment]
> E: The repository 'http://ppa.launchpad.net/jgmath2000/et/ubuntu cosmic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Seems like cosmic is missing from the distro list when I go to http://ppa.launchpad.net/jgmath2000/et/ubuntu/dists/

**Comment by MisterTea** [comment]
Oh, yeah I only run LTS. Can you use the bionic repo?

**Comment by MisterTea** [comment]
Actually on second thought I'll just make a cosmic repo

**Comment by MisterTea** [comment]
Done!
