### ISSUE TITLE
Update FreeBSD to ET 5.1.9

### ISSUE THREAD

**Issue by atrull** [MisterTea/EternalTerminal#169]
So I've got et server working. Client can connect. If the local network drops, and recovers to the same ip, the session recovers nicely. If I change wifi connection however, it fails on a key error.

[ auth is key-based, ssh works, mosh works.. mosh can successfully roam ip & recover. ]

Some Logs:

Server..

I0123 22:10:48.374042 12995072 UnixSocketHandler.cpp:382] Closing connection: 13
I0123 22:10:48.479285 12995072 PortForwardHandler.cpp:85] Got data for destination socket: 1866991770
I0123 22:10:48.479307 12995072 PortForwardDestinationHandler.cpp:11] Writing 341 bytes to port destination
I0123 22:11:24.106294 12992512 ServerConnection.cpp:15] Accepting connection
I0123 22:11:24.106374 12992512 ServerConnection.cpp:20] SERVER: got client socket fd: 13
I0123 22:11:24.107039 12992512 ServerConnection.cpp:59] Got client with id: yPF3X4ZQ1fa9gMOf
I0123 22:11:24.107074 12992512 UnixSocketHandler.cpp:382] Closing connection: 10
I0123 22:11:24.107102 12992512 Connection.cpp:129] Closed socket
I0123 22:11:24.107112 12992512 Connection.cpp:133] Recovering...
I0123 22:11:24.107108 12995072 TerminalServer.cpp:225] Terminal session ended
I0123 22:11:24.107147 12995072 Connection.cpp:177] Shutting down connection
E0123 22:11:24.107162 12995072 Connection.cpp:119] Tried to close a dead socket
I0123 22:11:24.154811 12992512 BackedWriter.cpp:75] 34372784800: Manually locking recover mutex!
I0123 22:11:24.154865 12992512 BackedWriter.cpp:85] 34372784800: Recovering 20 Messages
I0123 22:11:24.155889 12992512 BackedWriter.cpp:103] 34372784800: Manually unlocking recover mutex!
I0123 22:11:24.155902 12992512 Connection.cpp:166] Finished recovering
I0123 22:11:24.155913 12992512 UnixSocketHandler.cpp:382] Closing connection: 13
I0123 22:11:24.155930 12992512 Connection.cpp:129] Closed socket
I0123 22:11:24.261093 12992512 ServerConnection.cpp:15] Accepting connection
I0123 22:11:24.261126 12992512 ServerConnection.cpp:20] SERVER: got client socket fd: 13
I0123 22:11:24.261353 12992512 ServerConnection.cpp:59] Got client with id: yPF3X4ZQ1fa9gMOf
E0123 22:11:24.261363 12992512 ServerConnection.cpp:61] Got a client that we have no key for
I0123 22:11:24.261412 12992512 UnixSocketHandler.cpp:382] Closing connection: 13

Client ..

[INFO 2019-01-23 22:11:02,025 client-main PortForwardSourceHandler.cpp:18] Tunnel 8888 -> 8888 socket created with fd 28
[INFO 2019-01-23 22:11:02,035 client-main PortForwardSourceHandler.cpp:18] Tunnel 8888 -> 8888 socket created with fd 29
[INFO 2019-01-23 22:11:07,061 client-main PortForwardSourceHandler.cpp:18] Tunnel 8888 -> 8888 socket created with fd 27
[INFO 2019-01-23 22:11:13,256 client-main PortForwardSourceHandler.cpp:18] Tunnel 8888 -> 8888 socket created with fd 30
[INFO 2019-01-23 22:11:18,851 client-main PortForwardSourceHandler.cpp:18] Tunnel 8888 -> 8888 socket created with fd 31
[INFO 2019-01-23 22:11:24,001 client-main TerminalClient.cpp:477] Missed a keepalive, killing connection.
[INFO 2019-01-23 22:11:24,001 client-main ClientConnection.cpp:73] Closing socket
[INFO 2019-01-23 22:11:24,002 client-main ClientConnection.cpp:75] Socket closed, starting new reconnect thread
[INFO 2019-01-23 22:11:24,002 Reconnect ClientConnection.cpp:90] Trying to reconnect to server:2022
[INFO 2019-01-23 22:11:24,080 Reconnect TcpSocketHandler.cpp:89] Connected to server: server using fd 8
[INFO 2019-01-23 22:11:24,130 Reconnect ClientConnection.cpp:104] Got response with status: 2 3
[INFO 2019-01-23 22:11:24,130 Reconnect Connection.cpp:137] Locking reader/writer to recover...
[INFO 2019-01-23 22:11:24,130 Reconnect Connection.cpp:140] Recovering with socket fd 8...
[INFO 2019-01-23 22:11:24,179 Reconnect Connection.cpp:173] Finished recovering with socket fd: 8
[INFO 2019-01-23 22:11:24,179 Reconnect ClientConnection.cpp:135] Reconnect complete
[INFO 2019-01-23 22:11:24,185 client-main Connection.cpp:36] Closing socket because 32 Broken pipe
[INFO 2019-01-23 22:11:24,185 client-main ClientConnection.cpp:82] Waiting for reconnect thread to finish
[INFO 2019-01-23 22:11:24,185 client-main ClientConnection.cpp:73] Closing socket
[INFO 2019-01-23 22:11:24,185 client-main ClientConnection.cpp:75] Socket closed, starting new reconnect thread
[INFO 2019-01-23 22:11:24,185 Reconnect ClientConnection.cpp:90] Trying to reconnect to server:2022

[INFO 2019-01-23 22:11:24,235 Reconnect TcpSocketHandler.cpp:89] Connected to server: server using fd 8
[INFO 2019-01-23 22:11:24,283 Reconnect ClientConnection.cpp:104] Got response with status: 3 3
[INFO 2019-01-23 22:11:24,283 Reconnect ClientConnection.cpp:107] Got invalid key on reconnect, assume that server has terminated the session.
[ERROR 2019-01-23 22:11:24,288 client-main Connection.cpp:122] Tried to close a dead socket
[INFO 2019-01-23 22:11:24,288 client-main TerminalClient.cpp:521] Client derefernced

**Comment by atrull** [comment]
I can provide more logs.. if you want ?

**Comment by MisterTea** [comment]
Hmm, it's saying that the terminal session ended, meaning that the client sent the kill message to the server.

I'll have to take a look at the kill logic next week to see how that could happen.

**Comment by atrull** [comment]
Am I right in thinking roaming should work - i.e. change client IPs.. ?

**Comment by MisterTea** [comment]
@atrull yep, the client should be able to change IPs without any issue.  What version of ET are you running on client and server (run et --version to check)?

**Comment by telser** [comment]
@MisterTea This is probably on me. The FreeBSD port is pretty out of date. I'll make sure the latest release builds and update it tonight.

**Comment by MisterTea** [comment]
@telser Oh, you are totally right.  I have a script that uses VMs to push the build to various OSes, I should probably add freebsd to that.  Can you point me to the build process?

**Comment by MisterTea** [comment]
Wow, I spent a lot of time trying to get a freebsd virtualbox vm up and running and it's a PITA:

1. The system additions can't be built because dependencies are broken, so copy-paste doesn't work
2. I can move the mouse but can't click

Overall I find FreeBSD to be really frustrating and I don't see why anyone would use it?

**Comment by telser** [comment]
I don't use it much for a desktop(primarily because getting some of my work software to run is difficult), rather mostly, as OP mentioned, on the server side. Further I haven't tried to setup a virtualbox (with any OS) with copy/paste in forever. Generally use ssh (or ET :stuck_out_tongue: ) to connect to my vms. It appears that the virtualbox-ose-additions should be available as a binary https://www.freshports.org/emulators/virtualbox-ose-additions/ but again I'm not sure and don't have a test environment available to me at this moment. 

For the server side, things like jails, zfs, the networking stack, boot environments, and so on make it very attractive.

As for the building packages, they don't accept user uploaded binaries. The process is to update the ports tree and submit the diff on the freebsd bugzilla. Here's the handbook page on updating ports https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/port-upgrading.html FWIW, building HEAD seems to work but I can't get a connection. Will test and report back after travel (3ish days) to avoid anything super weird with hotel/airport/vpn networks getting in the way. But if I can help with something else in the meantime I'm more than happy to.

**Comment by MisterTea** [comment]
@telser oh yeah, I guess I should have thought of using et instead of the vm directly :-P.

@atrull Can you try building latest master from source and swapping out your et, etserver, and etterminal binaries with the new ones?  That should fix your problem while we get the package up to date.

**Comment by telser** [comment]
@MisterTea @atrull The package has been updated for the current/latest package branch https://www.freshports.org/net/eternalterminal/ If you use the quarterly package branch, then that isn't updated until the beginning of April (the beginning of the quarter).
