### ISSUE TITLE
et does not connect at all when SSH config contains 'Match original host somehost exec "..."'

### ISSUE THREAD

**Issue by Nindaleth** [MisterTea/EternalTerminal#171]
With the following settings in `~/.ssh/config`, `et` hangs and never connects (`ssh` connects correctly). Please mind, this will happen on a connection attempt to any host, not just when connecting to this specific host!

```
# One of the possible usecases: host is roaming between two different IPs - ping the .122 and if responding (1
# received), connect to the .122 - otherwise (0 received, 100% packet loss) connect to the .123
# Another usecase: in different networks, the host is available under different hostnames (and IPs)
# Usage: ssh rpi
Match originalhost rpi exec "ping -c1 -W1 192.168.1.122 | grep '1 received'"
    HostName 192.168.1.122
    User pi
# SSH handles this as a kind of an 'else' branch
Host rpi
    HostName 192.168.1.123
    User pi
```
If this block is removed from `~/.ssh/config`, `et` starts connecting normally again.

**Environment:**

* client - Linux x86_64 - Fedora 29
* server - Linux x86_64 - RHEL 7
* etclient - et-5.1.9-1.fc29.x86_64
* etserver - built from master 9a06f34a77fbdc05052a2a09fd20e584c7abe47b (should be equivalent to 5.1.9)
* the server was available on the other IP (192.168.1.123) at the time of testing

As can be seen from the `etclient_stderr.log` below, the SSH connection is correctly established (and if I connect to a server that does not run `etserver`, it errors out and quits immediately). ET, however, will not handle the directive well.

<details><summary><b>etclient_stderr.log contents:</b></summary><p>

```
X11 forwarding request failed
```
</p></details>

<details><summary><b>etclient.log contents:</b></summary><p>

```
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line: Match originalhost rpi exec "ping -c1 -W1 192.168.1.122 | grep '1 received'"
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line:     HashKnownHosts yes
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line:     GSSAPIAuthentication no
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line:     ForwardX11 yes
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line:     Compression yes
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line:     ServerAliveInterval 20
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line:     ControlMaster auto
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line:     ControlPath ~/.ssh/tmp/%r@%h:%p
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1289] unsupported config line:     ControlPersist 10m
, ignored
[INFO 2019-02-19 14:21:46,092 client-main ParseConfigFile.hpp:1097] /etc/ssh/ssh_config.d/*.confnot found
[INFO 2019-02-19 14:21:46,092 client-main TerminalClient.cpp:280] Parsed ssh config file, connecting to 192.168.1.122
[INFO 2019-02-19 14:21:46,301 client-main SshSetupHandler.cpp:138] etserver started
[INFO 2019-02-19 14:21:46,302 client-main TerminalClient.cpp:70] ID PASSKEY: jNlXFZEx9ph7daXP MVIbSbSomYB6Jbznlb4Wj9TEAsbcXFDQ
[INFO 2019-02-19 14:21:46,306 client-main TcpSocketHandler.cpp:62] Error connecting with 192.168.1.122: 101 Network is unreachable
[ERROR 2019-02-19 14:21:46,306 client-main TcpSocketHandler.cpp:130] ERROR, no host found
[ERROR 2019-02-19 14:21:46,306 client-main TerminalClient.cpp:94] Connecting to server failed: Connect timeout
[INFO 2019-02-19 14:21:46,316 client-main TerminalClient.cpp:122] Window size changed: 27 98 0 0
[INFO 2019-02-19 14:23:26,425 client-main Connection.cpp:115] Waiting to write...
[INFO 2019-02-19 14:25:06,532 client-main Connection.cpp:115] Waiting to write...
```
</p></details>

**Comment by MisterTea** [comment]
Our ssh parser is not very sophisticated so it is probably bombing out on cases like this.  As part of v6 I'd like to make a way to connect with et that doesn't depend on ssh and that will be one solution, but in general I doubt we will have bandwidth to handle cases like this.

If you have roaming IPs like this, why not run your own dns server and assign hostnames based on mac addresses?

**Comment by Nindaleth** [comment]
That could work. Unfortunately, the other usecase for this approach is when the client roams. In that case the rpi is reachable on a 192.168.x.y local IP in location A, while a dyndns hostname needs to be used if in location B. The dyndns hostname isn't reachable from location A for some reason (corporate network).

I don't really mind if I'm not able to connect to those few specific machines (if et ignores the entries), as long as I can reach the others.

As a workaround, I have moved these entries near the end of the SSH config and that seems to have helped, the other machines can now be reached via et. That's enough for me right now to give et a proper try. Thanks for your response!

**Comment by MisterTea** [comment]
Sure, glad you are using ET :-D
