### ISSUE TITLE
compile on debian missing et.cfg and service

### ISSUE THREAD

**Issue by eberna** [MisterTea/EternalTerminal#172]
after compiling from the source code i was't able to start the service because during the 'make install' the et.service and et.cfg were not installed in my running system. after copy the et.cfg to /etc and et.service in /etsc/systemd/system fixed the problem and i was able to start the server. is this a desired behavior or there is something missing in the install target?

**Comment by MisterTea** [comment]
Most people use the debian package to install, and we use debhelper which copies et.cfg and et.service to the right place, so we don't have that in our cmake script.  Could you update the "build from source" instructions to add this point so other people aren't confused?

**Comment by eberna** [comment]
as you suggested i just sent a pull request with the changes, thank you.
