### ISSUE TITLE
Can you use ET when you have only port 22 access?

### ISSUE THREAD

**Issue by vext01** [MisterTea/EternalTerminal#175]
Hi,

I was wondering if it is possible to use ET when the remote server is behind a third-party controlled firewall allowing only port 22 in?

Thanks

**Comment by MisterTea** [comment]
@vext01 No, you need some other port for et to run on.  In v6 we are planning on allowing et without ssh but for now that is a hard limitation.  Even with v6, people will need to load the keys with ssh (unless they want to use usb sticks).

**Comment by vext01** [comment]
Thanks. Sadly I'm in a scenario where the firewall is out of my control :(
