### ISSUE TITLE
ET 5.1.9 issue with installation on RHEL7

### ISSUE THREAD

**Issue by gvnirmal** [MisterTea/EternalTerminal#176]
I am trying to install ET 5.1.9 on RHEL 7 machine. I am running into problems with the installation. Request your kind help on the below items:
1. libutempter source or tar.gz file or the source isn't available over the internet.
2. Error mentioned below
3. Is it really possible to install on RHEL7 machine? Please suggest.

I am pasting the error snippets:

-- Generating done
EternalTerminal-et-v5.1.9> make
CMakeFiles/generated-code.dir/build.make:63: *** target pattern contains no `%'.      Stop.
make[1]: *** [CMakeFiles/generated-code.dir/all] Error 2
make: *** [all] Error 2

Below is the build function where the error comes from:

build() {
export PATH=/usr/bin:$PATH
GFLAGS_INCLUDE_DIR=${DESTROOT}/pkgs/gflags-2.1.2/usr/local/include/gflags
GFLAGS_LIBRARY=${DESTROOT}/gflags-2.1.2/usr/local/lib
LDFLAGS="-lpthread" \
CXXFLAGS="-I${BASE_DIR}/include -DHAVE_MALLOC=1 -DHAVE_MALLOC_H=1" \
${DESTROOT}/pkgs/cmake-3.12.4/bin/cmake . -DGFLAGS_INCLUDE_DIR=${DESTROOT}/pkgs/gflags-2.1.2/include -DPROTOBUF_INCLUDE_DIR=${BASE_DIR}/pkgs/protobuf    -3.4.0/include/ -DSODIUM_INCLUDE_DIR=${DESTROOT}/pkgs/libsodium-1.0.17/include -DGFLAGS_LIBRARY=${DESTROOT}/gflags-2.1.2/lib -DPROTOBUF_LIBRARY=${BASE_DI    R}/pkgs/protobuf-3.4.0/lib -DSODIUM_LIBRARY=${DESTROOT}/libsodium-1.0.17/lib
 make
}

**Comment by MisterTea** [comment]
libutempter is an optional dependency.

Not sure about that error. Can you post the cmake log and also build with "make VERBOSE=1"
