### ISSUE TITLE
Cannot restart et in same terminal window

### ISSUE THREAD

**Issue by joshim5** [MisterTea/EternalTerminal#177]
When I log out of an et instance and then try to log in again in the same terminal window, the spacing does not look correct and I can't hit enter after hitting my yubikey. Backspaces get mapped to ^? and enter maps to ^M.

This does not occur if I open a new terminal window and try to open et there.

The only way to get out of this issue is to close the terminal window and open another one.

Note: when I log out of et by calling `exit`, this is the output: `[1]    93468 abort      et devfair0213:8080 -t=1234:22 -jport=8080 -v=9`.

et version 5.1.9

**Comment by MisterTea** [comment]
@ailzhang does ET exit cleanly when using a jumphost?

**Comment by ailzhang** [comment]
@MisterTea  Yea at least it's clean for me. @joshim5 feel free to block some time on my calendar next time you see it happens. I can take a look.

**Comment by joshim5** [comment]
@ailzhang I can reliably reproduce this, so happy to show you anytime.
