### ISSUE TITLE
Unable to start et on CentOS 7 due to incorrect path in systemd unit file

### ISSUE THREAD

**Issue by TraceyC77** [MisterTea/EternalTerminal#182]
I am attempting to set up et on a CentOS 7 server and an Ubuntu laptop. The install for Ubuntu via PPA worked but the install for CentOS 7 did not. The core problem is the path to the executable in the included systemd unit file.

I had followed the instructions to build from source from the README here:
https://github.com/MisterTea/EternalTerminal

I also followed the steps for Debian for installing the systemd file. There are no instructions specific to CentOS, and there is only one unit file.
Suggested resolution: Have a separate unit file for CentOS and include it in the CentOS 7 documentation. [See related doc request](https://github.com/MisterTea/EternalTerminal/issues/180)

```
sudo cp ../systemctl/et.service /etc/systemd/system/
sudo cp ../etc/et.cfg /etc/
sudo systemctl enable et.service
sudo systemctl start et.service
```

After attempting to start the service, it reported an error and stopped. The cause was that the etserver file is not in the directory specified by the service unit file:
```
-- Unit et.service has begun starting up.
Apr 10 09:06:57 host.name.here[17211]: Failed at step EXEC spawning /usr/bin/etserver: No such file or directory
-- Subject: Process /usr/bin/etserver could not be executed
-- Defined-By: systemd
```

The location of the file on CentOS 7 is 
`/usr/local/bin/etserver`

After correcting the unit file and reloading the systemd daemon, the service was able to start. Unfortunately, the Ubuntu laptop is unable to connect to et on the CentOS 7 server, even though ssh works, but that's probably a separate issue.

**Comment by MisterTea** [comment]
Can you submit a PR to the readme or docs site explaining what you've done to help others?

Also, the reason why you can't connect even though ssh works is probably because you need to open port 2022

**Comment by TraceyC77** [comment]
I can work up a PR in the next day or two for the docs update, no problem.

After a little more digging, I found that the installer from the PPA on Ubuntu starts up etserver but the install from source on CentOS 7 does not. Therefore, the service is not listening on CentOS 7. Restarting the service didn't do anything. 

**In Ubuntu:**
```
) systemctl status et
● et.service - Eternal Terminal
   Loaded: loaded (/lib/systemd/system/et.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-04-10 07:21:32 CDT; 7h ago
  Process: 25432 ExecStart=/usr/bin/etserver --daemon --cfgfile=/etc/et.cfg (code=exited, status=0/SUCCESS)
 Main PID: 25433 (etserver)
    Tasks: 9 (limit: 4915)
   CGroup: /system.slice/et.service
           └─25433 /usr/bin/etserver --daemon --cfgfile=/etc/et.cfg

Apr 10 07:21:32 tracey-ThinkPad-W530 systemd[1]: Starting Eternal Terminal...
Apr 10 07:21:32 tracey-ThinkPad-W530 systemd[1]: Started Eternal Terminal.

) netstat -plan |ag /etserver
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
unix  2      [ ACC ]     STREAM     LISTENING     1592987  -                    /tmp/etserver.idpasskey.fifo

```

**In CentOS 7**
```
) systemctl status et.service
● et.service - Eternal Terminal
   Loaded: loaded (/etc/systemd/system/et.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2019-04-10 09:22:34 CDT; 5h 22min ago
  Process: 17616 ExecStart=/usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg (code=exited, status=0/SUCCESS)
 Main PID: 17617 (code=exited, status=0/SUCCESS)

Apr 10 09:22:34 hostname.here systemd[1]: Starting Eternal Terminal...
Apr 10 09:22:34 hostname.here[1]: Started Eternal Terminal.

) netstat -plan |ag etserver
-> [1]
```

journalctl wasn't that helpful but here it is
```
Apr 10 14:46:26 hostname.here[1]: Started Eternal Terminal.
-- Subject: Unit et.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit et.service has finished starting up.
-- 
-- The start-up result is done.
```

**Comment by TraceyC77** [comment]
> Can you submit a PR to the readme or docs site explaining what you've done to help others?
> 

Done, here is the PR
https://github.com/MisterTea/EternalTerminal/pull/185

For the "Download ET" web page, I really recommend either just linking to the README rather than the current download instructions page, or making an include for the README on the download page. This would prevent having two places to update documentation, and having them get out of sync.
