### ISSUE TITLE
ET client Cygwin compatibility?

### ISSUE THREAD

**Issue by mblais** [MisterTea/EternalTerminal#189]
Can the ET client be made to work in Cygwin?

**Comment by MisterTea** [comment]
Yep, it should work fine on cygwin, but why use cygwin instead of windows4linux?  You can run ubuntu on windows directly now.

**Comment by mblais** [comment]
Turned out to be too much work to build under Cygwin, so I installed WSL...
which was also too much work, but at least it's working now :-)
