### ISSUE TITLE
"session terminated" on first re-connect when using reverse tunnel

### ISSUE THREAD

**Issue by kverb** [MisterTea/EternalTerminal#190]
After I manually disconnect from my remote session (`exit` or `Ctrl-d`),  I experience a 'session terminated' when I reconnect to the same server. Retrying the ET command works the 2nd time, always. Our servers have a 2fac prompt for each SSH session, and the 'session terminated' happens after what I assume is a successful SSH connection. 

I'm using et version 5.1.9 on both client (mac OS 10.14.5) and Centos server.
My et command looks like  `et -x <server>.com:8082 -rt 8377:8377`

There's no issue if I omit the `-rt` flag.

I've no clue where/what to look for in the logs, but all of the failed connection logs are about 7kb, and end with the lines:

```
[FATAL 2019-06-03 09:58:41,643 terminal-main UserTerminalHandler.cpp:166] Error: (104): Connection reset by peer
[WARNING 2019-06-03 09:58:41,643 terminal-main UserTerminalHandler.cpp:166] Aborting application. Reason: Fatal log at [/builddir/build/BUILD/EternalTerminal-et-v5.1.9/src/terminal/UserTerminalHandler.cpp:166]
```

I noticed that `netstat` says the RT port (8377 in my case) is still listening after i disconnect. After i try (and fail) to reconnect, the 8377 port is no longer listening. 

Any help would be appreciated, even if there's just a work-around, like a command i can pass to ET to clean up the previous RT.

**Comment by albellows** [comment]
I have this same issue - same forwarded port, even.  A fellow follower of (@)wincent, I take it? :) 
To add to the cited log output - these are the corresponding logs on the server side:
```
[FATAL 2019-06-10 06:48:54,859 rYqQwsACQdIR3Sy0 TcpSocketHandler.cpp:145] Tried to listen twice on the same port
[WARNING 2019-06-10 06:48:54,859 rYqQwsACQdIR3Sy0 TcpSocketHandler.cpp:145] Aborting application. Reason: Fatal log at [/builddir/build/BUILD/EternalTerminal-et-v5.1.9/src/base/TcpSocketHandler.cpp:145]
```

**Comment by joshuarubin** [comment]
I'm having the same issue. Though I don't usually use the `-x` flag (maybe I should). I generally have to restart the et server to fix the issue.

Also, if I'm first connected via ssh with `RemoteForward` of the same port, then trying to connect with `et -rt ...` also dies and I have to restart the et server, log out of ssh, kill the `ControlMaster`, connect with `et -rt ...` and then connect again with ssh (if I also wanted the ssh session).

**Comment by ddska** [comment]
Same issue here, have to restart et server after each session.

**Comment by MisterTea** [comment]
Is your server on master?  This was fixed in https://github.com/MisterTea/EternalTerminal/commit/26fd0f5f0ef88d05d97e41b6b9612a885b48c636 .  I hope to get a new release out in the next couple of weeks

**Comment by ddska** [comment]
Fixed now, thank you!
