### ISSUE TITLE
Something is different....?

### ISSUE THREAD

**Issue by mblais** [MisterTea/EternalTerminal#191]
When I connect to my remote machine using `et`, something is different, and I'm trying to figure out what:

* On connect, I don't see the MOTD banner I usually see when connecting via `mosh` or `ssh`.
* `ls` no longer outputs color (even with `--color=always`), but other apps (like `zsh`) still do.

Help?

**Comment by MisterTea** [comment]
Hmm, it may be because we are running different setup. What she'll are you using?

**Comment by mblais** [comment]
The `et` server is on a LightSail (AWS) Bitnami Wordpress stack (Ubuntu 16.04.6 LTS).
The `et` client is on Ubuntu 16.04.6 LTS under Windows 10 (WSL).

**Comment by MisterTea** [comment]
@mblais are you running bash?  zsh?

**Comment by mblais** [comment]
zsh on both ends.

**Comment by dandv** [comment]
See also #211.

**Comment by MisterTea** [comment]
@mblais Is this still an issue with latest master?

**Comment by mblais** [comment]
It may be a while before I can answer that, as I don't currently have access to the machine I was using - but I'll star your question and reply at my next opportunity.

**Comment by mblais** [comment]
I am having problems with the build... 
`CMake Error at CMakeLists.txt:138 (add_sanitizers):
  Unknown CMake command "add_sanitizers".`
WSL Ubuntu 18.04.2 LTS

**Comment by MisterTea** [comment]
We recently added a submodules. You need to "git submodules update --init"

**Comment by mblais** [comment]
I'm missing stuff... not sure how to fix it:

`In file included from /home/matt/EternalTerminal/src/base/BackedReader.hpp:4:0,
                 from /home/matt/EternalTerminal/src/base/BackedReader.cpp:1:
/home/matt/EternalTerminal/src/base/Headers.hpp:67:10: fatal error: ThreadPool.h: No such file or directory`

**Comment by MisterTea** [comment]
That's also in a new submodule. Maybe just re-clone from scratch?

**Comment by mblais** [comment]
ET built successfully, but now I'm getting:
`Error starting ET process through ssh, please make sure your ssh works first`
(yes, my `ssh` is working)

**Comment by MisterTea** [comment]
Hmm, I'll need more info to debug that. Can you turn on verbose mode on client & server and collect some logs?

**Comment by mblais** [comment]
Trouble building from source on the server (Ubuntu 16.04.6 LTS) --

```
$ make
[  3%] Built target generated-code[  5%] Building CXX object
CMakeFiles/TerminalCommon.dir/src/terminal/PortForwardHandler.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/TerminalCommon.dir/build.make:70: recipe for target
'CMakeFiles/TerminalCommon.dir/src/terminal/PortForwardHandler.cpp.o' failed
make[2]: *** [CMakeFiles/TerminalCommon.dir/src/terminal/PortForwardHandler.cpp.o] Error 4
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/TerminalCommon.dir/all' failed
make[1]: *** [CMakeFiles/TerminalCommon.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by MisterTea** [comment]
This means that the machine you are trying to compile for doesn't have enough ram to compile the program. Is this a micro VM or something?

**Comment by mblais** [comment]
Yeah it's a 512MB LightSail VM (AWS) running Bitnami WordPress. I may upgrade it and try the build again (or I suppose I could just stop the server processes).

**Comment by mblais** [comment]
Successfully built `et` on the server, did `make install`, copied the config files, etc. 
But:
` et.service: Failed at step EXEC spawning /usr/bin/etserver: No such file or directory`

It's in `/usr/local/bin` instead.
??

**Comment by MisterTea** [comment]
You need to run make install as sudo for it to install to /usr/bin

**Comment by mblais** [comment]
I did use sudo, but still it goes into /usr/local/bin:

```
$ sudo make install
[  3%] Built target generated-code
[ 24%] Built target TerminalCommon
[ 57%] Built target et-lib
[ 61%] Built target etterminal
[ 64%] Built target et
[ 78%] Built target HtmCommon
[ 82%] Built target etserver
[ 85%] Built target htm
[ 89%] Built target htmd
[100%] Built target et-test
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/bin/etserver
-- Up-to-date: /usr/local/bin/etterminal
-- Up-to-date: /usr/local/bin/et
-- Up-to-date: /usr/local/bin/htm
-- Up-to-date: /usr/local/bin/htmd
```

**Comment by MisterTea** [comment]
Oh, there should be a cmake option to control the install path.  I think it's CMAKE_INSTALL_PREFIX

**Comment by mblais** [comment]
Ok, I have rebuilt both et-server and et client with the latest git sources (6.0.4 still) and now CMAKE_INSTALL_PREFIX = '/usr'

I am seeing the same behavior - MOTD does not appear when connecting, and `ls` always produces  uncolored output.

How can I help debug?

**Comment by mblais** [comment]
I partially solved half of the problem:

I noticed that my `LS_COLORS` environment variable was empty after logging in via `et`. I'm not sure exactly **why** or **how** the login procedure is different in `et` from `ssh` or `mosh`, but clearly it is different. 

I made sure `LS_COLORS` is being set in my login procedure, and now that part is working as expected.

I'm still not seeing MOTD.

Is this a clue? --> From motd(5)'s manual page:
```
NAME motd - message of the day

DESCRIPTION The contents of /etc/motd are displayed by pam_motd(8)
after a successful login but just before it executes the login shell.
```

**Comment by MisterTea** [comment]
For LS_COLORS, you can check your ~/.bash_profile and ~/.bashrc .  I think et runs one of them but not the other. 

For motd, that's run as part of PAM and et doesn't use PAM except when setting up the connection.

**Comment by mblais** [comment]
Why does `et` perform a non-standard login procedure (as compared to e.g. `ssh` or `mosh`)?

**Comment by MisterTea** [comment]
@mblais mostly because it isn't hooked up, but someone could add MOTD support with a PR.
