### ISSUE TITLE
Installing on GNU/Linux

### ISSUE THREAD

**Issue by ivenkrish** [MisterTea/EternalTerminal#193]
I've installed et on my Mac(client), no issues. Been trying to install it on my GNU/Linux server machine where I don't have root privileges. 

First off, I can't do yum install for any of the required dependencies because I don't have root permissions. I tried to manually compile cmake, protobuf etc and  and it has been a pain in the ass. I'm blocked since I don't have the specific required gcc 4.8.1 or above on my server so I can't compile cmake3 which in turn I need to compile ET.

Is there any other way to simply copy over the binary/libs required to my GNU/Linux server and run the et-server? Or is it simply impossible to install without root privileges?

**Comment by ailzhang** [comment]
You can copy binaries over and that's not a problem, but `etserver` on server side requires sudo access to start, so it might not work without sudo.

**Comment by MisterTea** [comment]
@vincentqb etserver is meant to be a daemon that runs as root, similar to sshd, mysqld, etc..  Because multiple people can use a single et server, running the et server as a regular user could be a security issue, since other people's data would be passing through that user's memory.

**Comment by LunarLanding** [comment]
What if only the user is going to access a specific et server?
On clusters I use it's fine to leave lightweight processes running for days, wouldn't ssh authentication limit security issues?
I know I would have issues convincing admins to give et sudo priviledges.
