### ISSUE TITLE
feature request: pre-session setup

### ISSUE THREAD

**Issue by RichardScothern** [MisterTea/EternalTerminal#194]
It would be very useful to be able to configure et to perform configurable pre-session setup.  A number of reasons for this:
 - The et session establishment does not use an interactive SSH session, and therefore does not invoke `/etc/profile{.d}`
 - The ssh agent is not available during PAM session setup.  There are use cases for the SSH agent to be used during session setup.

My proposal is to add an entry to the et configuration, specifying a directory e.g. `/etc/et.d`
and for the et server to invoke scripts in that directory after authentication has succeeded.

**Comment by MisterTea** [comment]
Hey @RichardScothern !  Actually et does use an interactive ssh session by passing the -l switch, so it should invoke those scripts.

Can you explain the second point more or give a reference?

**Comment by RichardScothern** [comment]
I do not see the `-l` flag in 6.0.4 (client or server)

**Comment by MisterTea** [comment]
@RichardScothern sorry, I meant that when et sets up the connection (by using ssh), it uses an interactive ssh.  So all the PAM scripts run when the connection is established.
