### ISSUE TITLE
When relay and dest have different usernames

### ISSUE THREAD

**Issue by yafz** [MisterTea/EternalTerminal#195]
Hi guys.
I wrote in my ssh config like this:

> Host relay
>  HostName [ip of relay]
>  User relayUser
> 
>  Host dest
>  HostName [ip of dest]
>  User destUser
>  ProxyJump relayUser@relay

I could et into relay and ssh into relay & dest, but when I try to et into dest, eternal terminal prompts me to enter the password of 'destUser@relayUser@relayIP' like this 'destUser@relayUser@x.x.x.x's password:'. Does that mean et cannot handle proxyjump well, or I am just being stupid?

Please help, thanks.

**Comment by MisterTea** [comment]
IIRC et's ssh config parser cannot handle the ProxyJump command.  @ailzhang  can you confirm?

@yafz if you would like to add this feature, we always welcome PRs :-D
