### ISSUE TITLE
SSH config "Include" path needs to be absolute path

### ISSUE THREAD

**Issue by grakkpl** [MisterTea/EternalTerminal#197]
ET does parse the "Include" parameter from ssh config file but it assumes it is an absolute path, and SSH supports both - absolute and relative paths. 

Working example:
```
cat .ssh/config
Include /Users/barteq/.ssh/config.eda
```

Invalid example:
```
cat .ssh/config
Include config.eda
```

Both work through SSH, ET reports this:
`Error starting ET process through ssh, please make sure your ssh works first`

**Comment by MisterTea** [comment]
@grakkpl Is this still an issue now that #244 has landed?
