### ISSUE TITLE
Unable to start etserver on Ubuntu after building from source

### ISSUE THREAD

**Issue by dandv** [MisterTea/EternalTerminal#210]
The issue is similar to #182. Even after modifying `et.service` to point to `/usr/local/bin/etserver` instead of `/usr/bin/etserver`, the process exits immediately with exit code 0:

```
$ sudo systemctl start et
$ sudo systemctl status et
● et.service - Eternal Terminal
   Loaded: loaded (/etc/systemd/system/et.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2019-07-30 01:58:54 EDT; 4s ago
  Process: 27219 ExecStart=/usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg (code=exited, status=0/SUCCESS)
 Main PID: 27225 (code=exited, status=0/SUCCESS)
```

Running `/usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg` manually works - it leaves the daemon running.

**Comment by jshort** [comment]
This is fixed by #209

**Comment by dandv** [comment]
Thanks! I've just tried the fix by cloning the repo and building, but I'm not completely sure what the steps are after `sudo make install`. I went ahead [per the README](https://github.com/MisterTea/EternalTerminal#debianubuntucentos) with

```
sudo cp ../systemctl/et.service /etc/systemd/system/
sudo cp ../etc/et.cfg /etc/
sudo systemctl enable et.service
sudo systemctl start et.service
```

but the `start` fails with 
> Job for et.service failed because the control process exited with error code.
>See "systemctl status et.service" and "journalctl -xe" for details.

```
$ systemctl status et.service
● et.service - Eternal Terminal
   Loaded: loaded (/etc/systemd/system/et.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-08-07 16:16:41 EDT; 2min 57s ago
  Process: 26714 ExecStart=/usr/bin/etserver --daemon --cfgfile=/etc/et.cfg (code=exited, status=203/EXEC)
 Main PID: 27225 (code=exited, status=0/SUCCESS)
```

`journalctl -xe` only shows a ssh disconnect message.

**Comment by MisterTea** [comment]
@dandv the et.service file itself has changed in et6, did you update that?
