### ISSUE TITLE
Super weird behavior when connecting via etserver vs. ssh

### ISSUE THREAD

**Issue by dandv** [MisterTea/EternalTerminal#211]
Any idea how come that the same commands run over an `et` connection behave differently vs. when they're run over a regular ssh shell connection?

1. [`crontab -e`](https://unix.stackexchange.com/questions/533012/crontab-waitpid-failed-waiting-for-pid-xxx-from-usr-bin-sensible-editor-n) produces an infinite loop of "crontab: waitpid() failed waiting for PID 3910 from "/usr/bin/sensible-editor": No child processes" messages
2. `apt update` (logged in as root) produces "Waited for apt-key but it wasn't there" for every repo:

  ```
# apt update
Hit:1 http://mirrors.digitalocean.com/ubuntu bionic InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease                                                                                                  
Hit:3 https://repos.influxdata.com/ubuntu bionic InRelease                                                                                                             
Hit:4 https://deb.nodesource.com/node_12.x bionic InRelease                                                                                                            
Hit:5 http://mirrors.digitalocean.com/ubuntu bionic-backports InRelease                                                                                                
Err:1 http://mirrors.digitalocean.com/ubuntu bionic InRelease                                                                                                          
  Waited for apt-key but it wasn't there
Hit:6 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease                                                                                                    
Hit:7 http://security.ubuntu.com/ubuntu bionic-security InRelease                              
Err:2 http://mirrors.digitalocean.com/ubuntu bionic-updates InRelease    
  Waited for apt-key but it wasn't there
```

Might there be some missing environment variable that `et` connections don't load/set?

**Comment by MisterTea** [comment]
Hey @dandv !  Can you run the "env" command on ssh and et sessions to see if there are any differences?  Once we see differences, then we can grep for them on your computer to figure out what setup ET is missing.

**Comment by dandv** [comment]
Duh, should've thought of that :)

Here's the diff (all other vars are the same):

![image](https://user-images.githubusercontent.com/33569/62268005-f5933180-b3f3-11e9-851a-a128f26fbdd7.png)

**Comment by MisterTea** [comment]
Hmm, those envars shouldn't cause the errors you are seeing?

You probably want to log in as a user and then "sudo su -" to get root.  Logging in as root can likely have issues.

**Comment by MisterTea** [comment]
Hey, actually this was a recent bug that should be fixed in https://github.com/MisterTea/EternalTerminal/commit/f7eb93b902e3662c647e1960e3bb57c423bff568 .  Please update to latest master and confirm.

**Comment by dandv** [comment]
Thanks for the fix! I tried building from source again the same way I documented in #203 but I ran into a missing file problem (`cxxopts.hpp`):

```
$ make && sudo make install
Scanning dependencies of target generated-code
[  1%] Running C++ protocol buffer compiler on proto/ET.proto
[  3%] Running C++ protocol buffer compiler on proto/ETerminal.proto
[  3%] Built target generated-code
Scanning dependencies of target et-lib
[  5%] Building CXX object CMakeFiles/et-lib.dir/external/easylogging++.cc.o
[  7%] Building CXX object CMakeFiles/et-lib.dir/src/base/BackedReader.cpp.o
In file included from /home/dandv/EternalTerminal-master/src/base/BackedReader.hpp:4:0,
                 from /home/dandv/EternalTerminal-master/src/base/BackedReader.cpp:1:
/home/dandv/EternalTerminal-master/src/base/Headers.hpp:62:10: fatal error: cxxopts.hpp: No such file or directory
 #include <cxxopts.hpp>
          ^~~~~~~~~~~~~
compilation terminated.
CMakeFiles/et-lib.dir/build.make:94: recipe for target 'CMakeFiles/et-lib.dir/src/base/BackedReader.cpp.o' failed
make[2]: *** [CMakeFiles/et-lib.dir/src/base/BackedReader.cpp.o] Error 1
CMakeFiles/Makefile2:250: recipe for target 'CMakeFiles/et-lib.dir/all' failed
make[1]: *** [CMakeFiles/et-lib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

Related to f601aab21165de0d05c797d67603924eb4c797f5 ?

**Comment by jshort** [comment]
@dandv did you do a recursive pull for git submodules?

**Comment by dandv** [comment]
Just did that now (see #214 for why I didn't do that before). The build and `sudo make install` completed successfully, but I'm [not sure how to start the service](https://github.com/MisterTea/EternalTerminal/issues/210#issuecomment-519254185).

I launched the daemon with `/usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg` (and `ps` shows it running) but when trying to connect to the host, now I get

> Error in authentication with etserver: Exception: Argument ‘--v=0’ starts with a - but has incorrect syntax

**Comment by MisterTea** [comment]
@dandv it is "--verbose" now, "--v" doesn't work because cxxopt doesn't support single letter longhand parameters.

**Comment by MisterTea** [comment]
@dandv probably this error is because your client is not up to date.

**Comment by dandv** [comment]
> probably this error is because your client is not up to date.

That was it, thanks!
