### ISSUE TITLE
Duplicate instructions to build from source

### ISSUE THREAD

**Issue by dandv** [MisterTea/EternalTerminal#214]
Looks like the README needs a do-over re. the build instructions. (I contributed to the duplication myself with #203). There are separate build instructions or a few Linux variants, then one separate section for Debian/Ubuntu/CentOS at https://github.com/MisterTea/EternalTerminal#debianubuntucentos

**Comment by MisterTea** [comment]
I pointed the website to the README so there should be one source of true for building.
