### ISSUE TITLE
Reconnect to session after killing client

### ISSUE THREAD

**Issue by tsoernes** [MisterTea/EternalTerminal#222]
Is this possible?
Say that you kill an `et` session on the client side. Can you reconnect to the same 'session' on the server?

**Comment by MisterTea** [comment]
No this isn't possible, but you can use tmux or screen to detach your session from et.

**Comment by tsoernes** [comment]
Can I make a feature request for that? tmux and screen are inconvenient wrt. scrolling etc

**Comment by MisterTea** [comment]
Use tmux control center (OSX) or HTM (other OSes) to get native scroll back. 

Making the et client survive being killed would be very difficult.

**Comment by dandv** [comment]
I'd also like the ability to reconnect to a session. My client machine ran out of battery, and now I have an orphan "session" on the remote server.

**Comment by MisterTea** [comment]
@dandv you can pass the "-x" switch to have et kill all other sessions by the same user before starting a new connection, or you can kill the orphan session manually.

It would be a huge amount of work to make et survive disconnects in a way that didn't compromise security.

**Comment by luismarques** [comment]
I just wanted to share that I also ran into this issue. I suggest that, at a minimum, the manual indicates that it's not possible to reconnect to a server if the client has died. But ideally this really should be possible.
