### ISSUE TITLE
Unable to compile on Mac because it lacks libutemper

### ISSUE THREAD

**Issue by MichaelBuckley** [MisterTea/EternalTerminal#224]
Hi,

The CMakeLists.txt file was recently updated to search for the UTemper library. This library does not exist on Mac, and isn't available in the homebrew package manager.

The call to `find_package` is directly outside of an `if(LINUX)` check. I could fix the issue by moving the `find_package` call into the `if(LINUX)` block, but I'm not sure if compiling with the library is intended for other non-Linux OSs (e.g. FreeBSD).

**Comment by MisterTea** [comment]
We have been looking for utempter for a year now. It isn't a required package so not having it is fine. You are probably hitting another cmake error.

**Comment by MichaelBuckley** [comment]
You're right. This was definitely a case of PEBKAC. My script to build for multiple platforms was parsing the output from that command incorrectly. Sorry for the noise.
