### ISSUE TITLE
Ubuntu PPA - arm64 packages 

### ISSUE THREAD

**Issue by frederickjh** [MisterTea/EternalTerminal#227]
Hi!
Trying to install on a Raspberry Pi 3 B+ which is arm64 architecture. Currently there does not appear to be a package for arm64 as the ´Packages.gz´ and the ´Packages.xz´ files in the PPA repository are empty.

Is it possible to create packages for arm64 for the PPA?

Thanks for considering this!
Frederick

**Comment by frederickjh** [comment]
I forgot to say that mosh was installable on the arm64 architecture as packages exist for it in the Ubuntu repositories.

**Comment by MisterTea** [comment]
It looks like launchpad only builds armhf: https://launchpad.net/~jgmath2000/+archive/ubuntu/et/+packages

**Comment by MisterTea** [comment]
Actually I found out how to enable arm64...

**Comment by frederickjh** [comment]
Thanks I was able to install `et` on the Raspberry Pi 3 B+.

**Comment by rahulraj80** [comment]
@frederickjh : Can you share the steps please? I am on Pi3B+ Raspbian/Stretch and the binaries and build instructions fail with different unmet dependencies like libc6 > 2.28 and cmake >= 3.14, which aptitude says is unsolvable.

**Comment by frederickjh** [comment]
Sorry @rahulraj80 no steps to share. I was using a different Linux distro Ubuntu. MisterTea enabled the build of the package for the arm64 architecture and I was able to install it using `apt` like any other package from the Ubuntu repositories.

**Comment by MisterTea** [comment]
@rahulraj80 Can you switch to buster or do you have to be on stretch?

**Comment by rahulraj80** [comment]
Thanks for clarifying, I erroneously assumed it would be the same arch.

Regards,
Rahul
________________________________

**Comment by rahulraj80** [comment]
Thanks @MisterTea:

After your tip, I went back and checked on two of my packages for which I was on Stretch. Turns out they have updated as well!! 🤦

Would never have checked had it not been for your feedback!

Thanks again, upgrade underway!
________________________________
