### ISSUE TITLE
Question: is all EternalTerminal traffic encrypted?

### ISSUE THREAD

**Issue by dtgriscom** [MisterTea/EternalTerminal#240]
As I understand from [https://eternalterminal.dev/howitworks/](https://eternalterminal.dev/howitworks/), ET uses ssh to do authentication, and then to exchange a session password. It then connects via a separate port for the duration of the session.

Question: is all traffic through that separate port encrypted?

(This might be a good thing to add to the documentation...)

**Comment by MisterTea** [comment]
Yes the rest of the traffic is encrypted. Please submit a PR adding that to the docs, thanks

**Comment by dtgriscom** [comment]
Happy to, but where? The only docs in the repo is the README.md, which doesn't address how ET works. Better would be a patch to https://eternalterminal.dev/howitworks/, as it explains the connection sequence; is the website in some repo somewhere?

**Comment by MisterTea** [comment]
The website code is in the gh-pages branch. So you can make changes there and submit a PR to that branch.

**Comment by dtgriscom** [comment]
(Oh, that's an ugly way to manage completely separate codebases.)

Done: thanks.

**Comment by MisterTea** [comment]
Yep, I agree with you, but it's how GitHub websites work.

**Comment by dtgriscom** [comment]
Thanks for merging my PR.
