### ISSUE TITLE
Is there a bound for the amount of memory/time used by ETServers?

### ISSUE THREAD

**Issue by dtgriscom** [MisterTea/EternalTerminal#243]
There are at least two ways that an ETServer could use an unbounded amount of memory:

1. An ETServer's task could generate enormous amounts of output while the client was disconnected

2. An ETServer could get disconnected from its client, and then the client killed before being able to reconnect and cleanly kill the server, leaving a zombie

This brings up a number of questions:

- Is there a time limit on how long an ETServer will wait for its client to reconnect, after which the server will cleanly kill itself?

- Is there a limit on how much data a disconnected ETServer will store before blocking or discarding the oldest data?

- Is there a limit on how many ETServers can be active on a single machine?

- Is there any way to get a summary of the active ETServer instances on a machine, with their states and current memory use? (This would have to be done thoughtfully, as it could be a security risk.)

**Comment by MisterTea** [comment]
Great questions. 

1. No, but I think a more elegant solution is for the server to stop reading characters from the terminal when the client is disconnected. This would block the shell program which (may?) block the program running on the shell, assuming that program is using blocking stdout.
2. Yes, IIRC it is around 64MB per connection. If a client is missing more than that, the server will kill the client. 
3. Nope
4. Not sure to be honest, but we do have a -x switch that kills all etservers for a user before starting a new one

**Comment by dtgriscom** [comment]
Thanks for the detailed responses:

>> - Is there a time limit on how long an ETServer will wait for its client to reconnect, after which the server will cleanly kill itself?
> 1. No, but I think a more elegant solution is for the server to stop reading characters from the terminal when the client is disconnected. This would block the shell program which (may?) block the program running on the shell, assuming that program is using blocking stdout.

I wouldn't like this, as often I'll be running compiles when I disconnect, and expect the work to continue while I'm disconnected, displaying all the output when I reconnect. That said, I expect having that as an option might help some users.

I think a user-configurable "disconnected" timeout, with a default of, say, 6 hours, would be broadly useful.

>>- Is there a limit on how much data a disconnected ETServer will store before blocking or discarding the oldest data?
> 2. Yes, IIRC it is around 64MB per connection. If a client is missing more than that, the server will kill the client.

Sounds good; is this user-configurable? (I assume not, in which case I'd request that feature...)

>>- Is there a limit on how many ETServers can be active on a single machine?
> 3. Nope

That, plus the current lack of a "timeout after no connection for X hours" feature, means that ET's memory consumption on a given machine will inevitably rise without bound.

I think it would also be useful to have a (perhaps per-user) ETServer limit.

>> - Is there any way to get a summary of the active ETServer instances on a machine, with their states and current memory use? (This would have to be done thoughtfully, as it could be a security risk.)
> 4. Not sure to be honest, but we do have a -x switch that kills all etservers for a user before starting a new one

So, any single user gets at most one ET session? Do people use that?

It would be great if sending some signal to the main ET process (SIGUSR1?) would log the current batch of servers and their states.

**Comment by MisterTea** [comment]
A user can have as many et sessions as they want.

Generally, the assumption with etserver is that there is either one client, or if there any many clients that they can be trusted.

**Comment by dtgriscom** [comment]
It isn't the trust part that I'm concerned about, it's the resource usage. I'm considering using ET to durably connect to a development machine that's often up for months. If every time my client died the server leaked memory, that would be a problem.

**Comment by MisterTea** [comment]
@dtgriscom You can use the -x switch to kill other clients when you connect or manually pkill etterminal processes that you aren't using.  Personally, I only need to do this when my client dies unexpectedly. Even then, it's typically only a few MB of ram that is wasted. If a client reconnects, there is no wasted memory.
