### ISSUE TITLE
Fails to install on Debian testing

### ISSUE THREAD

**Issue by haxwithaxe** [MisterTea/EternalTerminal#245]
Using Debian sid (testing) and running the install instructions for Debian verbatim produces this error
```
# apt install et
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 et : Depends: libprotobuf-lite10 but it is not installable
      Depends: libsodium18 (>= 0.6.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Changing the Debian release to buster, sid, or testing results in a 404 error when running `apt update`
It would be a good idea to have packages for the current stable release (buster), and nice to have them for testing (sid).

**Comment by arthurk** [comment]
Same problem here. The apt repo is not working `https://mistertea.github.io/debian-et/debian-source/` it shows 404 error

**Comment by yix** [comment]
Debian Buster is crying...

**Comment by MisterTea** [comment]
@haxwithaxe Try now, I rewrote the debian deployment script.

**Comment by oezh** [comment]
Still not working:

# apt install et
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 et : Depends: libprotobuf-lite10 but it is not installable
      Depends: libsodium18 (>= 0.6.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by foriequal0** [comment]
The debian source in the homepage should be changed to
```
deb https://github.com/MisterTea/debian-et/raw/master/debian-source/ buster main
```
`github.io` doesn't seem to properly serve file when it is stored in the Github LFS.
