### ISSUE TITLE
Building Eternal Terminal 6.x 

### ISSUE THREAD

**Issue by abnayak** [MisterTea/EternalTerminal#247]
I'm trying to build ET 6.0 version from source code for Cent OS. First thing I noticed is this version of ET now requires Protobuf libraries. My OS ships with an older version of Protobuf, so I install the protobuf 2.6.1 (does anyone know why ET isn't using latest version 3.x version of Protobuf?) from source code. Now, I'm able to build ET but when I try to execute _sudo /usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg_ I'm getting following error.

> /usr/local/bin/etserver: error while loading shared libraries: libprotobuf-lite.so.9: cannot open shared object file: No such file or directory

I've already defined the LD_LIBRARY_PATH and following is the output of ldd

```
linux-vdso.so.1 =>  (0x00007ffddddfa000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff677457000)
libprotobuf-lite.so.9 => /usr/lib/libprotobuf-lite.so.9 (0x00007ff677232000)
libsodium.so.23 => /usr/lib/libsodium.so.23 (0x00007ff676fdf000)
libutempter.so.0 => /usr/lib64/libutempter.so.0 (0x00007ff676ddd000)
libutil.so.1 => /lib64/libutil.so.1 (0x00007ff676bda000)
libresolv.so.2 => /lib64/libresolv.so.2 (0x00007ff6769c0000)
libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007ff67663b000)
libm.so.6 => /lib64/libm.so.6 (0x00007ff6763b7000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff6761a1000)
libc.so.6 => /lib64/libc.so.6 (0x00007ff675e0d000)
/lib64/ld-linux-x86-64.so.2 (0x00007ff677674000)
libz.so.1 => /lib64/libz.so.1 (0x00007ff675bf7000)
```
I'm sure, I'm not setting up something right but couldn't figure the root cause. Any help to resolve the problem is appreciated.

**Comment by MisterTea** [comment]
You need the protobuf-lite package in addition to protobuf

**Comment by abnayak** [comment]
Thanks @MisterTea for taking a look at the issue. I've the lite libraries in my system.

```
-rw-r--r-- 1 root root 26986174 Nov  7 07:17 libprotobuf.a
-rwxr-xr-x 1 root root      963 Nov  7 07:17 libprotobuf.la
-rw-r--r-- 1 root root  3631512 Nov  7 07:17 libprotobuf-lite.a
-rwxr-xr-x 1 root root      998 Nov  7 07:17 libprotobuf-lite.la
lrwxrwxrwx 1 root root       25 Nov  7 07:17 libprotobuf-lite.so -> libprotobuf-lite.so.9.0.1
lrwxrwxrwx 1 root root       25 Nov  7 07:17 libprotobuf-lite.so.9 -> libprotobuf-lite.so.9.0.1
-rwxr-xr-x 1 root root  1532102 Nov  7 07:17 libprotobuf-lite.so.9.0.1
lrwxrwxrwx 1 root root       20 Nov  7 07:17 libprotobuf.so -> libprotobuf.so.9.0.1
lrwxrwxrwx 1 root root       20 Nov  7 07:17 libprotobuf.so.9 -> libprotobuf.so.9.0.1
-rwxr-xr-x 1 root root 11257443 Nov  7 07:17 libprotobuf.so.9.0.1
-rw-r--r-- 1 root root 33870206 Nov  7 07:17 libprotoc.a
-rwxr-xr-x 1 root root      973 Nov  7 07:17 libprotoc.la
lrwxrwxrwx 1 root root       18 Nov  7 07:17 libprotoc.so -> libprotoc.so.9.0.1
lrwxrwxrwx 1 root root       18 Nov  7 07:17 libprotoc.so.9 -> libprotoc.so.9.0.1
-rwxr-xr-x 1 root root 12464579 Nov  7 07:17 libprotoc.so.9.0.1
```
I got these after building the https://github.com/protocolbuffers/protobuf source code. I can't find the lite version of the library. Do you to point what I need to build for protobuf-lite?

**Comment by MisterTea** [comment]
Hey @abnayak Maybe you have two versions of protobuf installed?

Also check out the deployment/centos.Dockerfile file.  That is a centos-based docker image that installs eternal terminal.
