### ISSUE TITLE
ET not very "eternal"

### ISSUE THREAD

**Issue by joshim5** [MisterTea/EternalTerminal#248]
My eternal terminal is not very "eternal." Whenever I disconnect from the internet, my session terminates. Here are logs (running in verbose mode). How can go about resolving this issue?

[INFO 2019-11-19 08:20:10,540 etserver-main TerminalServerMain.cpp:139] In child, about to start server.
[INFO 2019-11-19 08:20:10,541 etserver-main TcpSocketHandler.cpp:202] Listening on 0.0.0.0:8080/2/1/6
[INFO 2019-11-19 08:20:10,541 etserver-main TcpSocketHandler.cpp:202] Listening on 0.0.0.0:8080/10/1/6
[INFO 2019-11-19 08:20:10,541 etserver-main TerminalServer.cpp:20] Creating server
[INFO 2019-11-19 08:20:10,880 server-clientHandler ServerConnection.cpp:66] Got client with id: xxxxxxxxxxxxx2
[ERROR 2019-11-19 08:20:10,880 server-clientHandler ServerConnection.cpp:77] Got a client that we have no key for

[INFO 2019-11-19 08:19:34,795 terminal-main PipeSocketHandler.cpp:55] Connected to endpoint /tmp/etserver.idpasskey.fifo
[INFO 2019-11-19 08:19:34,796 terminal-main PipeSocketHandler.cpp:74] 6 is a good socket
[INFO 2019-11-19 08:20:10,532 terminal-main UserTerminalHandler.cpp:186] Router has ended abruptly.  Killing terminal session.

[INFO 2019-11-19 08:19:21,237 etserver-main TerminalServerMain.cpp:139] In child, about to start server.
[INFO 2019-11-19 08:19:21,238 etserver-main TcpSocketHandler.cpp:202] Listening on 0.0.0.0:8080/2/1/6
[INFO 2019-11-19 08:19:21,238 etserver-main TcpSocketHandler.cpp:202] Listening on 0.0.0.0:8080/10/1/6
[INFO 2019-11-19 08:19:21,238 etserver-main TerminalServer.cpp:20] Creating server
[INFO 2019-11-19 08:19:21,966 server-clientHandler ServerConnection.cpp:66] Got client with id: xxxxxxxxxxxx1
[ERROR 2019-11-19 08:19:21,966 server-clientHandler ServerConnection.cpp:77] Got a client that we have no key for
[INFO 2019-11-19 08:19:22,306 server-clientHandler ServerConnection.cpp:66] Got client with id: xxxxxxxxxxxx1
[ERROR 2019-11-19 08:19:22,307 server-clientHandler ServerConnection.cpp:77] Got a client that we have no key for
[INFO 2019-11-19 08:19:34,795 etserver-main UserTerminalRouter.cpp:18] Listening to id/key FIFO
[INFO 2019-11-19 08:19:34,796 etserver-main UserTerminalRouter.cpp:28] Connected
[INFO 2019-11-19 08:19:42,410 server-clientHandler ServerConnection.cpp:66] Got client with id: xxxxxxxxxxxxx2
[INFO 2019-11-19 08:19:42,410 server-clientHandler ServerConnection.cpp:92] New client.  Setting up connection
[INFO 2019-11-19 08:19:42,527 140351272077056 TerminalServer.cpp:372] RUNNING TERMINAL
[INFO 2019-11-19 08:19:42,644 z7YnPo8JFC44iPXx TerminalServer.cpp:324] Got terminal info
[INFO 2019-11-19 08:19:49,085 z7YnPo8JFC44iPXx TerminalServer.cpp:318] Got keep alive
[INFO 2019-11-19 08:20:01,071 z7YnPo8JFC44iPXx Connection.cpp:155] Closing socket because 32 Broken pipe
[INFO 2019-11-19 08:20:07,333 server-clientHandler ServerConnection.cpp:66] Got client with id: xxxxxxxxxxxxx2
[INFO 2019-11-19 08:20:07,333 server-clientHandler Connection.cpp:92] Locking reader/writer to recover...
[INFO 2019-11-19 08:20:07,333 server-clientHandler Connection.cpp:95] Recovering with socket fd 11...
[INFO 2019-11-19 08:20:07,450 server-clientHandler Connection.cpp:131] Finished recovering with socket fd: 11

[INFO 2019-11-19 08:18:20,297 etserver-main TerminalServerMain.cpp:139] In child, about to start server.
[ERROR 2019-11-19 08:18:20,298 etserver-main TcpSocketHandler.cpp:187] Error binding 2/1/6: 98 Address already in use
[ERROR 2019-11-19 08:18:20,298 etserver-main UnixSocketHandler.cpp:156] Tried to close a connection that doesn't exist: 7

[INFO 2019-11-19 08:12:40,175 terminal-main PipeSocketHandler.cpp:55] Connected to endpoint /tmp/etserver.idpasskey.fifo
[INFO 2019-11-19 08:12:40,175 terminal-main PipeSocketHandler.cpp:74] 6 is a good socket
[INFO 2019-11-19 08:18:20,293 terminal-main UserTerminalHandler.cpp:186] Router has ended abruptly.  Killing terminal session.

**Comment by adamrt** [comment]
It would be helpful if you provided any relevant information

- What version(s) of ET 
- What OS/Version(s)
- Any relevant custom config
- Any other specifics that would help

**Comment by MisterTea** [comment]
Hey @joshim5 are multiple people using the same terminal server?  It looks like you and another person may be trying to map the same remote port.
