### ISSUE TITLE
"fork me" on https://eternalterminal.dev/ doesn't take me to source so that I can make a PR to the website

### ISSUE THREAD

**Issue by ElijahLynn** [MisterTea/EternalTerminal#252]
"fork me" on https://eternalterminal.dev/ doesn't take me to source so that I can make a PR to the website, takes me here, which I can't seem to find the source markdown Jekyll files for the website. 

I want to add a section for "How it works" right in the main content area, because I initially was looking there and didn't see it hanging out on the top right nav for quite some time.

**Comment by ctsrc** [comment]
@ElijahLynn Have a look at the gh-pages branch.

https://github.com/MisterTea/EternalTerminal/tree/gh-pages

**Comment by ElijahLynn** [comment]
> @ElijahLynn Have a look at the gh-pages branch.
> 
> https://github.com/MisterTea/EternalTerminal/tree/gh-pages

Thanks for that pointer, will do.
