### ISSUE TITLE
Eternal Terminal server binds to all interfaces by default, and cannot be configured to bind to only some interfaces

### ISSUE THREAD

**Issue by ctsrc** [MisterTea/EternalTerminal#256]
By default Eternal Terminal server will bind to all interfaces.

In my case that is not desirable and I would like to limit it to listen only on a specific network interface / selection of IPv4 and IPv6 addresses.

Most server software will allow you to configure this, such as for example OpenSSH.

**Comment by MisterTea** [comment]
Hey @ctsrc, is it enough to limit to ipv4/ipv6 or do you also need control over the specific interface?

**Comment by ctsrc** [comment]
Hi @MisterTea, in my case I would need for it to be able to bind to a specific set of IPv4 and IPv6 addresses and not on others.

**Comment by sporkman** [comment]
I'll second this one. I frequently have machines with multiple IPs that are used for jails (lightweight virtualization) and the jails cannot make use of port 2022 (or whatever I set et up for) if the process on the host is binding all IPs.

Also *not* having an option to limit bind IPs is bordering on a POLA violation, IMHO - I can't think of another commonly-used daemon that doesn't allow for this.
