### ISSUE TITLE
Make a new minuscule release?

### ISSUE THREAD

**Issue by ctsrc** [MisterTea/EternalTerminal#259]
Hi, now that you've merged the two PRs that I submitted, I was wondering if you could tag a new release and call it v6.0.5?

Then I can contact the FreeBSD package maintainers about updating the package to include the rc.d service file that my PR added, as well as for them to include the default config in the package also.

**Comment by MisterTea** [comment]
Yep, it will be a good chance to test this new deployment system.

**Comment by ctsrc** [comment]
Excellent :)

**Comment by MisterTea** [comment]
Pushed 6.0.5
