### ISSUE TITLE
et server core dumps on Ubuntu on incoming connection

### ISSUE THREAD

**Issue by mblais** [MisterTea/EternalTerminal#265]
```
$ sudo systemctl status et
● et.service - Eternal Terminal
   Loaded: loaded (/etc/systemd/system/et.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Thu 2019-12-05 23:09:39 UTC; 18min ago
  Process: 14515 ExecStart=/usr/bin/etserver --daemon --cfgfile=/etc/et.cfg (code=exited, status=0/SUCCESS)
 Main PID: 14520 (code=dumped, signal=ABRT)

Dec 05 22:41:44 redacted.com systemd[1]: Starting Eternal Terminal...
Dec 05 22:41:44 redacted.com systemd[1]: et.service: PID file /var/run/etserver.pid not readable (yet?) after start: No such file or directory
Dec 05 22:41:44 redacted.com systemd[1]: Started Eternal Terminal.
Dec 05 23:09:39 redacted.com systemd[1]: et.service: Main process exited, code=dumped, status=6/ABRT
Dec 05 23:09:39 redacted.com systemd[1]: et.service: Unit entered failed state.
Dec 05 23:09:39 redacted.com systemd[1]: et.service: Failed with result 'core-dump'.
```
et is version 6.0.0 (client and server), both are default configuration.
et server is on Ubuntu 16.04.6 LTS (Amazon LightSail server with Bitnami Wordpress) - ports 22 and 2022 are open.
et client is running under Windows WSL - Ubuntu 18.04.3 LTS

I have the core dump file from the server, if that's helpful

> Then run this on your server:
`tar -cvzPhf /tmp/etserverLogs.tar.gz /tmp/etserver_err /tmp/etserver.INFO`

I got:
```
tar -cvzPhf /tmp/etserverLogs.tar.gz /tmp/etserver_err /tmp/etserver.INFO                                                        /opt/bitnami 
tar: /tmp/etserver_err: Cannot stat: No such file or directory
tar: /tmp/etserver.INFO: Cannot stat: No such file or directory
```

**Comment by MisterTea** [comment]
Please update to 6.0.4 and try again

**Comment by mblais** [comment]
> Please update to 6.0.4 and try again
Hm, looks like it already is at 6.0.4, but the version message is inaccurate?
```
$ apt-get install et
et is already the newest version (6.0.4-bionic2).

$ et --version
et version 6.0.0
```

**Comment by MisterTea** [comment]
You have two versions of et installed. Do a "which et" and see if there is an old version in /usr/local/bin

**Comment by mblais** [comment]
> You have two versions of et installed. Do a "which et" and see if there is an old version in /usr/local/bin

Ah. Ok, I fixed that, but I still get a core dump on et-server when I try to connect.

**Comment by MisterTea** [comment]
Can you get us a stack trace?

**Comment by mblais** [comment]
> Can you get us a stack trace?

No symbols 🙁
[etserver.gdb.1.log](https://github.com/MisterTea/EternalTerminal/files/3935848/etserver.gdb.1.log)

**Comment by MisterTea** [comment]
It's a log fatal in this function https://github.com/MisterTea/EternalTerminal/blob/master/src/terminal/UserTerminalRouter.cpp#L17

There should be a file that matches this: /tmp/et* with the log message.

**Comment by mblais** [comment]
> There should be a file that matches this: /tmp/et* with the log message.

Here you go:  [et-logs-1.gz](https://github.com/MisterTea/EternalTerminal/files/3937231/et-logs-1.gz)

**Comment by MisterTea** [comment]
@mblais  The server isn't running 6.0.4.  Can you check to see if you have an extra etserver or etterminal binary on your machine?  Maybe you have one in /usr/local/bin as what happened in the client.

**Comment by mblais** [comment]
The server says it's **/usr/bin/etserver** which is 6.0.4 ...
```$ sudo systemctl status et
● et.service - Eternal Terminal
   Loaded: loaded (/etc/systemd/system/et.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Sun 2019-12-08 04:08:56 UTC; 1 day 4h ago
  Process: 16113 ExecStart=/usr/bin/etserver --daemon --cfgfile=/etc/et.cfg (code=exited, status=0/SUCCESS)
 Main PID: 16116 (code=dumped, signal=ABRT)

Dec 08 04:02:40 lucretiasworld.com systemd[1]: Starting Eternal Terminal...
Dec 08 04:02:40 lucretiasworld.com systemd[1]: et.service: PID file /var/run/etserver.pid not readable (yet?) after start: No such file or directory
Dec 08 04:02:40 lucretiasworld.com systemd[1]: Started Eternal Terminal.
Dec 08 04:08:56 lucretiasworld.com systemd[1]: et.service: Main process exited, code=dumped, status=6/ABRT
Dec 08 04:08:56 lucretiasworld.com systemd[1]: et.service: Unit entered failed state.
Dec 08 04:08:56 lucretiasworld.com systemd[1]: et.service: Failed with result 'core-dump'.

$ /usr/bin/etserver --version
et version 6.0.4
```
Same for the client side:
```
$ which et
/usr/bin/et

$ /usr/bin/et --version
et version 6.0.4
```
I deleted all traces I could find of other versions on both sides.

**Comment by MisterTea** [comment]
can you "rm -Rf /tmp/et*" to clear the logs and then restart the server and try again?

**Comment by mblais** [comment]
OK, same result, here's the new server logs:  
[et-logs.gz](https://github.com/MisterTea/EternalTerminal/files/3938917/et-logs.gz)

**Comment by MisterTea** [comment]
It looks like your client is still running 6.0.0 somehow.  Can you try doing "et localhost" on the server and see if that works?

**Comment by MisterTea** [comment]
Can you also try this on the server:

/usr/bin/etterminal --version

**Comment by MisterTea** [comment]
Something drastic you can try:

find /usr | grep "/et[server|terminal]*$"

then delete everything you find on both client and server.  Then reinstall 6.0.4 and try again.

**Comment by mblais** [comment]
You were right - `6.0.0` was in /usr/local/bin on both machines. Sorry, I thought I had already checked there 🙄

Looks like it's all working now. Thanks for your help 🙏
