### ISSUE TITLE
Feature: Change the server address on a running session(s)

### ISSUE THREAD

**Issue by singalen** [MisterTea/EternalTerminal#268]
Sometimes the remote server changes its address, and cannot be addressed by a domain name.
Would love to have a way to change the server IP address/name on an already running session(s). Like:
`et --switch-sessions 192.168.1.2:rpi4.local` (in `from:to` format).

**Comment by MisterTea** [comment]
Why can't you use a domain name?

**Comment by singalen** [comment]
I can think of a few use cases:
* The host doesn't originally have one, and I don't have the access to `/etc/hosts`.
* Sometimes we just use the IP addresses, and think of creating a domain name alias in `/etc/hosts` just after the fact (my case).
On a second thought, case 1 is not very frequent. Next time, I will use an alias.

**Comment by MisterTea** [comment]
Going to close, but if you or someone else implements this, I'm happy to accept a PR.
