### ISSUE TITLE
Error starting ET process through ssh, please make sure your ssh works first

### ISSUE THREAD

**Issue by iomari** [MisterTea/EternalTerminal#270]
I keep getting "Error starting ET process through ssh, please make sure your ssh works first". 
And of course ssh and mosh both work between the same client/server. Anyone know what might be wrong?
ET It works fine on my BeagleBoneBlack running Ubuntu.
ET fails with the above message on all 3 of my Tinkerboards all running the same Ubuntu Bionic as the BeagleBoneBlack.
All 4 systems are using the same ssh config files and the same et.cfg file.
Any suggestions?

thanks in advance
iomari

**Comment by MisterTea** [comment]
Please check the logs for details.  You can also set verbose=1 in /etc/et.cfg to get more details.

**Comment by iomari** [comment]
Thank you. Setting verbose  to 1 still produces the single line error.
I can't seem to find which log file to monitor. My ssh uses /var/log/kern.log bit I don't see ET logs there.

**Comment by iomari** [comment]
here are logs when I connect to 2 different machines with identical setups (/etc/ssh identical and /etc/et.cfg identical). The first connects, the second doesn't:

# et --logtostdout iomari@192.168.1.34                                                                                                                                                                               [INFO 2020-01-15 10:00:38,468 client-main TerminalClientMain.cpp:163] Parsed ssh config file, connecting to 192.168.1.34
[INFO 2020-01-15 10:00:38,469 client-main TcpSocketHandler.cpp:89] Connected to server: 192.168.1.34 using fd 5
[INFO 2020-01-15 10:00:39,006 client-main SshSetupHandler.cpp:118] etserver started
[INFO 2020-01-15 10:00:39,006 client-main TerminalClientMain.cpp:234] ID PASSKEY: 0CO9wmXplrEZuzg2 WlmtWNTD4rsFrSDVhSpdY3subBF0pqoi
[INFO 2020-01-15 10:00:39,007 client-main TcpSocketHandler.cpp:89] Connected to server: 192.168.1.34 using fd 6
[INFO 2020-01-15 10:00:39,029 client-main TerminalClient.cpp:329] Window size changed: row: 49 column: 214 width: 0 height: 0

iomari@bbb-34:~$
^^^^ WORKING ^^^^

# et --logtostdout iomari@192.168.1.92                                                                                                                                                                               

[INFO 2020-01-15 10:00:12,101 client-main TerminalClientMain.cpp:163] Parsed ssh config file, connecting to 192.168.1.92
[INFO 2020-01-15 10:00:12,102 client-main TcpSocketHandler.cpp:89] Connected to server: 192.168.1.92 using fd 5
ERROR: unknown command line flag 'verbose'
IError starting ET process through ssh, please make sure your ssh works first 

^^^ NOT WORKING  ^^^

**Comment by iomari** [comment]
when I run:
tail -f /var/log/auth.log on the machine in question. I receive 2 additional lines (in bold text) that I don't receive on the machine that connects properly.

Jan 15 10:26:16 TK-92 sshd[30550]: Accepted publickey for iomari from 192.168.1.5 port 33990 ssh2: RSA SHA256:9fkJ6AFksiVUBOGvobgXg4ydDE9BPsV4djPOx8aWwKg
Jan 15 10:26:16 TK-92 sshd[30550]: pam_unix(sshd:session): session opened for user iomari by (uid=0)
Jan 15 10:26:16 TK-92 systemd-logind[324]: New session c586 of user iomari.
Jan 15 10:26:16 TK-92 sshd[30585]: Received disconnect from 192.168.1.5 port 33990:11: disconnected by user
Jan 15 10:26:16 TK-92 sshd[30585]: Disconnected from user iomari 192.168.1.5 port 33990
Jan 15 10:26:16 TK-92 sshd[30550]: pam_unix(sshd:session): session closed for user iomari
**Jan 15 10:26:16 TK-92 systemd-logind[324]: Session c586 logged out. Waiting for processes to exit.
Jan 15 10:26:16 TK-92 systemd-logind[324]: Removed session c586**.

**Comment by MisterTea** [comment]
The problem is that the second machine doesn't have the latest version of et installed on it.  Make sure you install 6.0.5 on all machines.
