### ISSUE TITLE
EternalTerminal disconnect blocks Python stdout output; halting program progress

### ISSUE THREAD

**Issue by tsoernes** [MisterTea/EternalTerminal#278]
I have a Python terminal program which outputs its progress with a progress bar (tqdm). I'm running it on remote server, and using ET to connect to that server. 

I have a problem though: when the connection is temporarily closed, python programs that prints program output are paused. I think the cause might be that stdout printing is blocked, causing the program to effectively wait and make no progress until connection is re-established.

How can this problem be addressed?

**Comment by tsoernes** [comment]
This can be addressed by running the python program with `nohup`. E.g. `nohup python myprog.py & tail -f nohup.out`

**Comment by MisterTea** [comment]
Yep, you can also run inside of tmux
