### ISSUE TITLE
Debian package for arm (raspberry pi) needed

### ISSUE THREAD

**Issue by mstoops** [MisterTea/EternalTerminal#279]
I tried installing ET on my RPi following the Debian installation steps in the README, but found there were no `arm` binaries. 

I was able to manually compile and run (on Rasbian) with little issue, following the [very well-written] instructions in the README, but similar to issue #227 there is no arm32/64 package to make installation easier. I don't know whether I need arm32 or arm64, although since #227 requested arm64, I would guess that's what is needed (when I `file /bin/ls` it tells me it's ELF 32-bit, so maybe Rasbian is 32-bit).

Cheers.

**Comment by MisterTea** [comment]
There should be arm binaries now
