### ISSUE TITLE
macOS to macOS via brew

### ISSUE THREAD

**Issue by kour1er** [MisterTea/EternalTerminal#283]
I've only just discovered ET so please forgive any newbie errors. I'm connecting between two Macs both running the latest version of Catalina (10.15.3). I've installed EternalTerminal via brew on both systems (6.0.5).

I can connect fine and the connection persists, however when I put one machine to sleep, wait a couple of hours, then wake up, I get a crash appear in the log on the always on Mac and a disconnect on the client.

---
[FATAL 2020-02-16 18:13:19,649 etserver-main easylogging++.cc:2876] CRASH HANDLED; Application has crashed due to [SIGINT] signal
    ======= Backtrace: =========
    [1]  0x000000010320f325 :el::base::debug::logCrashReason(int, bool, el::Level, char const*)
    [2]  0x000000010323b30a :el::base::debug::defaultCrashHandler(int) (.cold.1)
    [3]  0x000000010320e9f9 :el::base::debug::defaultCrashHandler(int)
    [4]  0x00007fff6357342d :_platform.dylib            0x00007fff6357342d _sigtramp
    [5] 6   ???                                 0x0000000000000000 0x0 + 0 
    [6] 7   etserver                            0x00000001031d31f6 main + 5890 
    [7] 8   libdyld.dylib                       0x00007fff633757fd start + 1 

[WARNING 2020-02-16 18:13:19,650 etserver-main easylogging++.cc:2876] Aborting application. Reason: Fatal log at [/tmp/et-20200202-86706-1i3ksq6/EternalTerminal-et-v6.0.5/external_imported/easyloggingpp/src/easylogging++.cc:2876] 

---

The path at the end of that (/tmp/et-20200202-86706-1i3ksq6) doesn't appear to exist so I can't look there for further information. Am I doing something obviously stupid?

Many thanks for any pointers that someone could offer.

**Comment by MisterTea** [comment]
When connecting to OS/X systems, you need to pass ```--prefix=/usr/local``` to the et command

**Comment by jshort** [comment]
Quick follow up if people find this:  in older releases of the `et` client binary, the option was `--prefix` and requires a full path to the `etterminal` binary (`--prefix=/usr/local/bin/etterminal`) but has been replaced with the `--terminal-path` option to make it clear (since it actually wasn't a prefix).  Alternatively  you can use the `--macserver` option which does exactly this if `etterminal` is in /usr/local/bin.
