### ISSUE TITLE
Should OS-X to FreeBSD work?

### ISSUE THREAD

**Issue by sporkman** [MisterTea/EternalTerminal#284]
Looking to use et between my laptop and a cloud host that's my ssh jumphost - the idea if it works is to use iTerm2 with tmux integration (which I already use), but with et allowing for persistence.

So far I've run into a few issues:

- for the life of me I'm not finding manpages or similar with some explanation of what each installed binary is and what all the options are
- on the server, not seeing how to make et not bind to all IPs - I have jails on the host that want to use IPs/ports that the main et is grabbing
- not seeing how to get the server to just log to syslog instead of dumping random stuff in /tmp (feels not terribly secure to put this info in a public directory)
- the FreeBSD rc script has a "--pidfile" argument to startup, but the et server binary claims there's no "--pidfile" option
- the "verbose" option is not being very verbose for me, I get a single-line error

So for whatever it's worth, the server is running, using the official FreeBSD package, latest available: https://www.freshports.org/net/eternalterminal/

The client on OS-X 10.14 is 6.0.6 from homebrew.

When trying to connect to a host with et that I can connect to via ssh, I'm getting this single-line error:

```
spork@GaseousWeiner ~ $ et --verbose=9 myhost
Error starting ET process through ssh, please make sure your ssh works first
spork@GaseousWeiner ~ $
```

Digging around in /tmp, I get this (client, then server):

```
[INFO 2020-02-22 01:29:46,913 client-main TerminalClientMain.cpp:163] Parsed ssh config file, connecting to myhost
[V1 2020-02-22 01:29:46,913 client-main TerminalClientMain.cpp:11] Connecting
[V4 2020-02-22 01:29:46,935 client-main TcpSocketHandler.cpp:77] Before selecting sockFd
[V4 2020-02-22 01:29:46,936 client-main TcpSocketHandler.cpp:81] sockFd 7is selected7
[INFO 2020-02-22 01:29:46,936 client-main TcpSocketHandler.cpp:89] Connected to server: myhost.example.com using fd 7
[V1 2020-02-22 01:29:46,936 client-main UnixSocketHandler.cpp:161] Closing connection: 7

SERVER

[ERROR 2020-02-22 01:28:24,401 server-clientHandler ServerConnection.cpp:119] Error handling new client: Failed a call to readAll
[ERROR 2020-02-22 01:29:42,690 server-clientHandler ServerConnection.cpp:119] Error handling new client: Failed a call to readAll
[ERROR 2020-02-22 01:29:46,938 server-clientHandler ServerConnection.cpp:119] Error handling new client: Failed a call to readAll
[ERROR 2020-02-22 01:56:05,210 server-clientHandler ServerConnection.cpp:119] Error handling new client: Failed a call to readAll
```

Any ideas where to start with this?

**Comment by MisterTea** [comment]
What version is the server running?  I am not the maintainer of the freebsd package so possibly it's out of sync

**Comment by sporkman** [comment]
Sorry, thought I already followed up. The server version is older (eternalterminal-5.1.9_5). I was assuming that there would be backwards compatibility in the client though...

**Comment by MisterTea** [comment]
Major versions are not backwards compatible.  We try to only push our major versions when we absolutely need to.

**Comment by sporkman** [comment]
Shoot, I hope this is OK and I can re-close, but wanted to add notes to anyone finding this:

- I contacted the FreeBSD port maintainer, did not hear back yet, but...
- I was able to compile the latest version on FreeBSD 12.1 with zero patches or anything, so there's literally nothing for the port maintainer to do than update the checksum and version number
- The version I built works fine, using it for most of the day w/o issue
