### ISSUE TITLE
can not start et service on centos7

### ISSUE THREAD

**Issue by shz0116** [MisterTea/EternalTerminal#286]
After following instructions from READMEfile and built from source,
I failed to start the service:

$ sudo systemctl start et.service 
Job for et.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status et.service" and "journalctl -xe" for details.

$ systemctl status et.service
● et.service - Eternal Terminal
     Loaded: loaded (/etc/systemd/system/et.service; enabled; vendor preset: enabled)
     Active: failed (Result: core-dump) since Mon 2020-02-24 18:06:08 PST; 2min 46s ago
    Process: 4124425 ExecStart=/usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg (code=dumped, signal=ABRT)
        CPU: 3ms

**Comment by MisterTea** [comment]
What do the logs say?

**Comment by shz0116** [comment]
Could you tell me where are he log files ?

**Comment by MisterTea** [comment]
/tmp/et*.log

Also check out https://github.com/MisterTea/EternalTerminal/pull/277

**Comment by shz0116** [comment]
After upgrading the gcc compiler to 7.3.1, I can build etserver now and start the service on server.
$ sudo systemctl status et.service
● et.service - Eternal Terminal
     Loaded: loaded (/etc/systemd/system/et.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-02-25 02:49:54 PST; 4s ago
    Process: 1547212 ExecStart=/usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg (code=exited, status=0/SUCCESS)
   Main PID: 1547214 (etserver)
         IO: 0B read, 0B written
      Tasks: 9
     Memory: 1.1M
        CPU: 43ms
     CGroup: /system.slice/et.service
             └─1547214 /usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg

Feb 25 02:49:54 devvm694.vll1.facebook.com systemd[1]: Starting Eternal Terminal...
Feb 25 02:49:54 devvm694.vll1.facebook.com systemd[1]: et.service: Supervising process 1547214 which is not our child. We'll most likely
Feb 25 02:49:54 devvm694.vll1.facebook.com systemd[1]: Started Eternal Terminal.

However, on client side, using et could not connect to server, using ssh is ok:
% et --logtostdout MYSERVER
[INFO 2020-02-25 02:51:34,448 client-main ParseConfigFile.hpp:1342] unsupported config line:   AddKeysToAgent yes
, ignored
[INFO 2020-02-25 02:51:34,448 client-main ParseConfigFile.hpp:1342] unsupported config line:   UseKeychain yes
, ignored
[INFO 2020-02-25 02:51:34,448 client-main ParseConfigFile.hpp:1342] unsupported config line:   IdentityFile ~/.ssh/id_rsa
, ignored
[INFO 2020-02-25 02:51:34,449 client-main ParseConfigFile.hpp:1342] unsupported config line: 	SendEnv LANG LC_*
, ignored
[INFO 2020-02-25 02:51:34,449 client-main ParseConfigFile.hpp:1342] unsupported config line: Match host *.MYSERVER*
, ignored
[INFO 2020-02-25 02:51:34,449 client-main ParseConfigFile.hpp:1342] unsupported config line: 	GSSAPIAuthentication yes
, ignored
[INFO 2020-02-25 02:51:34,449 client-main ParseConfigFile.hpp:1342] unsupported config line: 	PubkeyAuthentication no
, ignored
[INFO 2020-02-25 02:51:34,449 client-main TerminalClientMain.cpp:163] Parsed ssh config file, connecting to devvm694.vll1.facebook.com
[INFO 2020-02-25 02:51:58,745 client-main TcpSocketHandler.cpp:62] Error connecting with MYSERVER: 60 Operation timed out
[ERROR 2020-02-25 02:51:58,746 client-main TcpSocketHandler.cpp:130] ERROR, no host found
Could not reach the ET server: MYSERVER:2022

Here is my .ssh/config file:
% cat ~/.ssh/config 
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa

LOG on the server side:
Here is the log on the server side:
180 [V1 2020-02-25 06:03:10,798 etserver-main ServerConnection.cpp:16] Accepting connection
181 [V1 2020-02-25 06:03:10,799 etserver-main ServerConnection.cpp:21] SERVER: got client socket fd: 10
182 [ERROR 2020-02-25 06:03:10,799 server-clientHandler ServerConnection.cpp:118] Error handling new client: Invalid size (<0 or >128 MB): 72058693583176470
183 [V1 2020-02-25 06:03:10,799 server-clientHandler UnixSocketHandler.cpp:161] Closing connection: 10

I am also using VPN. Is it a problem ?

**Comment by MisterTea** [comment]
If you work at Facebook, please use the directions in the internal wiki to get ET because we do see custom setup.  Let's follow up in workchat if you still have an issue.
