### ISSUE TITLE
Latest client (6.0.6) doesn't work with etserver 5.1.9

### ISSUE THREAD

**Issue by emadfarag** [MisterTea/EternalTerminal#290]
I'm trying to connect to an etserver 5.1.9 running on linux with a 6.0.6 client. It fails to connect, but I am to connect with an old client. I unfortunately don't control what version runs on the server, so it would be great if backwards compatibility could be maintained. Here's the error I get when connecting from 6.0.6.

```
[INFO 2020-02-29 13:54:20,327 client-main TerminalClientMain.cpp:163] Parsed ssh config file, connecting to server
[V1 2020-02-29 13:54:20,327 client-main TerminalClientMain.cpp:11] Connecting
[V4 2020-02-29 13:54:20,365 client-main TcpSocketHandler.cpp:77] Before selecting sockFd
[V4 2020-02-29 13:54:20,365 client-main TcpSocketHandler.cpp:81] sockFd 7is selected7
[INFO 2020-02-29 13:54:20,365 client-main TcpSocketHandler.cpp:89] Connected to server: server using fd 7
[V1 2020-02-29 13:54:20,365 client-main UnixSocketHandler.cpp:161] Closing connection: 7
ERROR: unknown command line flag 'verbose'
Error starting ET process through ssh, please make sure your ssh works first
```

**Comment by MisterTea** [comment]
Each major version is backwards breaking, which is why we try to limit the number of major version updates.

**Comment by emadfarag** [comment]
It would be nice to at least print that out indicating that the version mismatch is the reason it's not working, if it's possible.
