### ISSUE TITLE
Error connecting to server: 3: Client is not registered

### ISSUE THREAD

**Issue by dandv** [MisterTea/EternalTerminal#294]
Got this error after rebuilding the server from the Nov 30 version (c457ba880d3328ea0c4e0d69132d91dc69371e3c) to the current build, and connecting to it with the built client.

Turns out I had forgotten to restart the server. After restarting it, I could connect fine.

I remember I ran into another cryptic (to me) error when the client and the server were not of the same build. Any way to detect these situations and tell the user that they need the same (or a compatible) version?

**Comment by MisterTea** [comment]
We have checks but unfortunately when we make a major revision it's usually to break the protocol and it's often that we need to also break the check.  As things become more stable, new major versions should be very rare.
