### ISSUE TITLE
Not picking up port from ~/.ssh/config

### ISSUE THREAD

**Issue by cduguet** [MisterTea/EternalTerminal#300]
Hello, I have trouble getting the port from the ~/.ssh/config file. 
```
$ et --version
et version 6.0.7
```
``` $ et server
Could not reach the ET server: xxx.xxx.org:2022
```

This is how my ~/.ssh/config looks like 
```
Host server
   HosName xxx.xxx.org
   Port 1313
   User xxx
   LocalForward 8888 127.0.0.1:8888
   LogLevel QUIET
   IdentityFile ~/.ssh/id_rsa2
   PreferredAuthentication publickey
   RequestTTY yes
```
I have not made any changes to /etc/ssh/ssh_config
I have seen another issue but it states the problem was solved in  6.0.7

**Comment by Jasonpoh** [comment]
I have this issue as well.

**Comment by MisterTea** [comment]
The port in ssh config is your ssh port, not your et port. The error you are getting is that it can't reach the et server. To fix that, you need to specify the et port on the command line.

**Comment by bejavu** [comment]
I there a way to set this port in a config file so I won't have to type it to the terminal each time?
