### ISSUE TITLE
Install from source doesn't create /etc/systemd/system/et.service on Ubuntu?

### ISSUE THREAD

**Issue by dandv** [MisterTea/EternalTerminal#308]
I've followed the instructions to install from source on Ubuntu, up to and including the `sudo cp ../etc/et.cfg /etc/`, but `/etc/systemd/system/et.service` was not created. This looks like a regression, because it's worked before, and after adding the proper contents to that file from an older machine I had `etserver` running on, I could run the service:

```
[Unit]
Description=Eternal Terminal
After=syslog.target network.target

[Service]
Type=forking
PIDFile=/var/run/etserver.pid
ExecStart=/usr/local/bin/etserver --daemon --cfgfile=/etc/et.cfg

[Install]
WantedBy=multi-user.target
```

**Comment by MisterTea** [comment]
There is an et.service file in the repo. Does it match what you posted?

**Comment by cameronsstone** [comment]
I just git cloned, and found `systemctl/et.service`, which seems to match:
```
[Unit]
Description=Eternal Terminal
After=syslog.target network.target

[Service]
Type=forking
PIDFile=/var/run/etserver.pid
ExecStart=/usr/bin/etserver --daemon --cfgfile=/etc/et.cfg

[Install]
WantedBy=multi-user.target
```

**Comment by dandv** [comment]
I no longer have current details to confirm/deny this, so closing for now. Thanks!

**Comment by FFdhorkin** [comment]
I ran into this on an Amazon Linux build, so I think this is still an issue
