### ISSUE TITLE
error while loading shared libraries: libprotobuf-lite.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dandv** [MisterTea/EternalTerminal#311]
I've scp'ed `et` from a server onto a new client machine (Ubuntu 20) without `et`, then I followed the instructions in the README,

> Once built, the binary only requires libgflags-dev and libprotobuf-dev.

and ran `sudo apt install libgflags-dev libprotobuf-dev` successfully. But when I run `et`, I still get this error:

```sh
$ ./et
./et: error while loading shared libraries: libprotobuf-lite.so.10: cannot open shared object file: No such file or directory
```

**Comment by MisterTea** [comment]
The problem with scp-ing binaries around is that you are assuming the exact same versions of shared libraries are on the destination machine.

You should instead install et using the package manager of the new machine, or build it from source.

**Comment by dandv** [comment]
The problem with building the source has been that I have one version on a the server built a few weeks ago, then I build one on the client, and [they're not compatible](https://github.com/MisterTea/EternalTerminal/issues/211#issuecomment-520683892).

Installing from the PPA worked though.

Speaking of that, I wanted to make a small PR for the Using section of [the Tutorial](https://eternalterminal.dev/usermanual/). Does it have a repo somewhere? The suggestion was to add a line, "If you don't want the `et` daemon running on the client, run `systemctl disable et`. I think that's a very common setup.

**Comment by MisterTea** [comment]
It's in the gh-pages branch of this repo

**Comment by MisterTea** [comment]
We are using vcpkg manifests now so this shouldn't be an issue

**Comment by dandv** [comment]
@MisterTea not familiar with those and looking up [vcpkg manifests](https://vcpkg.readthedocs.io/en/latest/specifications/manifests/) wasn't that illuminating :) What is the implication for the end user?

**Comment by MisterTea** [comment]
If you run cmake with the vcpkg toolchain using the latest code, it will automatically download and build the dependencies.

**Comment by MisterTea** [comment]
https://github.com/MisterTea/EternalTerminal/blob/master/.github/workflows/vcpkg_build.yml
