### ISSUE TITLE
Connection terminates on first character sent (after connection established)

### ISSUE THREAD

**Issue by cameronsstone** [MisterTea/EternalTerminal#314]
I installed ET on client and server, and after verifying I could ssh from the client to the server, I tried firing up the `etserver` on the server and connecting with `et`. The connection gets established successfully, but as soon as I enter a keystroke the connection drops. Neither client nor server seems to crash, but there's an error from the raw socket library. See the attached tarballs for the logs.

Server:
1. Platform is [AL2](https://aws.amazon.com/amazon-linux-2/)
1. Installed from git, basically following the [Ubuntu instructions](https://github.com/MisterTea/EternalTerminal#ubuntu)
1. `etserver --version` yields `et version 6.0.7`

Client:
1. Platform is Macos Catalina (10.15.4)
1. Installed with `brew install MisterTea/et/et`
1. `et --version` yields `et version 6.0.7`

[etclientLogs.tar.gz](https://github.com/MisterTea/EternalTerminal/files/4665542/etclientLogs.tar.gz)
[etserverLogs.tar.gz](https://github.com/MisterTea/EternalTerminal/files/4665543/etserverLogs.tar.gz)

**Comment by cameronsstone** [comment]
FYI: checking out the et-v6.0.7 tag and building that makes the problem go away.

**Comment by MisterTea** [comment]
Thanks for reporting!
