### ISSUE TITLE
Ubuntu: Connection dies on first character input

### ISSUE THREAD

**Issue by d-e-e-p** [MisterTea/EternalTerminal#323]
when it works, et is great -- especially with my iterm/mac client. unfortunately i can't get it working on a few machines.  GDB session with -v 9 attached.

lsb_release -a

> Distributor ID: Ubuntu
> Description:    Ubuntu 18.04.4 LTS
> Release:    18.04
> Codename:   bionic

 sudo gdb ./etserver
(gdb) run  --port 9998 --logtostdout -v 9

[temp.log](https://github.com/MisterTea/EternalTerminal/files/4778211/temp.log)

**Comment by d-e-e-p** [comment]
still crash after d15bb72 :
[temp2.log](https://github.com/MisterTea/EternalTerminal/files/4782416/temp2.log)

**Comment by MisterTea** [comment]
Did you update the server to latest master and reinstall?

**Comment by d-e-e-p** [comment]
yes, etserver was built after pulling the commit below. see temp2.log...thanks.

> commit d15bb726d987bd147480125d694de44a2ea6ce83 (HEAD -> master, origin/master, origin/HEAD)
> Author: Jason Gauci <jgmath2000@gmail.com>
> Date:   Mon Jun 15 08:33:03 2020 -0700
> 
>     Revert back to write/read instead of send/recv on unix.  Fixes #323 #322 #314
>

**Comment by MisterTea** [comment]
What about et and etterminal?  Are they new?

**Comment by d-e-e-p** [comment]
oops no. 
unfortunately running with updated et gives the same result.  on the different machine config we get a crash and on the same machine (et localhost) we get 'Session terminated' . 
both server and client are current in these 2 log files:

[diff_machine.log](https://github.com/MisterTea/EternalTerminal/files/4794541/diff_machine.log)
[same_machine.log](https://github.com/MisterTea/EternalTerminal/files/4794543/same_machine.log)

**Comment by MisterTea** [comment]
Can you try using the official builds instead of building from source?

**Comment by d-e-e-p** [comment]
unfortunately same results...

>     sudo add-apt-repository ppa:jgmath2000/et
>     sudo apt-get update
>     sudo apt-get install et


[different_machine.log](https://github.com/MisterTea/EternalTerminal/files/4796853/different_machine.log)
[same_machine.log](https://github.com/MisterTea/EternalTerminal/files/4796854/same_machine.log)

**Comment by MisterTea** [comment]
Et localhost on Ubuntu definitely works: it's our integration test.

Check to see if you have two copies of et installed at once?
