### ISSUE TITLE
trying to get it work on termux

### ISSUE THREAD

**Issue by mirsella** [MisterTea/EternalTerminal#327]
hello

i wanted to use eternalterminal on termux, but it isn't in the repo. so I tried building it from source. cmake is finishing fine, but make throw a error because execinfo.h is missing. execinfo.h is not in the bionic libc used on termux.
log for make : https://pastebin.com/rgaXdn73

I tried to copy execinfo.h from my PC to termux but didn't work, it found execinfo.h but other errors appear. 
log : https://pastebin.com/qNFFhp9h

I'm trying to tweak ust.hpp to remove execinfo.h but I don't think I'll succeed.
i don't know what you can do to fix it. I've created this issue to say we can't use EternalTerminal on termux. 
thanks

**Comment by mirsella** [comment]
I succeeded in building with make.
I had to comment in everything related to execinfo.h in `external/UniversalStacktrace/ust/ust.hpp` since the bionic libc version termux use doesn't have execinfo.h : 
line 9 : `#include <execinfo.h>`
line 313 : `numFrames = backtrace(stack, MAX_STACK_FRAMES);`
line 317 : `char **strings = backtrace_symbols(stack, numFrames);`
line 323 : `const std::string line(strings[a]);`
line 371 : `free(strings);`

after this the other error is about the option '-lrevolv' for aarch64-linux-android-ld is not supported, I found that removing it from all the link.txt file is working, so I executed this command to  remove them : `fd link.txt -x sed -i 's/-lresolv//g' {}`
the build is passing.

**Comment by mirsella** [comment]
when launching `etserver --logtostdout -v 1` i got : https://pastebin.com/ydK50mqG
`addr2line: '/data/data/com.termux/files/home/5bdddbe000-5bdddc0000': No such file` this i the cause of the crash ? or it's because of the gibrish that is the stack trace of PipeSocketHandler.cpp ?

also without '--logtostdout' option when I launch `etserver` it crash with a error message `invalid file name /tmp/etserver_stderr_$(date)` probably because he can't access /tmp on android without root. maybe add a new option to set the location of the logs files ?

**Comment by MisterTea** [comment]
You need to run etserver as root

**Comment by mirsella** [comment]
actually i've just discovered there no /tmp on android. I'll try to create a folder myself, and `ln -s` it to termux files so it doesn't require root.
I'll post the output anyway
`etserver`with `su` : https://pastebin.com/inpcnPz2

**Comment by mirsella** [comment]
maybe if you have a rooted device you can tell me if you can create a /tmp folder ?

**Comment by MisterTea** [comment]
Why run etserver on android?  Don't you only need the client?

**Comment by mirsella** [comment]
yep, I wanted to use it primarily as a client but also a server sometime. i don't know why i didn't even retried as a client.
but it still don't work, with `su`, `sudo su` and `sudo` : https://pastebin.com/1cqcUpEa
the IP is good, i can ping each machine. also in the log of the server there no new message when i try to connect on termux.

**Comment by mirsella** [comment]
i'll try `termux-chroot` tomorrow.

**Comment by mirsella** [comment]
not really working haha. the closest i got is `sudo termux-chroot` but when i use `et mirsella@192.168.1.166` give me `Could not reach the ET server: 192.168.1.166:2022` but i can ping the machine from my phone, and connect with the same `et` command from my PC and it work. i don't know what could make it fail to connect to the `et` server.

**Comment by MisterTea** [comment]
What happens when you try to et to localhost on that machine?

**Comment by mirsella** [comment]
sorry for the late response.
I can `et` into the server from my pc, and in the server i can `et localhost` too. it's only when i try from termux that it don't work.
still getting  `Could not reach the ET server: 192.168.1.166:2022` i can ssh and ping the machine from termux too.

i re tried with different method and still getting `Could not reach the ET server: 192.168.1.166:2022` but not with termux-chroot, which have another error : 
termux-chroot and sudo termux-chroot : ```CANNOT LINK EXECUTABLE "sh": library "/data/data/com.termux/files/usr/lib/libtermux-exec.so" needed or dlopened by "/system/bin/sh" is not accessible for the namespace "(default)"```

with the `Could not reach the ET server: 192.168.1.166:2022` the line up there is `Error getting address info for 192.168.1.166:2022: 3 (Invalid value for ai_flags)` seems like it can be the problem ? what is ai_flags ? maybe a problem in the compilation ?

another question not related, ET doesn't support for now keybind to close a connection ? because when i poweroff my server from ET it just hang, and i can't quit ET. i have to close the console, ctrl+c doesn't work. on ssh it exit automatically but most importantly there the keybind `<C-R>~.` which quit the connection.

thanks

**Comment by buttaface** [comment]
I got the client built and running on Termux with the patch in the pull linked above, but it doesn't seem to connect to the server when I run it like `et user@10.0.0.1`, with a real username and IP. Is sshd supposed to be running on the server too or does etserver have its own ssh implementation?

This is my first time trying `et`, so I'm unsure how it's supposed to work. I built etserver on the server and ran it from my home directory, but when I tried to connect to it directly from the server with `et localhost` that too failed with an error in `readAll`, whether I ran the server as root or not. At least that connected to the server, unlike the Termux client from a different IP.

I probably didn't configure something right, so if you regular users want to try it out, go to the above Termux pull, click on `Checks`, then `Artifacts` on the right, then `termux-packages` to download the built Termux packages. Unpack them and then install the right one with `dpkg -i eternal-terminal_6.0.13_aarch64.deb`.

I'll submit that patch here once we get it all working.

**Comment by MisterTea** [comment]
Et has its own server so you need sshd and etserver running

**Comment by laurentlbm** [comment]
I tried the package by @buttaface and got an error also. `etserver` and `sshd` are running, I can connect to the server with both `ssh` and `mosh`.

`Could not reach the ET server: 192.168.0.101:2022`

**Comment by buttaface** [comment]
Should work now:
```
pkg install et
etserver --daemon --cfgfile=$PREFIX/etc/et.cfg
# Add Port 8022 to .ssh/config and start sshd
et localhost
```
Let me know if something broke, other than `etserver --help`.

**Comment by mirsella** [comment]
working for me, thanks for the work, even on the termux repo.

b3512b6 fixed it ? can you briefly explain what was the technical problem ? thanks

**Comment by buttaface** [comment]
No, see my full pull #374, including the comments.

**Comment by laurentlbm** [comment]
It works well as client to connect, but when I test connection issues (turn wifi off and on), the session is terminated with an error at the moment wifi is turned off.

Last lines of the logs:
```
[V4 2021-01-04 14:55:12,642 client-main TerminalClient.cpp:303] Clientfd is selected
[V4 2021-01-04 14:55:12,643 client-main UnixSocketHandler.cpp:23] socket 6 has data
[V4 2021-01-04 14:55:12,643 client-main TerminalClient.cpp:305] connection has data
[V4 2021-01-04 14:55:12,643 client-main Connection.cpp:151] Before read get connectionMutex
[V4 2021-01-04 14:55:12,643 client-main Connection.cpp:153] After read get connectionMutex
[V4 2021-01-04 14:55:12,643 client-main UnixSocketHandler.cpp:23] socket 6 has data
[V4 2021-01-04 14:55:12,643 client-main UnixSocketHandler.cpp:45] Unixsocket handler read from fd: 6
[ERROR 2021-01-04 14:55:12,643 client-main UnixSocketHandler.cpp:53] No Stack Trace on Android
Error reading: 103 Software caused connection abort
[ERROR 2021-01-04 14:55:12,643 client-main Connection.cpp:165] No Stack Trace on Android
Got a serious error trying to read: 103 / Software caused connection abort
[ERROR 2021-01-04 14:55:12,645 client-main TerminalClient.cpp:396] No Stack Trace on Android
Error: Failed a call to read
Connection closing because of error: Failed a call to read

Session terminated

[INFO 2021-01-04 14:55:12,646 client-main Connection.cpp:145] Shutting down connection
[V1 2021-01-04 14:55:12,646 client-main UnixSocketHandler.cpp:165] Closing connection: 6
[V1 2021-01-04 14:55:12,646 client-main Connection.cpp:93] Closed socket
[INFO 2021-01-04 14:55:12,646 client-main Connection.cpp:78] Tried to close a dead socket
```

**Comment by buttaface** [comment]
Is that not what's supposed to happen? I figured `et` was just supposed to keep everything running when I reconnected, which I tested and that worked.

**Comment by laurentlbm** [comment]
The problem is that when I reconnect, a new session is started.

Server logs: https://pastebin.com/bHw6Uh4e
