### ISSUE TITLE
Connecting to ET sessions after client goes away

### ISSUE THREAD

**Issue by wojciechwasko** [MisterTea/EternalTerminal#332]
I'm on ET 6.0.7; client is a laptop running Windows 10 WSL/Ubuntu 18.04.4, server is on Ubuntu 18.04.4

In my workflow, I connect to multiple remote servers from my client - often establishing multiple sessions to the same server - which works quite well. However, if I reboot my laptop, I can see that all the remote sessions are still present on the server but I can't connect to them. I can establish _new_ ET sessions without any issue, but old sessions still linger in the background. Here's what the server looks like in that state:
```
$ who
wwasko   pts/0        2020-06-22 14:24 (et [24316])
wwasko   pts/1        2020-06-22 09:22 (et [12431])
wwasko   pts/2        2020-06-22 09:22 (et [12526])
wwasko   pts/3        2020-06-22 09:32 (et [22418])
wwasko   pts/4        2020-06-23 09:29 (et [17417])
wwasko   pts/5        2020-06-23 10:10 (et [17564])
wwasko   pts/6        2020-06-23 13:40 (et [42390])
wwasko   pts/7        2020-06-25 12:30 (et [48297])
wwasko   pts/8        2020-06-26 07:57 (et [19854])
wwasko   pts/9        2020-06-23 14:27 (et [36329])
wwasko   pts/10       2020-06-26 08:01 (et [19974])
wwasko   pts/11       2020-06-24 15:58 (et [41644])
wwasko   pts/12       2020-06-25 09:36 (et [25682])
wwasko   pts/13       2020-06-25 09:38 (et [25858])
wwasko   pts/14       2020-06-25 09:46 (et [37213])
wwasko   pts/15       2020-07-14 10:11 (et [33703])
wwasko   pts/16       2020-07-14 10:48 (et [16081])
wwasko   pts/17       2020-07-15 18:01 (et [11935])
wwasko   pts/18       2020-07-16 10:00 (et [19612])
wwasko   pts/19       2020-07-14 15:38 (et [24781])
wwasko   pts/20       2020-07-15 08:47 (et [14403])
wwasko   pts/21       2020-07-16 12:06 (et [19777])
wwasko   pts/22       2020-07-16 13:30 (et [1426])
```
In reality, only the last two sessions are actually active sessions, all the previous ones are sessions which have been abandoned by the client due to reboot.

Is there a way in ET to connect to an "orphaned" session or at least kill all non-currently-active sessions?

**Comment by mountainjoe** [comment]
I also have this problem, almost certainly caused by my VPN disconnecting before my ET clients turn off.

**Comment by MisterTea** [comment]
You can use the -x command to kill previous sessions, or you can kill them manually.

**Comment by wojciechwasko** [comment]
Thanks, that's useful. Is there some way to reconnect to the old sessions, though?

**Comment by MisterTea** [comment]
@wojciechwasko No, there isn't a persistent state on the client side to do this.

Once Hyper.js 3.1.0 comes out, you can use hyper-htm to control many tabs from a single et connection and this should simplify your workflow
