### ISSUE TITLE
Force quit

### ISSUE THREAD

**Issue by theicfire** [MisterTea/EternalTerminal#340]
If my server turns off, is there a way to force quit Eternal Terminal? I can do this in ssh with ~. (tilde, dot). In Eternal Terminal, the only way I know how to quit is closing the terminal window.

Not a big deal if not, it just wasn't clear to me if this was possible or not. Looks like right clicking in MacOS Iterm -> "Restart" also works for me.

**Comment by MisterTea** [comment]
Oh, I just pkill et.exe in another terminal. 

This should be an easy change if someone wants to add that functionality. You just need to intercept keystrokes as they go across the wire and look for ~.

**Comment by theicfire** [comment]
Got it, thanks! I'll close the issue and hopefully search engines will index it for posterity

**Comment by bozlo** [comment]
so there is no nicely quit way rather than kill?
