### ISSUE TITLE
Support external libexecinfo in CMakeLists.txt

### ISSUE THREAD

**Issue by ahesford** [MisterTea/EternalTerminal#347]
The `CMakeLists.txt` defines `CORE_LIBRARIES` to include `libexecinfo` as an external library on FreeBSD and NetBSD. For Linux systems with the musl C library, `libexecinfo` is required as well. Please add support for appending `execinfo` to `CORE_LIBRARIES` in a more general way to support musl in addition to the BSDs.

This should be as simple as adding a cmake variable that can be defined at configuration time to toggle this behavior.

**Comment by MisterTea** [comment]
Please submit a PR with the change
