### ISSUE TITLE
ssh_config: support multiple Include

### ISSUE THREAD

**Issue by SuperSandro2000** [MisterTea/EternalTerminal#348]
The ssh_config parser does not support multiple Include commands. It just stops after the first one and ignores all following. This works with openssh-client so it should obviously also work with et.

**Comment by MisterTea** [comment]
Please submit a PR with the change

**Comment by SuperSandro2000** [comment]
I have no prior experience in C++ otherwise I would have done that already.

**Comment by MisterTea** [comment]
@SuperSandro2000 I learned c++ by submitting changes to an open source project. So can you!

**Comment by SuperSandro2000** [comment]
> @SuperSandro2000 I learned c++ by submitting changes to an open source project. So can you!

Take a look at my contributions on my GitHub profile. There are only 24 hours in a day and I do not have time to learn c++.

**Comment by mcybz** [comment]
I can confirm. It does not work with mutiple includes, only on the first one.
