### ISSUE TITLE
Error: (98): Address already in use

### ISSUE THREAD

**Issue by ChanganVR** [MisterTea/EternalTerminal#351]
Hi there,

Thanks for your tool and I found it very useful! I'm recently trying to use it on a cluster where I don't have sudo. I compliled the library and ran "./build/etserver  --port 8008 --logtostdout", which gave the following output.

[INFO 2020-09-18 21:15:23,032 etserver-main TerminalServerMain.cpp:145] In child, about to start server.
[INFO 2020-09-18 21:15:23,033 etserver-main TcpSocketHandler.cpp:215] Listening on 0.0.0.0:8008/2/1/6
[INFO 2020-09-18 21:15:23,033 etserver-main TcpSocketHandler.cpp:215] Listening on 0.0.0.0:8008/10/1/6
[FATAL 2020-09-18 21:15:23,158 etserver-main PipeSocketHandler.cpp:98] Stack Trace:
[0] 0x2b15b7 et::PipeSocketHandler::listen(et::SocketEndpoint const&)
[1] 0x23cdce et::UserTerminalRouter::UserTerminalRouter(std::shared_ptr<et::PipeSocketHandler>, et::SocketEndpoint const&)
[2] 0x22e629 et::TerminalServer::TerminalServer(std::shared_ptr<et::SocketHandler>, et::SocketEndpoint const&, std::shared_ptr<et::PipeSocketHandler>, et::SocketEndpoint const&) (TerminalServer.cpp:14)
[3] 0x1d4082 main (TerminalServerMain.cpp:152)
[4] 0x7eff8a343b97 __libc_start_main
[5] 0x1d100a _start
Error: (98): Address already in use
[WARNING 2020-09-18 21:15:23,158 etserver-main PipeSocketHandler.cpp:98] Aborting application. Reason: Fatal log at [/u/changan/Software/EternalTerminal/src/base/PipeSocketHandler.cpp:98]
Aborted (core dumped)

I have checked the port and it's not occupied by other applications. I tried other ports as well and got the same results. Is this output expected for users without sudo? And is it possible for me to run it without sudo? 

Thanks!

**Comment by MisterTea** [comment]
It means you don't have write access to the unix socket (maybe you ran et as root before?).

**Comment by ChanganVR** [comment]
I asked the school IT for help. They might have run this as root for testing but they ended up refusing to keep running this service as root for the cluster. How does it influence my use of ET? Is it possible in general for users without sudo to run this on linux?

**Comment by MisterTea** [comment]
If they ran it once at root, it created the /tmp/et.sock file as root. You
have to delete this file as root then run it again as a normal user

**Comment by ChanganVR** [comment]
There isn't this file under /tmp directory. But there is a file called etserver.idpasskey.fifo. Could that be the issue?

**Comment by MisterTea** [comment]
That's the file.  Thanks for the correction.

**Comment by ChanganVR** [comment]
This works! Thanks. Closing this issue now.
