### ISSUE TITLE
etserver fails to open session on Ubuntu

### ISSUE THREAD

**Issue by wjshamblin** [MisterTea/EternalTerminal#352]
Trying to get etserver going on Ubuntu either 18.04 or 16.04 results in:

Error starting ET process through ssh, please make sure your ssh works first

Ssh is fully functional, but etserver fails on

[V4 2020-09-25 08:06:28,347 server-clientHandler UnixSocketHandler.cpp:23] socket 8 has data
[V4 2020-09-25 08:06:28,347 server-clientHandler UnixSocketHandler.cpp:45] Unixsocket handler read from fd: 8
[V1 2020-09-25 08:06:28,348 server-clientHandler SocketHandler.cpp:32] Failed a call to readAll: Broken pipe
[WARNING 2020-09-25 08:06:28,348 server-clientHandler ServerConnection.cpp:118] Error handling new client: Failed a call to readAll
[V1 2020-09-25 08:06:28,348 server-clientHandler UnixSocketHandler.cpp:165] Closing connection: 8

I am including the logs, and an strace of the process as it executes in case that helps. The server is running as root, so permissions should not be an issue. Here are the logs from syslog:

Sep 25 08:06:35 redacted sshd[21671]: pam_sss(sshd:auth): authentication success; logname= uid=0 euid=0 tty=ssh ruser= rhost=INTERNAL_IP_ADDRESS user=unix_username
Sep 25 08:06:42 redacted sshd[21671]: Successful Duo login for 'unix_username' from INTERNAL_IP_ADDRESS
Sep 25 08:06:42 redacted sshd[21669]: Accepted keyboard-interactive/pam for unix_username from INTERNAL_IP_ADDRESS port 58578 ssh2
Sep 25 08:06:42 redacted sshd[21669]: pam_unix(sshd:session): session opened for user unix_username by (uid=0)
Sep 25 08:06:42 redacted systemd-logind[14124]: New session 8535 of user unix_username.
Sep 25 08:06:42 redacted systemd[1]: Started Session 8535 of user unix_username.
Sep 25 08:06:42 redacted systemd[1]: Started Session 8535 of user unix_username.
Sep 25 08:06:42 redacted sshd[21755]: Received disconnect from INTERNAL_IP_ADDRESS port 58578:11: disconnected by user
Sep 25 08:06:42 redacted sshd[21755]: Disconnected from user unix_username INTERNAL_IP_ADDRESS port 58578
Sep 25 08:06:42 redacted sshd[21669]: pam_unix(sshd:session): session closed for user unix_username
Sep 25 08:06:42 redacted systemd-logind[14124]: Removed session 8535.

I noticed several issues very similar to this, so hopefully this will help narrow it down. It produces the same results running as a regular user.
[et.zip](https://github.com/MisterTea/EternalTerminal/files/5282923/et.zip)

Thanks!

Joe

**Comment by MisterTea** [comment]
@wjshamblin can you try with the latest version (6.0.13)?

**Comment by wjshamblin** [comment]
That does indeed seem to resolve the issue. Thanks!
