### ISSUE TITLE
Lingering etterminal processes and lots of log files in /tmp

### ISSUE THREAD

**Issue by valankar** [MisterTea/EternalTerminal#354]
I have been noticing lingering etterminal processes piling up on my Ubuntu server. I am using et on WSL (Ubuntu) in Windows 10 and it seems specific to this connection method when closing the WSL terminal window.

If I connect with `et host` and then exit the shell normally, the etterminal process goes away. However, if I connect and then close the WSL window without exiting the shell, the etterminal process lingers on.

Client version:

```
valankar@LAPTOP-LFLC973U:~$ et --version
et version 6.0.11
```

Server version:

```
valankar@v-1:~$ etserver --version
et version 6.0.11
```

2nd connection and closing window:

```
valankar@v-1:~$ ps -ef |grep termin
valankar 23274     1  1 09:05 ?        00:00:13 etterminal --verbose=0
valankar 23626     1  0 09:16 ?        00:00:00 etterminal --verbose=0
```

3rd connection and closing window:

```
valankar@v-1:~$ ps -ef |grep termin
valankar 23274     1  1 09:05 ?        00:00:17 etterminal --verbose=0
valankar 23626     1  0 09:16 ?        00:00:00 etterminal --verbose=0
valankar 23739     1  0 09:20 ?        00:00:00 etterminal --verbose=0
```

This does not happen in MacOS, for example when I close the window without exiting the shell.

This also ends up with lots of log files in /tmp (attached).

I see there is a `-x` argument to kill old sessions, but is this required in my case? It is strange that WSL needs it but not MacOS.

**Comment by valankar** [comment]
[etlogs.tar.gz](https://github.com/MisterTea/EternalTerminal/files/5369655/etlogs.tar.gz)

**Comment by MisterTea** [comment]
This is the correct behavior.  You can kill the etterminal processes that you didn't exit properly using pskill or by passing the "-x" switch that automatically kills previous etterminal processes from the same user.
