### ISSUE TITLE
et error after connecting to server

### ISSUE THREAD

**Issue by RonanMacF** [MisterTea/EternalTerminal#357]
Port 2022 is not usable on the server so I am trying to connect using different ports. I have confirmed that et is installed on both the client and server and is visible in PATH. I have paswordless login setup on the server also. I have identified open listening ports using `netstat -tnlp` and can see the following
```
tcp        0      0 0.0.0.0:5914            0.0.0.0:*               LISTEN      -
tcp6       0      0 :::6014                 :::*                    LISTEN      -
```

When I try to connect to the server using either one of these ports I get the following.
```
[INFO 2020-10-31 16:49:14,306 client-main ParseConfigFile.hpp:1378] /Users/ronan/.ssh/confignot found
[INFO 2020-10-31 16:49:14,307 client-main ParseConfigFile.hpp:1353] unsupported config line: 	SendEnv LANG LC_*
, ignored
[INFO 2020-10-31 16:49:14,307 client-main TerminalClientMain.cpp:172] Parsed ssh config file, connecting to hostname
[INFO 2020-10-31 16:49:14,494 client-main TcpSocketHandler.cpp:88] Connected to server: hostname using fd 6
zsh:2: command not found: etterminal
Error starting ET process through ssh, please make sure your ssh works first
```

I confirmed ssh is working on the server and it looks like the connection suceeded.

**Comment by MisterTea** [comment]
"zsh:2: command not found: etterminal"

That's the issue.  the etterminal command is not in /usr/bin .  Updates to the path in bashrc will not work because the etterminal command runs before that.

**Comment by RonanMacF** [comment]
> "zsh:2: command not found: etterminal"
> 
> That's the issue. the etterminal command is not in /usr/bin . Updates to the path in zshrc will not work because the etterminal command runs before that.

appreciate it.
```
$ whereis et
et: /usr/bin/et /usr/include/et /usr/share/et /nix/store/yyaq9iy2v6sbsm5631s1n70zp0a9m5l1-user-environment/bin/et
```

then trying to connect again using `et ronan@host -p xx -v 9 --logtostdout` where xxx is the mix of the open ports found in the original message.
```
[INFO 2020-11-05 19:46:05,795 client-main TerminalClientMain.cpp:172] Parsed ssh config file, connecting to host
[V1 2020-11-05 19:46:05,795 client-main TerminalClientMain.cpp:11] Connecting
[V4 2020-11-05 19:46:05,980 client-main TcpSocketHandler.cpp:75] Before selecting sockFd
[V4 2020-11-05 19:46:05,980 client-main TcpSocketHandler.cpp:79] sockFd 6is selected6
[INFO 2020-11-05 19:46:05,980 client-main TcpSocketHandler.cpp:88] Connected to server: host using fd 6
[V1 2020-11-05 19:46:05,980 client-main UnixSocketHandler.cpp:165] Closing connection: 6
zsh:2: command not found: etterminal
Error starting ET process through ssh, please make sure your ssh works first
```

**Comment by MisterTea** [comment]
Can you do a "whereis etterminal" ?

**Comment by RonanMacF** [comment]
Yep sure, `etterminal: /usr/bin/etterminal /nix/store/yyaq9iy2v6sbsm5631s1n70zp0a9m5l1-user-environment/bin/etterminal`

**Comment by RonanMacF** [comment]
Would have thought the output should be the same but `which -a etterminal` gives
```
~/.nix-profile/bin/etterminal
~/.nix-profile/bin/etterminal
~/.nix-profile/bin/etterminal
/bin/etterminal
/usr/bin/etterminal
```

**Comment by MisterTea** [comment]
Is there some permissions issue with etterminal?

**Comment by rarefree** [comment]
> Is there some permissions issue with etterminal?

I have the same issue. I installed with brew and etterminal is in /usr/local/bin

There is no permission issue. I can execute etterminal fine.

**Comment by RonanMacF** [comment]
> > Is there some permissions issue with etterminal?
> 
> I have the same issue. I installed with brew and etterminal is in /usr/local/bin
> 
> There is no permission issue. I can execute etterminal fine.

Are you OSX->OSX? FYI I couldn't figure out the issue and ended up going back to mosh. Will try attempt it again and see if I can get it working.

**Comment by rarefree** [comment]
> Are you OSX->OSX? FYI I couldn't figure out the issue and ended up going back to mosh. Will try attempt it again and see if I can get it working.

Nope, OSX->Linux etserver

**Comment by RonanMacF** [comment]
Ok so I think your "I installed with brew" is irrelevant here. There is an issue with the et on the Linux server, same situation I had :( Hopefully we can figure out a solution

**Comment by rarefree** [comment]
> Ok so I think your "I installed with brew" is irrelevant here. There is an issue with the et on the Linux server, same situation I had :( Hopefully we can figure out a solution

I'm getting the error on the client side with etterminal as you did. I don't see any errors in etserver with verbose running.

**Comment by jshort** [comment]
@RonanMacF Can you run with the `--terminal-path` option to explicitly give the path to the `etterminal` binary you want to use on the server (and confirm your user can execute the file on the server).  Previously if you are on an older `et` binary, the option was `--prefix` but it expects a full path to the binary.

@rarefree Can you run with the `--macserver` option (or use `--terminal-path` directly if the path is different):

("macserver",
 78          "Set when connecting to an macOS server.  Sets "
 79          "--terminal-path=/usr/local/bin/etterminal")
