### ISSUE TITLE
-c option not honoured

### ISSUE THREAD

**Issue by elthariel** [MisterTea/EternalTerminal#358]
Hi,

I'm using et version 6.0.11 on both the client and server. Connection and re-connection works perfectly fine (:love_letter:)

But the `-c` option does not work as expected.

When i run `et example.com -c "/bin/ls"`, instead of executing the command remotely, it just displays it and starts a login shell.

```shellsession
local > et example.com -c "/bin/ls"
/bin/ls; exit
server >
```

I haven't included the logs because they're empty on the client and doesn't show anything relevant on the server

**Comment by elthariel** [comment]
Hum... This is embarassing. There was a tricky bug with my prompt which broke this.
Sorry

**Comment by kurktchiev** [comment]
so i am using -c as well and similar behavior happens now.

is there a way to keep ET from appending `exit`?
