### ISSUE TITLE
Compiling on darwin/arm64 (brew on Apple Silicon)

### ISSUE THREAD

**Issue by uwe-schwarz** [MisterTea/EternalTerminal#362]
Trying to install via `brew install MisterTea/et/et`

> ==> Installing et from mistertea/et
> ==> Downloading https://github.com/MisterTea/EternalTerminal/archive/et-v6.0.11.tar.gz
> Already downloaded: /Users/uwe/Library/Caches/Homebrew/downloads/b29cbb6915631be9cb6937bf03efb4fc6e03e669948706285736a9910458faaa--EternalTerminal-et-v6.0.11.tar.gz
> ==> cmake .
> ==> make -j4 install
> Last 15 lines from /Users/uwe/Library/Logs/Homebrew/et/02.make:
>             CATCH_BREAK_INTO_DEBUGGER();
>             ^
> /tmp/et-20201118-47361-iubr46/EternalTerminal-et-v6.0.11/external_imported/Catch2/single_include/catch2/catch.hpp:5485:75: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
>     #define CATCH_BREAK_INTO_DEBUGGER() if( Catch::isDebuggerActive() ) { CATCH_TRAP(); }
>                                                                           ^
> /tmp/et-20201118-47361-iubr46/EternalTerminal-et-v6.0.11/external_imported/Catch2/single_include/catch2/catch.hpp:5464:34: note: expanded from macro 'CATCH_TRAP'
>     #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
>                                  ^
> <inline asm>:1:6: note: instantiated into assembly here
>         int $3
>             ^
> 2 errors generated.
> make[2]: *** [CMakeFiles/et-test.dir/test/Main.cpp.o] Error 1
> make[1]: *** [CMakeFiles/et-test.dir/all] Error 2
> make: *** [all] Error 2

Is there anything else I could try/provide?

**Comment by MisterTea** [comment]
Can you try grabbing the source, updating the catch submodule to latest master, and see if that compiles?

**Comment by MisterTea** [comment]
If that doesn't work, please file an issue with the catch2 team here https://github.com/catchorg/Catch2

**Comment by uwe-schwarz** [comment]
Ok, tried it with Catch2 devel branch and the included `build_static.sh`:

> [ 86%] Building CXX object CMakeFiles/et-test.dir/test/ConnectionTest.cpp.o
> In file included from /Users/uwe/dev/EternalTerminal/test/CryptoHandlerTest.cpp:1:
> /Users/uwe/dev/EternalTerminal/test/TestHeaders.hpp:5:10: fatal error: 'catch2/catch.hpp' file not found
> #include "catch2/catch.hpp"
>          ^~~~~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [CMakeFiles/et-test.dir/test/CryptoHandlerTest.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> In file included from /Users/uwe/dev/EternalTerminal/test/BackedTest.cpp:7:
> /Users/uwe/dev/EternalTerminal/test/TestHeaders.hpp:5:10: fatal error: 'catch2/catch.hpp' file not found
> #include "catch2/catch.hpp"
>          ^~~~~~~~~~~~~~~~~~
> In file included from /Users/uwe/dev/EternalTerminal/test/ConnectionTest.cpp:7:
> /Users/uwe/dev/EternalTerminal/test/TestHeaders.hpp:5:10: fatal error: 'catch2/catch.hpp' file not found
> #include "catch2/catch.hpp"
>          ^~~~~~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [CMakeFiles/et-test.dir/test/BackedTest.cpp.o] Error 1
> 1 error generated.
> make[2]: *** [CMakeFiles/et-test.dir/test/ConnectionTest.cpp.o] Error 1
> make[1]: *** [CMakeFiles/et-test.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 88%] Linking CXX executable htmd
> [ 88%] Built target htmd
> [ 90%] Linking CXX executable htm
> [ 90%] Built target htm
> [ 91%] Linking CXX executable etterminal
> [ 93%] Linking CXX executable et
> [ 95%] Linking CXX executable etserver
> [ 95%] Built target etterminal
> [ 95%] Built target et
> [ 95%] Built target etserver
> make: *** [all] Error 2

This looks like some change which should happen in et, but I'm totally unfamiliar with Catch2 or what happens here.

**Comment by thalamus** [comment]
So I've resolved this - all that is needed is to update Catch2 to https://github.com/catchorg/Catch2/commit/ff349a50bfc6214b4081f4ca63c7de35e2162f60 then it compiles fine.

**Comment by kk7ds** [comment]
Looks like this was fixed after the latest release. Is there some way I can easily make brew build from master or something?

**Comment by trifle** [comment]
Sorry to poke a closed issue, but ET currently doesn't compile on M1/homebrew through the brew CLI.
Building from source/HEAD also failed with missing openssl - the mac release presumably includes some pre-populated paths?.
I've solved the issue by manually downloading the release tarball and swapping out Catch2.
Could it be that the release tarball was cut after this fix?

In any case, many thanks for your work on ET - it's a huge help to not worry about screen, killed ssh sessions, keepalives etc etc.!

**Comment by thalamus** [comment]
You're right, but it's a completely different issue, so you should have filed a new bug really.

`brew install mistertea/et/et --head` should (and did) work

I'll see if I can fix it.

**Comment by MisterTea** [comment]
Thanks!  latest master added openssl as a dependency.

**Comment by trifle** [comment]
Wow, thanks a lot @thalamus and @MisterTea for the hints and resolution.
I didn't think of brew install <formula> --head, good to know and remember! :)

**Comment by thalamus** [comment]
@MisterTea I've been testing --head builds regularly and I did test the build after e88afbfafaff6169fea1322ef07f36bc1d925527 that added openssl in as a dependency and it worked at the time without the dependency in the formula, which is why I thought it was probably a homebrew change which had caused it to suddenly become an issue.
