### ISSUE TITLE
I've recompiled ET for Alpine Linux again but had to disable something 

### ISSUE THREAD

**Issue by demyxco** [MisterTea/EternalTerminal#367]
Hello again! This isn't an issue but more of a question. I had to remove references to `UniversalStacktrace` in various files just to have it compile successfully again (I submitted a previous ticket over a year ago), due to backtrace errors. It compiled successfully and I was able to `et user@ip`. I'm assuming `UniversalStacktrace` is another logger for debugging purposes so omitting it should be fine?

**Comment by demyxco** [comment]
Sorry for the delay, here are the modifications I've made to make it "work." Been using it for a few days now, no issues that I can see.

https://github.com/demyxco/eternal-terminal/blob/491c622af250faf9cd4500931108d708540043de/Dockerfile#L57-L63

**Comment by MisterTea** [comment]
@demyxco I verified master works with alpine and still prints stack traces when there's a failure. You shouldn't need any changes now

**Comment by demyxco** [comment]
Awesome, thanks. Will check it out when I have more time.
