### ISSUE TITLE
/usr/bin/ld: cannot find -lunwind when installing from source

### ISSUE THREAD

**Issue by ericeb80** [MisterTea/EternalTerminal#369]
cmake ../ gives me this verbose can somebody help me please.

-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.8.0 loaded.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Found sodium: /usr/lib/x86_64-linux-gnu/libsodium.so  
-- Could NOT find UTempter (missing: UTEMPTER_INCLUDE_DIR UTEMPTER_LIBRARIES) 
-- CXX target et-lib cotired.
-- CXX target TerminalCommon cotired.
-- CXX target et cotired without precompiled header. Too few applicable sources.
-- CXX target etserver cotired without precompiled header. Too few applicable sources.
-- CXX target etterminal cotired without precompiled header. Too few applicable sources.
-- CXX target HtmCommon cotired.
-- CXX target htm cotired without precompiled header. Too few applicable sources.
-- CXX target htmd cotired without precompiled header. Too few applicable sources.
-- CXX target et-test cotired.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eric_eb/EternalTerminal/build
eric_eb@eric-pc:~/EternalTerminal/build$ make && sudo make install
Scanning dependencies of target generated-code
[  1%] Running cpp protocol buffer compiler on proto/ET.proto
[  3%] Running cpp protocol buffer compiler on proto/ETerminal.proto
[  3%] Built target generated-code
[  4%] Generating CXX prefix source cotire/TerminalCommon_CXX_prefix.cxx
[  4%] Generating CXX prefix header cotire/TerminalCommon_CXX_prefix.hxx
[  6%] Building CXX precompiled header cotire/TerminalCommon_CXX_prefix.hxx.gch
Scanning dependencies of target TerminalCommon
[  8%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/forwarding/PortForwardHandler.cpp.o
[  9%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/forwarding/ForwardSourceHandler.cpp.o
[  9%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/forwarding/ForwardDestinationHandler.cpp.o
[ 11%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/TerminalServer.cpp.o
[ 13%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/UserTerminalRouter.cpp.o
[ 14%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/TerminalClient.cpp.o
[ 14%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/SshSetupHandler.cpp.o
[ 16%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/UserTerminalHandler.cpp.o
[ 18%] Building CXX object CMakeFiles/TerminalCommon.dir/src/terminal/UserJumphostHandler.cpp.o
[ 19%] Building CXX object CMakeFiles/TerminalCommon.dir/ETerminal.pb.cc.o
[ 19%] Linking CXX static library libTerminalCommon.a
[ 21%] Built target TerminalCommon
[ 22%] Generating CXX prefix source cotire/et-lib_CXX_prefix.cxx
[ 22%] Generating CXX prefix header cotire/et-lib_CXX_prefix.hxx
[ 24%] Building CXX precompiled header cotire/et-lib_CXX_prefix.hxx.gch
Scanning dependencies of target et-lib
[ 26%] Building CXX object CMakeFiles/et-lib.dir/external/easyloggingpp/src/easylogging++.cc.o
[ 27%] Building CXX object CMakeFiles/et-lib.dir/src/base/BackedReader.cpp.o
[ 27%] Building CXX object CMakeFiles/et-lib.dir/src/base/BackedWriter.cpp.o
[ 29%] Building CXX object CMakeFiles/et-lib.dir/src/base/ClientConnection.cpp.o
[ 31%] Building CXX object CMakeFiles/et-lib.dir/src/base/Connection.cpp.o
[ 32%] Building CXX object CMakeFiles/et-lib.dir/src/base/CryptoHandler.cpp.o
[ 34%] Building CXX object CMakeFiles/et-lib.dir/src/base/ServerClientConnection.cpp.o
[ 34%] Building CXX object CMakeFiles/et-lib.dir/src/base/ServerConnection.cpp.o
[ 36%] Building CXX object CMakeFiles/et-lib.dir/src/base/SocketHandler.cpp.o
[ 37%] Building CXX object CMakeFiles/et-lib.dir/src/base/PipeSocketHandler.cpp.o
[ 39%] Building CXX object CMakeFiles/et-lib.dir/src/base/TcpSocketHandler.cpp.o
[ 39%] Building CXX object CMakeFiles/et-lib.dir/src/base/UnixSocketHandler.cpp.o
[ 40%] Building CXX object CMakeFiles/et-lib.dir/src/base/LogHandler.cpp.o
[ 42%] Building CXX object CMakeFiles/et-lib.dir/src/base/DaemonCreator.cpp.o
[ 44%] Building CXX object CMakeFiles/et-lib.dir/src/base/SystemUtils.cpp.o
[ 44%] Building CXX object CMakeFiles/et-lib.dir/src/base/RawSocketUtils.cpp.o
[ 45%] Building CXX object CMakeFiles/et-lib.dir/src/base/SubprocessToString.cpp.o
[ 47%] Building CXX object CMakeFiles/et-lib.dir/ET.pb.cc.o
[ 49%] Linking CXX static library libet-lib.a
[ 50%] Built target et-lib
[ 52%] Generating CXX prefix source cotire/et-test_CXX_prefix.cxx
[ 54%] Generating CXX prefix header cotire/et-test_CXX_prefix.hxx
[ 54%] Building CXX precompiled header cotire/et-test_CXX_prefix.hxx.gch
Scanning dependencies of target et-test
[ 55%] Building CXX object CMakeFiles/et-test.dir/test/BackedTest.cpp.o
[ 55%] Building CXX object CMakeFiles/et-test.dir/test/ConnectionTest.cpp.o
[ 57%] Building CXX object CMakeFiles/et-test.dir/test/CryptoHandlerTest.cpp.o
[ 59%] Building CXX object CMakeFiles/et-test.dir/test/JumphostTest.cpp.o
[ 60%] Building CXX object CMakeFiles/et-test.dir/test/TerminalTest.cpp.o
[ 60%] Building CXX object CMakeFiles/et-test.dir/test/Main.cpp.o
[ 62%] Linking CXX executable et-test
/usr/bin/ld: cannot find -lunwind
/usr/bin/ld: cannot find -lunwind
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/et-test.dir/build.make:185: et-test] Error 1
make[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/et-test.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by MisterTea** [comment]
You need libunwind. On ubuntu it's libunwind-dev

**Comment by ericeb80** [comment]
Thank you MisterTea. Cant wait to try this new tool.

**Comment by ericeb80** [comment]
> You need libunwind. On ubuntu it's libunwind-dev

Thank you MisterTea. Cant wait to try this new tool.

**Comment by ericeb80** [comment]
Ticket close.
