### ISSUE TITLE
Should "Restart=on-failure" be added to systemctl/et.service ?

### ISSUE THREAD

**Issue by koppchen** [MisterTea/EternalTerminal#376]
Hello,
 
With the current `et.service` file in the repo, and the 6.0.13 version in the debian package, if et fails for some reason when managed from systemd, it won't get restarted.  Would it make sense to add `Restart=on-failure` under the `[Service]` section?  That way the service is restarted by systemd automatically on failure, and a user doesn't need admin/sudo to start the service themselves.

So, instead of this:
```
[Service]
Type=simple
ExecStart=/usr/bin/etserver --cfgfile=/etc/et.cfg
```

We'd have this:
```
[Service]
Type=simple
Restart=on-failure
ExecStart=/usr/bin/etserver --cfgfile=/etc/et.cfg
```

note: systemd service `Restart=` is documented [here](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=)

Thank you,
-- Jim

**Comment by MisterTea** [comment]
Oh!  I didn't know about that.  Please submit a PR!!!!

**Comment by koppchen** [comment]
PR -> #377 

Thanks!

**Comment by koppchen** [comment]
oh, btw, this option was tested with `sudo kill -s SIGSEGV <et-pid>`, and using `journalctl -f -u et.service` & `systemctl status et.service` to verify it gets restarted.

**Comment by MisterTea** [comment]
Thanks so much!  Closing.
