### ISSUE TITLE
Ask client to confirm telemetry on launch

### ISSUE THREAD

**Issue by SuperSandro2000** [MisterTea/EternalTerminal#382]
Will there be an option to disable telemetry entirely?

**Comment by MisterTea** [comment]
There's a telemetry option in et.cfg to disable it server-side and there's the --telemetry option to disable it on the client.

**Comment by SuperSandro2000** [comment]
Did you think about disabling it by default? Especially in the open source community it is considered not nice and sometimes even rude to enable telemetry by default.

**Comment by MisterTea** [comment]
Can you elaborate on that?

I'm collecting crash logs using crashpad, and also collecting LOG(ERROR) and LOG(FATAL).  The only thing I'm using the logs for is to make ET better.

**Comment by SuperSandro2000** [comment]
You are sending the data to sentry which most likely collects personal data which probably requires a privacy policy. So far the readme does not contain any information about this and trying to hide such things looks always very suspicious even you just try to get more insights into crashes. If you would be open about it, would make it easy to disable and opt-in rather than opt-out it would be less of a problem for most people.

**Comment by MisterTea** [comment]
Sentry only collects the data I send it (and possibly the IP address of the sender)

**Comment by MisterTea** [comment]
@SuperSandro2000 Please take a look at #395 and give me your thoughts.
