### ISSUE TITLE
jumphost: could not reach the ET server 

### ISSUE THREAD

**Issue by ChanganVR** [MisterTea/EternalTerminal#386]
Hi there,

Thank you for the awesome software. I'm trying to connect to a server A (linux) via jumphost server B(linux) from my laptop (mac). I'm able to ssh to A via B or et A/B individually, but when I et A via B, it always fails and alerts "Could not reach the ET server: B:2022" (not additional information when specifying --verbose=9). The port 2022 is open on server B because I'm able to et to it. Do you have any idea why this happened? Appreciate your help!

Regards,
Changan

**Comment by MisterTea** [comment]
Can you et to A and then et to B within A?

**Comment by ishitamed19** [comment]
My default login shell is bash in server B. And in my bashrc, I was instantiating zsh shell, so that every time I log into my server B, it automatically starts a zsh shell. Hence, when I removed this line from my bashrc, the error got resolved.
