### ISSUE TITLE
Add option to enable disconnect notifications

### ISSUE THREAD

**Issue by MisterTea** [MisterTea/EternalTerminal#39]
ET used to notify people on disconnect but this was disabled since it caused issues with "tmux -CC".  This issue is to add that back as an option for people who do not use tmux control mode

**Comment by MisterTea** [comment]
I tried to revive https://github.com/MisterTea/EternalTCP/commit/118210cbe00dd4e2f860b6ca8a22ea7a3dac6043 but it doesn't work well in many cases.  Basically, this is very hard to do without a deep integration with a terminal emulator.  I could pass some escape sequence letting the terminal emulator know that there is a disconnect, but they would have to render something and handle removing it after we reconnect.

**Comment by MisterTea** [comment]
Actually maybe I can change the title of the window.  Let me look into that

**Comment by MisterTea** [comment]
Actually it's non-trivial to change the window title.  I tried setting PROMPT_COMMAND but that doesn't seem to be portable :-/

**Comment by krayon** [comment]
Perhaps you could do it for users of tmux at least, by manipulating the status bar(s)? In the event control mode allows for setting stuff like that, you could probably flash a colour or similar? Seems there's a fair bit of customisation available:
    https://leanpub.com/the-tao-of-tmux/read#status-bar

**Comment by MisterTea** [comment]
@krayon This is a great idea but I don't have time at the moment.  Would this be something that you would be interested in submitting a PR for?  If you made a standalone C++ class with a connect() disconnect() API I can write the logic to call it.

**Comment by ddickstein** [comment]
Any further plans here?  This would be really helpful, especially when trying to differentiate cases of disconnection vs frozen programs at a glance.

**Comment by MisterTea** [comment]
@ddickstein Care to submit a PR? :-)

I'm a tmux -CC user so this isn't high pri for me TBQH but happy to review a PR for it.

**Comment by ddickstein** [comment]
What changes do you think are necessary to get it to work?  I haven't spent much time working in C++ and I don't know the codebase here.  Do you have a rough sense of how much work it is and what the steps would be?

**Comment by krayon** [comment]
@MisterTea I absolutely would but unfortunately I don't have the time and I don't actually use EternalTCP myself. I was just evaluating it for someone and had that idea. I'm sorry I can't offer a PR for this :(
