### ISSUE TITLE
Build instructions fail on Kubuntu 20.4

### ISSUE THREAD

**Issue by dandv** [MisterTea/EternalTerminal#394]
Same error on Kubuntu 20.4 as #378 when running `cmake`:

> CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
>  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
>  OPENSSL_INCLUDE_DIR)
> Call Stack (most recent call first):
>  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
>  /usr/share/cmake-3.16/Modules/FindOpenSSL.cmake:447 (find_package_handle_standard_args)
>  CMakeLists.txt:12 (find_package)

After installing `libssl-dev` (not sure if that's the right library though?), there's an error about CURL:

> CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
>   Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake-3.16/Modules/FindCURL.cmake:143 (find_package_handle_standard_args)
>   external/sentry-native/CMakeLists.txt:248 (find_package)

Which one should be installed?

```
$ sudo apt-get install libcurl-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libcurl-dev is a virtual package provided by:
  libcurl4-openssl-dev 7.68.0-1ubuntu2.4
  libcurl4-nss-dev 7.68.0-1ubuntu2.4
  libcurl4-gnutls-dev 7.68.0-1ubuntu2.4
You should explicitly select one to install.

E: Package 'libcurl-dev' has no installation candidate
```

**Comment by MisterTea** [comment]
libcurl4-openssl-dev

**Comment by MisterTea** [comment]
actually libssl-dev
