### ISSUE TITLE
Release new versions

### ISSUE THREAD

**Issue by KapJI** [MisterTea/EternalTerminal#407]
Current version in Debian and Homebrew repos is v6.0.13 from Nov 2020, but the latest is v6.1.3.

Can you please release updated versions? They probably have some fixes.

Also maybe this can be automated with Github Actions or Circle CI?

**Comment by MisterTea** [comment]
Yep I'm working on this diligently. There are many challenges with 6.1 on various OSes. Follow the repo to get notified!

**Comment by MisterTea** [comment]
@KapJI I got homebrew up to date but debian will be a problem.

I was using github to store debian packages, but now the packages are > 100 MB so I can't use github anymore.  I'll need to get into debian proper or find another way to host the packages.

**Comment by MisterTea** [comment]
Put in the request to add et to debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985189

**Comment by KapJI** [comment]
Awesome, thank you! Would love to see it on main debian repo.

Btw, have you tried to figure out where this size is coming from? 100 MB+ sounds like a lot for CLI app.

**Comment by MisterTea** [comment]
It's the debug symbols. I'm throwing every external header into a common header that is precompiled. I'll have to refactor it at some point.

**Comment by MisterTea** [comment]
6.1 is rolled out almost everywhere
