### ISSUE TITLE
Problems parsing ~/.ssh/config

### ISSUE THREAD

**Issue by banach-space** [MisterTea/EternalTerminal#429]
Hi,

First of all, thank you for **EternalTerminal**, it's a great productivity boost!

I'm using **et** on Mac OS (Big Sur 11.2.3). It's getting really confused with my `~/.ssh/config` file, that otherwise seems perfectly fine. I have created this reproducer (it's not what I normally use):
```
Host github.com
  HostName github.com

Host foo-*
  HostName %h.com
```
I would use it to connect to e.g. `foo-01`, but it tries to connect to `github.com` instead:
```
et --logtostdout --verbose 9   foo-01
[INFO 2021-04-22 10:04:58,037 client-main ParseConfigFile.hpp:1371] unsupported config line: 	SendEnv LANG LC_*, ignored
[INFO 2021-04-22 10:04:58,037 client-main TerminalClientMain.cpp:186] Parsed ssh config file, connecting to github.com
[V1 2021-04-22 10:04:58,037 client-main TerminalClientMain.cpp:14] Connecting
^CShutting down sentry
[INFO 2021-04-22 10:04:59,314 client-main TcpSocketHandler.cpp:59] Error connecting with github.com: 4 Interrupted system call
[INFO 2021-04-22 10:04:59,314 client-main TcpSocketHandler.cpp:152] No host found
[V1 2021-04-22 10:04:59,314 client-main TerminalClientMain.cpp:17] Could not connect to host
Could not reach the ET server: github.com:2022
```
When it does try to connecting to `foo-01` (every 3-4th attempt), it fails as expected:
```
et --logtostdout --verbose 9   foo-01
[INFO 2021-04-22 10:04:59,821 client-main ParseConfigFile.hpp:1371] unsupported config line: 	SendEnv LANG LC_*, ignored
[INFO 2021-04-22 10:04:59,821 client-main TerminalClientMain.cpp:186] Parsed ssh config file, connecting to foo-01.com
[V1 2021-04-22 10:04:59,821 client-main TerminalClientMain.cpp:14] Connecting
[V1 2021-04-22 10:04:59,823 client-main TerminalClientMain.cpp:17] Could not connect to host
Could not reach the ET server: foo-01.com:2022
```

I've also noticed other issues when parsing my `~/.ssh/config`. It might be related, but I didn't want to bloat this ticket.

**EDIT:**
```
$ et --version
et version 6.1.7
```

Thank you,
-Andrzej

**Comment by MisterTea** [comment]
Can you compile with address sanitizer and see if you catch anything?

**Comment by MisterTea** [comment]
Hey I found an issue that's fixed in master.  Can you see if you still get the issue on master?

**Comment by banach-space** [comment]
I've just built ToT ([3f5d95115a711509f2fada28418123c1a81585c6](https://github.com/MisterTea/EternalTerminal/commit/3f5d95115a711509f2fada28418123c1a81585c6)). Works like a charm. Thank you for fixing this and for responding so quickly!

Let me test for a few days before closing the issue.

**Comment by banach-space** [comment]
This has worked fine for me for a few days now. Thank again for fixing this!
