### ISSUE TITLE
Eternal Terminal fails to parse IPv6 addresses

### ISSUE THREAD

**Issue by drodriguez** [MisterTea/EternalTerminal#433]
Eternal Terminal client host name parsing will not allow parsing IPv6 addresses passed directly on the command line, or the format is not very easy to figure out.

The code in https://github.com/MisterTea/EternalTerminal/blob/1d198cc97e467d82a6246e871d75994b9a5c7404/src/terminal/TerminalClientMain.cpp#L147-L151 looks for the first ":" (colon) in order to find the separation of a hostname and a port number. This works for textual host names and for IPv4 addresses, but fails for IPv6 addresses.

IPv6 addresses are normally provided like `2001:db8::8a2e:370:7334`, where the colon is used to separate the words, and a double colon indicating that all the words between those two colons are zero. When provided to the Eternal Terminal parser, 2001 will be interpreted as the hostname, and since `stoi` is used, the port will be parsed as zero in that case, but can partially parse the second word of the IPv6 address.

A fix might probably involve using https://linux.die.net/man/3/inet_pton to try to parse the hostname as a IPv6 or a IPv4 address before trying to split it. I would say that using `rfind` instead of `find` to look for the last `:` might also be good.

As a workaround, it seems that it is possible to add an entry in `~/.ssh/config` with a textual `Host` "name" and a `HostName` with the IPv6 address.

**Comment by jshort** [comment]
Fixed by #536
