### ISSUE TITLE
Unable to install: Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by oG14108149527Exl0Ftr7sY** [MisterTea/EternalTerminal#440]
Ubuntu 20.04 

sudo add-apt-repository ppa:ondrej/php

sudo add-apt-repository ppa:ondrej/apache2

sudo apt-get install et

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 et : Depends: libssl-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

- - - -

The following packages have unmet dependencies:

 libssl-dev : Depends: libssl1.1 (= 1.1.1f-1ubuntu2.4) but 1.1.1j-1+ubuntu20.04.1+deb.sury.org+3 is to be installed

E: Unable to correct problems, you have held broken packages.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Unable to use Eternal Terminal on servers using packages by ondrej

**Comment by MisterTea** [comment]
You'll have to build from source because you have conflicting ppas

**Comment by iAmG-r00t** [comment]
I also faced the same issue, is there a way for you guys to add et to ubuntu main packages for easier installation process ??

**Comment by MisterTea** [comment]
I would love to be in the Ubuntu main packages but so far Debian hasn't been willing to add us.

**Comment by iAmG-r00t** [comment]
How comes and why??

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Installing Eternal Terminal works great when using the Ubuntu packages.

The problem is when using the latest PHP 8.0.5 and Apache2 packages from:

https://launchpad.net/~ondrej/+archive/ubuntu/php/

https://deb.sury.org/#debian-dpa

**Comment by oG14108149527Exl0Ftr7sY** [comment]
Would be great if I was possible to use Eternal Terminal in the same environment as the packages from "ondrej".

Currently Eternal Terminal only works with the default "Ubuntu" packages.

**Comment by oG14108149527Exl0Ftr7sY** [comment]
The easiest way to use PHP 8 on Ubuntu 20.04 web-servers is with packages from "Ondrej."


The problem is that packages from Ondrej and Eternal Terminal do not work together.


Want to use Eternal Terminal with Iridium 9555 satellite phone / satellite modem.


Would you please look into this matter?
