### ISSUE TITLE
Eternal Terminal VPN / Other languages implementations / Protocol description

### ISSUE THREAD

**Issue by iMrDJAi** [MisterTea/EternalTerminal#452]
Hello @MisterTea, I hope you're doing well <3

I been looking for a way to create persistent tunnels that survive disconnections and interruptions and I found Eternal Terminal. I have some questions about this project, but first let me tell you what I'm trying to achieve:

So, my device is connected to a network that doesn't actually provide internet access, also there is an HTTP proxy sever (proxy:8080) connected to that network which is accessible to my device, but that proxy only allows connections to a small set of whitelisted domains. I have no control over the network and the proxy, thankfully I have full access to a whitelisted domain that points to a server I own (myserver.com), so here is what I did: I created an SSH tunnel hosted on that server to gain internet access.

```
device => network => proxy:8080 => myserver.com:22 => internet
```

I wrote the client that I use to connect to my SSH in JavaScript and I run it on node. It's mainly a local socks5 proxy server (localhost:1080) connected to the SSH server through a socket proxy. I use tun2socks to forward my device's traffic to the socks5 server. The client works on both Windows and Android (using nodejs mobile).

```
device => tap interface => tun2socks => socks5 server (localhost:1080) => socket proxy (proxy:8080) => SSH (myserver.com:22) => internet
```
While this worked perfectly, the HTTP proxy has a problem, it seems that it has an evil firewall that limits each request size to 300kb, which means once a request exceeds that limit it interrupts the connection immediately. Therefore, I can't keep my SSH connection alive so long.

As a solution I decided to give each new request its own tunnel, in this way I can somehow access the internet but since I can't download anything that has more than 300kb some websites become completely broken, I barely can visit github.com (Yes I'm using it right now while submitting this issue). The workaround itself is unreliable and has its own issues: super high ping, unstable connection... without mentioning that it spams the server very bad. In short, the experience is poor! :")

I had to find a new strategy, Eternal Terminal looks good for the purpose but I'm struggling to find how to get started. I need to create a new VPN client for Windows and Android that relies on this project. I don't think that I can use it directly since it doesn't support socket proxies as far as I know, unless there is a workaround for that. But it still unclear to me how to build it for Android, I saw some issues talking about termux but I need to import it into my app as a library.

That's why I'd rather write it in JavaScript from scratch, but there is no available detailed description about how the Eternal TCP protocol works (you only mentioned BackedReader / BackedWriter) so I can't know how to craft packets and deal with fragmentation. I hope you'll provide me more info about that.

Thank you so much for this cool project! You should know how useful the Eternal TCP layer is, resumable sockets are neat! You should definitely extend it for use cases other than terminals. Have a nice day!

**Comment by iMrDJAi** [comment]
@MisterTea Hello again! I been working on the JavaScript implementation in the last few days, I did a great job with BackedReader and BackedWriter classes. However, I still have more work to do especially with the ring buffer.  

How big should the ring buffer be? not sure what size I'm supposed to give. Also, what about the cached packets? Do they have a size limit?

> Check out the reconnect(...) function. I think it's in ServerClientConnection.

I haven't find it there. Anyway, can you please provide me something like [this](https://datatracker.ietf.org/doc/html/rfc1928#section-4) if possible? This would be super helpful!

> Gotcha, socket proxies are not supported.

I was able to implement them, I created 2 local proxy servers, one for the ssh port (22), and the other for the eternal terminal port (2022). Now instead of doing `et root@myserver.com` I simply do `et root@127.0.0.1`.

**Comment by MisterTea** [comment]
> How big should the ring buffer be? not sure what size I'm supposed to give. Also, what about the cached packets? Do they have a size limit?

I didn't spend a lot of time optimizing this, but I think I made the ring buffer 16 packets and each packet can have arbitrary size.

**Comment by iMrDJAi** [comment]
Closing for now. Currently I have no interest to continue working on this.
Keeping this as a reference for future: https://stackoverflow.com/questions/69107115/how-to-properly-clear-the-internal-buffer-of-a-readable-stream-in-node/69118355#69118355.
