### ISSUE TITLE
Installing Eternal Terminal on Debian 10

### ISSUE THREAD

**Issue by fdm82** [MisterTea/EternalTerminal#456]
I've followed the instructions to install on Debian 10 (Buster) but 

apt-get update

throws an error:

Ign:8 https://github.com/MisterTea/debian-et/raw/master/debian-source buster InRelease
Err:9 https://github.com/MisterTea/debian-et/raw/master/debian-source buster Release
  404  Not Found [IP: 140.82.121.3 443]

Doesn't the repo exist anymore ?

**Comment by MisterTea** [comment]
I just pushed a new version. If you "apt update" does it work?

**Comment by fdm82** [comment]
It's not working, still the same error

**Comment by MisterTea** [comment]
Ah, looks like I'm no longer building buster since bookworm came out because of the way my scripts work.  I should be able to add buster back in the next day or so.

**Comment by fdm82** [comment]
Is there a timeline by when the buster repro is available again ?

**Comment by MisterTea** [comment]
Ok buster should be there again, thanks.

**Comment by fdm82** [comment]
Great. It works. Thanks
