### ISSUE TITLE
Make Telemetry work on Mojave

### ISSUE THREAD

**Issue by dgentry** [MisterTea/EternalTerminal#461]
Ideally, telemetry would work on Mojave too.

I have it working in a `telemetry_for_mojave` branch (at https://github.com/dgentry/EternalTerminal/tree/telemetry_for_mojave), but I should test that my changes don't break other platforms.  (I think they are fine, but if you wait a day or two, I'll narrow the changes to only the code that needs it (i.e., not all code that imports `Headers.hpp`.)

**Comment by MisterTea** [comment]
Closing because I believe this is resolved but please reopen if it isn't.
