### ISSUE TITLE
[Ubuntu] Kitty terminal backspace does not work

### ISSUE THREAD

**Issue by sbeckeriv** [MisterTea/EternalTerminal#469]
Dearest maintainer, 

I am using kitty https://github.com/kovidgoyal/kitty and I have found that my backspace key does not seem to work. Instead of a backspace it is entering a space. I was unsure where to put this issue or even how to debug it. I can confirm that the built in terminal works fine.  Please let me know where I should be looking or how I can debug this issue?

Thank you for any and all help. This looks like a really useful project for me.

Becker

**Comment by MisterTea** [comment]
What does it say when you run

```
echo $TERM
```

under both ssh and et?

**Comment by sbeckeriv** [comment]
for kitty:
ssh 
echo $TERM
xterm

et:
echo $TERM
xterm-kitty


i remember now that kitty does have some terminfo issues. https://wiki.archlinux.org/title/Kitty#Terminal_issues_with_SSH i just have ssh aliased and forgot about it.  could that be it?

**Comment by MisterTea** [comment]
If you change the term variable back to "xterm" does it work?

**Comment by sbeckeriv** [comment]
Yes it does MisterTea. I guess i can set that up in my .bash file. I tried `SetEnv TERM=xterm-256color` in my ssh config for the server but that did not seem to work. 

Thanks for the help and all your work on this project.
