### ISSUE TITLE
ET gathers data on user activity without consent or their knowledge

### ISSUE THREAD

**Issue by mcybz** [MisterTea/EternalTerminal#474]
The README.md makes no mention that telemetry is on by default.

Nor anyway to turn it off other than compiling from source (which is not what most users do). It doesn't matter if IP's are logged or not, this should be disclosed and an option to easily disable it. Better yet would be to make it opt in.

There are countless examples of large opensource projects where this issue has blow up in the past. See `brew` for example.

**Comment by MisterTea** [comment]
You can turn off telemetry by passing "--telemetry false" to the et command or setting telemetry to false in et.cfg

**Comment by mcybz** [comment]
> You can turn off telemetry by passing "--telemetry false" to the et command or setting telemetry to false in et.cfg

Thanks I see that now after hunting in the issues and commits. And additional I see there is a `ET_NO_TELEMETRY=1` from viewing the source code.

Is this information readily available to end users? 

I'm sure you're not trying to hide this fact, but I think this main point was lost, given how fast this was closed.

**Comment by MisterTea** [comment]
> > You can turn off telemetry by passing "--telemetry false" to the et command or setting telemetry to false in et.cfg
> 
> Thanks I see that now after hunting in the issues and commits. And additional I see there is a `ET_NO_TELEMETRY=1` from viewing the source code.
> 
> Is this information readily available to end users?
> 
> I'm sure you're not trying to hide this fact, but I think this main point was lost, given how fast this was closed.

Please submit a PR to update the README.md file, thanks!
