### ISSUE TITLE
CentOS 7 - cloning issue while building from source

### ISSUE THREAD

**Issue by rvnsource** [MisterTea/EternalTerminal#478]
Hi,
I am trying to build 'eternal' from source, following this link (https://github.com/MisterTea/EternalTerminal)
But, seeing this error while cloning the below command in CentOS 7:-

Command:-
git clone --recurse-submodules https://github.com/MisterTea/EternalTerminal.git

Error output:-
[root@mylab1 build]# git clone --recurse-submodules https://github.com/MisterTea/EternalTerminal.git
Cloning into 'EternalTerminal'...
remote: Enumerating objects: 31300, done.
...
remote: Total 136075 (delta 81), reused 73 (delta 73), pack-reused 135981
Receiving objects: 100% (136075/136075), 47.01 MiB | 21.33 MiB/s, done.
Resolving deltas: 100% (84361/84361), done.
Submodule path 'external/vcpkg': checked out 'b295670e4bab14debe88d92cd5364b21ce26232c'
Failed to recurse into submodule path 'external/sentry-native'
[root@mylab1 ~]# ls -lart

**Comment by jshort** [comment]
Is this still an issue?  This is a git(hub) issue and sentry-native's commit was updated 7 mo ago.  Re-open if you still have this problem.
