### ISSUE TITLE
macOS (homebrew) build breaks with boost installed since strict permissions added to easylogging

### ISSUE THREAD

**Issue by thalamus** [MisterTea/EternalTerminal#480]
If boost is installed, following commit https://github.com/MisterTea/easyloggingpp/commit/532df6a32c6d743ac54f1d65dd220fb3249d4b8e the build fails with the following:

```
/tmp/et-20211228-42320-8imcba/EternalTerminal-et-v6.1.9/external_imported/easyloggingpp/src/easylogging++.cc:752:19: error: no member named 'perm_options' in namespace 'boost::filesystem'; did you mean 'std::filesystem::perm_options'?
                  fs::perm_options::replace);
                  ^~~~~~~~~~~~~~~~
                  std::filesystem::perm_options
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/filesystem:351:29: note: 'std::filesystem::perm_options' declared here
enum class _LIBCPP_ENUM_VIS perm_options : unsigned char {
                            ^
/tmp/et-20211228-42320-8imcba/EternalTerminal-et-v6.1.9/external_imported/easyloggingpp/src/easylogging++.cc:750:7: error: no matching function for call to 'permissions'
      fs::permissions(filename,
      ^~~~~~~~~~~~~~~
/opt/homebrew/include/boost/filesystem/operations.hpp:449:6: note: candidate function not viable: no known conversion from 'std::filesystem::perm_options' to 'system::error_code &' for 3rd argument
void permissions(const path& p, perms prms, system::error_code& ec) BOOST_NOEXCEPT
     ^
/opt/homebrew/include/boost/filesystem/operations.hpp:446:6: note: candidate function not viable: requires 2 arguments, but 3 were provided
void permissions(const path& p, perms prms)
     ^
```

It looks like `boost::filesystem` takes different arguments than `std::filesystem` which is causing the failure, and the presence of `boost/filesystem.hpp` causes `boost::filesystem` to be used which results in the build failure.

Removing boost fixes the build, but obviously isn't the ideal solution.

**Comment by MisterTea** [comment]
Ugh.  I think we need to kill support for boost::filesystem if it isn't compatible.

**Comment by MisterTea** [comment]
Fixed by https://github.com/MisterTea/EternalTerminal/commit/cc5b7d223d29d5fda1a839a269ad54cd8d49311c

Run "brew install --HEAD et" until the next patch release (a few days from now) as a mitigation

**Comment by MisterTea** [comment]
I needed some follow-up changes but they are in now and it should work (for real) 😅

**Comment by C4ptainCrunch** [comment]
I can confirm, it seems fixed over here ! Second time's a charm. Thank you 🚀

**Comment by thalamus** [comment]
@MisterTea Thanks for the fix. I was scratching my head with this one for a bit haha.

**Comment by jubalh** [comment]
Hi!

> I needed some follow-up changes but they are in now and it should work (for real) sweat_smile

which commits were this?

I would like to bring the latest release to an older version of a distribution. And when I try to compile I get:
`[   78s] /home/abuild/rpmbuild/BUILD/EternalTerminal-et-v6.2.1/src/base/LogHandler.cpp:51:7: error: 'permissions' is not a member of 'fs'`
Maybe some too old compiler/boost? I thought maybe the mentioned commits could help.
