### ISSUE TITLE
builds fail on OSX

### ISSUE THREAD

**Issue by kurktchiev** [MisterTea/EternalTerminal#483]
I posted this in the homebrew repo (https://github.com/MisterTea/homebrew-et/issues/17) but building latest ET on OSX is failing on Big Sur and Monteray (at least I have a Catalina box i need to check and see if I can upgrade on)

**Comment by kurktchiev** [comment]
nope it fails on catalina too

**Comment by MisterTea** [comment]
Fixed by https://github.com/MisterTea/EternalTerminal/commit/cc5b7d223d29d5fda1a839a269ad54cd8d49311c

Run "brew install --HEAD et" until the next patch release (a few days from now) as a mitigation
