### ISSUE TITLE
Unnecessary -dev dependencies in the built debian package

### ISSUE THREAD

**Issue by zsorizs** [MisterTea/EternalTerminal#490]
When looking at the debian package I see the next dependencies:

Depends: libc6 (>= 2.17), libcurl4 (>= 7.16.2), libprotobuf-lite23 (>= 3.12.4), libsodium23 (>= 0.6.0), libssl1.1 (>= 1.1.0), libstdc++6 (>= 9), libunwind8, libutempter0 (>= 1.1.5), zlib1g (>= 1:1.1.4), libgcc1 (>= 1:3.3), libprotobuf-dev, libsodium-dev, libtinfo5, libutempter-dev, libcurl4-openssl-dev, libssl-dev, libunwind-dev

I think all those ending with -dev are not needed and they result in pulling in a lot of unnecessary dependencies when installing et.

When building a Debian package the dev dependencies need to appear in the Build-Depends section of the control file, but there is no need to list them in the Depends section. You have the Depends section already set up so that the build process automatically adds all the necessary dependencies. Removing all the -dev entries from there should solve this issue.

**Comment by MisterTea** [comment]
I don't think removing the dev dependencies would work without adding the non-dev dependencies. Simply removing them will cause missing .so files

**Comment by zsorizs** [comment]
During the package build, all the necessary dependencies are automatically added.

In this case:
- for libprotobuf-dev libprotobuf-lite23 (>= 3.12.4)
- for libsodium-dev libsodium23 (>= 0.6.0)
- for libutempter-dev libutempter0 (>= 1.1.5)
- for libcurl4-openssl-dev libcurl4 (>= 7.16.2)
- for libssl-dev libssl1.1 (>= 1.1.0)
- for libunwind-dev libunwind8

So you can safely remove these dev dependencies and it won't break the executable.

**Comment by zsorizs** [comment]
I can provide a pull request, if you want.

**Comment by MisterTea** [comment]
Sure, the deployment branch has the debian files.  Please submit a PR there and I can build with that and make sure it's functional.

**Comment by zsorizs** [comment]
I have created the pull request: #494

**Comment by MisterTea** [comment]
Thanks, approved!  I'm going to close this issue unless there's any followup

**Comment by zsorizs** [comment]
Thanks for applying.
When can I expect that the new debian package will be released?
