### ISSUE TITLE
Dependency/Readme clean up

### ISSUE THREAD

**Issue by Doom4535** [MisterTea/EternalTerminal#586]
Assuming my quick check of the build dependencies is correct, could the main page be updated to reflect the current dependencies? It would help with cleaning up distro packages and could save build time for source build systems.
## Deprecated dependencies
I believe the following libraries are no longer required for the latest builds:
`ncurses` (since v3 on, I believe the last usage was [v2.1.0 NCursesOverlay.hpp](https://github.com/MisterTea/EternalTerminal/blob/6d2984cacd2d8999acf85dd3f38212341c3c4cdc/terminal/NCursesOverlay.hpp#L6), [v2.1.0 CMakeLists.txt](https://github.com/MisterTea/EternalTerminal/blob/et-v2.1.0/CMakeLists.txt))
`gflags` (since v6 on, last usage was on v5, with removal here: #206)

## Potentially optional dependencies:
`boost` When looking at the curent master https://github.com/MisterTea/EternalTerminal/commit/2e06248f75d40042d3b116b233bce58db5022e6d, I'm not seeing much usage of boost (most (or all) are checks to see if it is availible); when grep'ing through the v6 releases, I'm seeing a lot of references to it in the [`external`](https://github.com/MisterTea/EternalTerminal/tree/2e06248f75d40042d3b116b233bce58db5022e6d/external) and the more recent (since v6.0.4, but not in master; presumably for vcpkg) `external_imported` (different commit 
[5eb70c/external_imported](https://github.com/MisterTea/EternalTerminal/tree/5eb70c2169870394aad2fe67a42a2eabf519232f/external_imported)) folders. Additionally, I am able to build a few random v6 releases without boost; what is lost by not including this library in a build and could the main page be updated to make this an optional include (with some details on why one may/may not want to include it (is this library currently included solely for vcpkg?))?

**Comment by MisterTea** [comment]
Thanks for looking into this! Boost Filesystem was used back when we had significant folks running older compilers without standard filesystem. We can probably remove it now.
