### ISSUE TITLE
"Error handling new client: Failed a call to readAll"

### ISSUE THREAD

**Issue by catharsis71** [MisterTea/EternalTerminal#597]
I want to try out EternalTerminal after trying Mosh and being disappointed by the lack of scrollback (but it DID work properly).  EternalTerminal on the other hand doesn't work at all

When client tries to connect, the following appears in the server log:

```
[V1 2023-08-20 11:45:59,992 etserver-main ServerConnection.cpp:16] Accepting connection
[V3 2023-08-20 11:45:59,992 etserver-main UnixSocketHandler.cpp:137] Socket 8 accepted, returned client_sock: 10
[V3 2023-08-20 11:45:59,992 etserver-main UnixSocketHandler.cpp:143] Client_socket inserted to activeSockets
[V1 2023-08-20 11:45:59,992 etserver-main ServerConnection.cpp:21] SERVER: got client socket fd: 10
[V4 2023-08-20 11:45:59,992 server-clientHandler Headers.hpp:349] Before selecting sockFd
[V4 2023-08-20 11:45:59,996 server-clientHandler UnixSocketHandler.cpp:23] socket 10 has data
[V4 2023-08-20 11:45:59,996 server-clientHandler UnixSocketHandler.cpp:45] Unixsocket handler read from fd: 10
[V1 2023-08-20 11:45:59,996 server-clientHandler SocketHandler.cpp:34] Failed a call to readAll: Broken pipe
[WARNING 2023-08-20 11:45:59,996 server-clientHandler ServerConnection.cpp:127] Error handling new client: Failed a call to readAll
[V1 2023-08-20 11:45:59,996 server-clientHandler UnixSocketHandler.cpp:166] Closing connection: 10
```

I suspect this may be because I'm using a port other than 22 for SSH, and the documentation is very poor about how to handle this

In Mosh it was a simple matter of adding ```--ssh="ssh -6 -p 22320"``` on the client connection command

but no luck on ET

```--ssh-option "-6 -p 22320"``` seems to do nothing

```/etc/ssh/sshd_config``` on the server contains ```Port 22320``` is it not pulling the information from this file?

I notice the documentation says ```ssh_config``` instead of ```sshd_config``` but it doesn't say if it's referencing the ```ssh_config``` on the client or the server

Editing the ```ssh_config``` on the client is not an option

I use different ports on different servers

Either I need to be able to specify the SSH port on the command line, or I need to be able to specify it  in```/etc/et.cfg```  on the server or it needs to read it from ```/etc/ssh/sshd_conf``` on the server

**Comment by MisterTea** [comment]
Et (similar to vscode remote folders) relies on your ~.ssh/ssh_config file
(or /etc/ssh_config but that's only root writable). You need to set the ssh
port there.

Jason G.

**Comment by catharsis71** [comment]
I have a ```~/.ssh/config```, is that what you mean?

I already have ```~/.ssh/config``` on my local machine set up with entries for all my servers

Here's how the entry looks for the server in question:

```
Host uk2
 Hostname uk2.mydomain.tld
 User me
 Port 22320
```

So normally I just do ```ssh uk2``` which is equivalent to ```ssh -p 22320 me@uk2.mydomain.tld```

but using ```et uk2:65533 --verbose=9``` (65533 is the port mosh-server is listening on) does the same thing, I still see the same error in the server log

**Comment by catharsis71** [comment]
Hmmm... eventually I removed the ```--verbose=9``` from the connection command it it connected

then I exited, re-added the ```--verbose=9```, and it still connected

very odd
