### ISSUE TITLE
Segfault starting etserver on raspberry pi zero

### ISSUE THREAD

**Issue by jaredmoody** [MisterTea/EternalTerminal#608]
After following the debian instructions to add the PPA and installing, attempting to start the server just immediately segfaults.

```
 $
/usr/bin/etserver --cfgfile=/etc/et.cfg
Segmentation fault
```

Backtrace:

```
#0  0xb6a445c8 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.1
#1  0xb6a3e1a0 in ?? () from /lib/arm-linux-gnueabihf/libcrypto.so.1.1
```

**Comment by MisterTea** [comment]
I've seen this before in arch. It has to do with a mismatch between the
libcrypto on the machine and the one et was compiled with. You can compile
et from scratch to fix for now.

What OS and version are you using?

**Comment by jaredmoody** [comment]
This was on raspbian bullseye

**Comment by MisterTea** [comment]
Let me see if I can compile libcrypto within et a d eliminate these errors.

**Comment by jaredmoody** [comment]
6.2.9 is working for me on aarch! 🎉
