### ISSUE TITLE
GCP IAP proxy

### ISSUE THREAD

**Issue by branep** [MisterTea/EternalTerminal#610]
Hello,

I'd like to setup ET to work through the GCP IAP proxy. What ports should should I forward through the proxy to accomplish this?
We are trying to take advantage of the IAP tunnelling and close public ports. 

Thanks!

**Comment by MisterTea** [comment]
@branep what was the solution?  I don't use GCP but others may want to know

**Comment by branep** [comment]
> @branep what was the solution? I don't use GCP but others may want to know

Hey @MisterTea, nothing implemented yet. Still looking and considering VPN or other alternatives.
