### ISSUE TITLE
Ubuntu mantic et package (et_6.2.8-mantic1_amd64.deb) broken (bad dep on libtinfo5)

### ISSUE THREAD

**Issue by egnor** [MisterTea/EternalTerminal#612]
Attempting to install this package (which is where the PPA currently points) gives this error:

```
% sudo dpkg -i ~/Downloads/et_6.2.8-mantic1_amd64.deb
[sudo] password for egnor: 
(Reading database ... 194462 files and directories currently installed.)
Preparing to unpack .../et_6.2.8-mantic1_amd64.deb ...
Unpacking et (6.2.8-mantic1) over (6.2.8-mantic1) ...
dpkg: dependency problems prevent configuration of et:
 et depends on libtinfo5; however:
  Package libtinfo5 is not installed.

dpkg: error processing package et (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 et
```

This is proximally because [libtinfo5](https://answers.launchpad.net/ubuntu/mantic/amd64/libtinfo5) has been [removed from Debian for general ancientness](https://salsa.debian.org/debian/ncurses/-/commit/11d067455801fddf8c65eba6e447ef7aacd1d703) and therefore Ubuntu as well.

But I don't see any _actual_ dependency on this package, none of the binaries installed seem to depend on that library? Using `--force-deps` to install the package seems to result in a working EternalTerminal, but I haven't tested everything...

**Comment by mLewisLogic** [comment]
Same issue.

As a stopgap, @egnor's suggestion got it limping along for me.

```sh
wget https://ppa.launchpadcontent.net/jgmath2000/et/ubuntu/pool/main/e/et/et_6.2.8-mantic1_amd64.deb
sudo dpkg --force-depends -i ./et_6.2.8-mantic1_amd64.deb
```

Hoping it gets fixed soon to get back to having it managed via apt.

**Comment by xlorepdarkhelm** [comment]
Any update on this?

**Comment by MisterTea** [comment]
Hmm, as the thread suggests, I'm not using libtinfo5, but maybe it's coming
it through ncurses-dev?

**Comment by jribbens** [comment]
@MisterTea What do you mean by that? The package you are publishing depends directly on libtinfo5, and doesn't depend on curses either directly or indirectly.

**Comment by MisterTea** [comment]
Maybe I'm missing/forgetting something, but I don't see libtinfo5 mentioned anywhere in the repo?

**Comment by smammy** [comment]
It'll be in the `debian/control` file in the sources you generate your `.deb`s from. (Is the packaging source on here somewhere?)

**Comment by jribbens** [comment]
As @smammy says, we're not talking about what your code _actually_ depends on, we're talking about what your package metadata _says_ it depends on:
```console
$ apt-get download et
Get:1 https://ppa.launchpadcontent.net/jgmath2000/et/ubuntu mantic/main amd64 et amd64 6.2.8-mantic1 [1293 kB]
Fetched 1293 kB in 0s (11.9 MB/s)
$ dpkg -e et_6.2.8-mantic1_amd64.deb 
$ fgrep libtinfo5 DEBIAN/control | fmt
Depends: libc6 (>= 2.38), libcurl4 (>= 7.16.2), libgcc-s1 (>= 3.3.1),
libprotobuf32 (>= 3.21.12), libsodium23 (>= 0.6.0), libssl3 (>= 3.0.0),
libstdc++6 (>= 13.1), libunwind8, libutempter0 (>= 1.1.5), zlib1g (>=
1:1.1.4), libgcc1 (>= 1:3.3), libtinfo5

**Comment by jribbens** [comment]
Brilliant, thanks! Got it working for me now from Mac OS client to Ubuntu server.
