### ISSUE TITLE
A way to prevent sourcing the shell's configs twice

### ISSUE THREAD

**Issue by CmdQ** [MisterTea/EternalTerminal#619]
When using `et`, I do through some small scripts that I created and it always gets me in a `tmux` session.

When working on my shell configs, I noticed that they are sourced after `et` connects __and a second time__ after `tmux` opens. That is really unfortunate, since my configs are __slow__. I already spent some time profiling, removing and rewriting and I got it a bit faster, but it's still more than a second. And due to work stuff, I can't get it down more.

But what feels unnecessary is that `etserver` sources them, because `tmux` will do so anyway and it's the same work—even if it wasn't, `tmux` would win.

So it would be great if there even was a way to
- skip sourcing or even
- - not start the “big” shell at all and go with `bin/sh` instead. I won't do anything in the base shell anyway.

Now, I read that `etserver` needs to be found and the config and stuff, but passing a hard-coded `--terminal-path` etc. to `et` would be a price I'm willing to pay to halve my connection time.

Or is there and I missed it?

**Comment by MisterTea** [comment]
Could you use environment variables to skip most of your config depending on the circumstances?
