### ISSUE TITLE
et needs ssh's -t option to support running tmux with et

### ISSUE THREAD

**Issue by timotheecour** [MisterTea/EternalTerminal#620]
ssh -t is useful to force pseudo-terminal allocation, eg:

`ssh myhost /pathto/tmux new-session -A -s foo`
open terminal failed: not a terminal
`ssh -t myhost /pathto/tmux new-session -A -s foo`
works, starts or joins tmux
`ssh -o RequestTTY=yes myhost /pathto/tmux new-session -A -s foo`
also works

what's the equivalent with `et`?
this didn't work:
`et myhost -c "/pathto/tmux new-session -A -s foo"`
it prints:
```
/pathto/tmux new-session -A -s foo; exit
/pathto/tmux new-session -A -s foo; exit
etc
```
passing this didn't help: `--ssh-option -t` nor did `--ssh-option RequestTTY=yes`, nor did `--ssh-option RequestTTY=force`

this might help with debugging?
`et --logtostdout --verbose 9 --ssh-option "LogLevel=DEBUG3,RequestTTY=force"`

**Comment by timotheecour** [comment]
EDIT: my setup was a bit more complex and i needed a `--jumphost host_aux`, and what i had tried was:

from macos:
```
ssh host_aux
then this failed: et myhost -c "/pathto/tmux new-session -A -s foo"
while this worked: `et myhost` followed by `/pathto/tmux new-session -A -s foo`
```
but this works if I run directly:
`et myhost --jumphost host_aux -c "/pathto/tmux new-session -A -s foo"`

**Comment by MisterTea** [comment]
Hmm. Maybe the issue is that doing an et inside of an ssh has a problem?

et always allocates a psuedoterminal so it doesn't need a -t. Ptys are
cheap enough that no one has complained yet.
