### ISSUE TITLE
Can use SCP or SSHFS with EternalTerminal?

### ISSUE THREAD

**Issue by AGI-chandler** [MisterTea/EternalTerminal#627]
Just wondering if there are ways to use `et` to establish connections like we do with `sftp` or to copy data like we do with `scp`?  Thanks

**Comment by MisterTea** [comment]
With port forwarding, you can route ssh/SCP through et. Et by itself has no
way to copy files.

**Comment by AGI-chandler** [comment]
I don't understand why port forwarding is required when we didn't need that to get _EternalTerminal_ working, can you help me understand why?  This is the only way?  

In the Files manager (Gnome), I can open a location like `sftp://[remote]` | `[remote]` = short host from `~/.ssh/config`, and it will mount my home dir on the remote server somewhere local.  I guess this is actually using `sshfs` underneath instead of `sftp` so I'm actually trying to use `sshfs` and somehow mount a remote dir with _EternalTerminal_, so it doesn't cause system to hang whenever access is lost.  

I figured a command like: `sshfs  [remote]:  /[mountpoint]  -o ssh_command=et` could work (this when `et [remote]` already works fine).  Have tried a few different commands, including using `-o ssh_command=ssh-et` but everything always ends in `read: Connection reset by peer`.  I'm guessing that's what the port forwarding would fix?  I can't even figure out how to turn on verbose messages from `sshfs` though 💢😠

but you'd imagine such an `sshfs` command would be more like what?

**Comment by MisterTea** [comment]
sftp is a protocol that et doesn't implement.  What you can do is forward your ssh port and then run sftp over that.

**Comment by AGI-chandler** [comment]
Sorry for the confusion but can blame Gnome folks for letting me type `sftp://example.com` and it mounts my home dir on example.com somewhere in `~/.gvfs` or something.  Either way, in the background it's really using `sshfs` command and there's no extra ports or forwarding needed it uses port 22.  The point is to have an EternalMount instead of an EternalTerminal.

**Comment by MisterTea** [comment]
I started working on a eternal version of sshfs here: https://github.com/MisterTea/CodeFS

I haven't touched it in a while though and it needs to be tested.

**Comment by MisterTea** [comment]
Closing this issue but please try codeFS and leave feedback over there.
