### ISSUE TITLE
deb repositories no longer contain files for debian buster/bullseye

### ISSUE THREAD

**Issue by paulgit** [MisterTea/EternalTerminal#640]
Hi

Today I started getting errors from the debian repositories published in the README, it seems they no longer contain builds for buster/bullseye. I see builds for trixie and bookworm.

Is this an intentional change or an issue? Is my only option to build the latest version from source?

Thanks

Paul

**Comment by MisterTea** [comment]
Ok, since we have two issues within 24 hours I'll make the call. 

Going to bring openssl inside the repo and then we can add support to those. Openssl 3.x is required for et now.

**Comment by MisterTea** [comment]
@paulgit do you actually need buster? ET hasn't supported buster in many versions

**Comment by MisterTea** [comment]
@paulgit Added 6.2.4 for buster and 6.2.8 for bullseye back to the repo
