### ISSUE TITLE
DNS Requests Every Second When Remote Host Unreachable

### ISSUE THREAD

**Issue by AGI-chandler** [MisterTea/EternalTerminal#654]
I use _et_ to access various computers at work, which require login to a VPN first.  The VPN disconnects every 24 hours, so _et_ has been really helpful.  Even though the terminal appears frozen, and even if I don't reconnect the VPN for hours on end, _et_ will maintain the link and whenever the VPN connection is reestablished, all data/commands get delivered to the server.  That all works perfectly, thanks.

Now lately I have been working with my DNS settings and watching DNS queries and I noticed a huge spike in queries when the VPN disconnects.  I noticed when that happened, there were queries once per second for 2 of 4 hosts I was connected to with _et_ which need the VPN established.  As soon as I suspended (SIGSTOP) the 2 `et` processes, the DNS queries stopped, and when I resumed the `et` processes, they picked up again.  When connection to the VPN was reestablished, the queries also stopped.

It appears to be due to the fact these 2 hosts have internal-only IP addresses (i.e. 10.x.y.z), so their records are not exported/propagated to the global directory.  Once a connection to the VPN is established, the DNS queries are routed though it and the proper 10.x.y.z A record is returned.

I ran _et_ with `--verbose=9` and the relevant log data is below.  There was only `etclient` data that had been produced; `etclient-stderr` didn't have any data, `etserver` doesn't even exist for today, neither did `etserver-stderr`.  Below that is the server's `et` log data.

Really hope you have ideas for a patch or at least a temp workaround because I'm limited in the number of monthly DNS queries.  Let me know if I can help with anything else.  Thx

[Client etclient log data.txt](https://github.com/user-attachments/files/16737939/Client.etclient.log.data.txt)

[Server etterminal log data.txt](https://github.com/user-attachments/files/16737941/Server.etterminal.log.data.txt)

**Comment by MisterTea** [comment]
I thought DNS queries were free for everyone?  Isn't is a small handshake that uses almost no bandwidth?

Right not every time et tries to reconnect (once per second), a DNS lookup happens here https://github.com/MisterTea/EternalTerminal/blob/master/src/base/TcpSocketHandler.cpp#L27

You would need to write code to save the results of that lookup in the class and refresh the saved results at some rate (because of roaming and VPN, the DNS lookup can change over time so we can't cache forever).

**Comment by MisterTea** [comment]
It's hardcoded to once per second.

**Comment by AGI-chandler** [comment]
It's also affected by the `--timeout` option, but can only set that as high as 5 seconds.  That's definitely an improvement.  As soon as I did, the queries immediately dropped to that rate.  I also found the `options` setting `timeout:n` for `/etc/resolv.conf`, which _systemd-resolved_ now maintains, but won't allow to set anything directly there.  Instead, it generates that file from settings in `/etc/systemd/resolved.conf`, which uses a different format plus a different set of options, none that I've found incude this timeout option.  Found one person that said we can't set `options` this way anyone.  Wonder who's bright idea it was to remove and disable functionality from `/etc/resolv.conf`?  We've been using that file for over 20 years it seems smh...

**Comment by AGI-chandler** [comment]
Well, guess we can close this, since it's not got much to do with _et_.  As a quick fix, but not a permanent solution, I manually added entries to `/etc/hosts`.  This stopped the DNS requests in their tracks.
