### ISSUE TITLE
Building 6.2.9 one macOS 14.6.1 errors

### ISSUE THREAD

**Issue by Lotusshaney** [MisterTea/EternalTerminal#656]
Trying to compile 6.2.9 on macOS 14.6.1 getting the following error

```
-- Running vcpkg install - failed
CMake Error at external/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  /Users/username/etbuild/EternalTerminal_x86/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:81 (project)
```

Building 6.2.8 https://github.com/MisterTea/EternalTerminal/commit/19c25d54bcfa352e007f22a6da8272fdf3cce8af however works fine

**Comment by MisterTea** [comment]
I'm getting a MacBook early next week then I'll be able to debug. Feel free to ping me if you don't hear anything in a week.

**Comment by MisterTea** [comment]
The error is because libsodium requires autoconf & friends:

```
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:718 (message):
  libsodium requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
Call Stack (most recent call first):
  ports/libsodium/portfile.cmake:49 (vcpkg_configure_make)
  scripts/ports.cmake:175 (include)


error: building libsodium:arm64-osx failed with: BUILD_FAILED
```

Running this command fixes it: `brew install autoconf automake libtool`

Updated instructions in https://github.com/MisterTea/EternalTerminal/commit/2099bdcf330cae40b98a13370b4de84a1b98f134
