### ISSUE TITLE
Dependencies missing from Debian/Ubuntu build instructions

### ISSUE THREAD

**Issue by gkiessling** [MisterTea/EternalTerminal#668]
The instructions for [building on Debian/Ubuntu](https://github.com/MisterTea/EternalTerminal/tree/master?tab=readme-ov-file#debianubuntu) are missing a couple of (transitive) dependencies:
* autoconf
* libtool

Without autoconf, cmake failed while building libsodium:

```
$ cmake ../
...
Building libsodium:x64-linux@1.0.20#1...
-- Downloading https://github.com/jedisct1/libsodium/archive/1.0.20-RELEASE.tar.gz -> jedisct1-libsodium-1.0.20-RELEASE.tar.gz...
-- Extracting source /home/gkiessling/oss/EternalTerminal/external/vcpkg/downloads/jedisct1-libsodium-1.0.20-RELEASE.tar.gz
-- Using source at /home/gkiessling/oss/EternalTerminal/external/vcpkg/buildtrees/libsodium/src/20-RELEASE-e1d8ad6ac8.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
CMake Error at scripts/cmake/vcpkg_configure_make.cmake:718 (message):
  libsodium requires autoconf from the system package manager (example: "sudo
  apt-get install autoconf")
```

After installing autoconf, cmake failed again while running autoconf. The autoconf error log (which I looked at but didn't save before re-running the build) indicated that libtool was missing.

Once both autoconf and libtool were installed, cmake succeeded.

**Comment by MisterTea** [comment]
Please submit a PR to fix, thanks!

**Comment by gkiessling** [comment]
https://github.com/MisterTea/EternalTerminal/pull/670

**Comment by timsu92** [comment]
@MisterTea This issue seems could be closed?

**Comment by MisterTea** [comment]
Yep thanks
