### ISSUE TITLE
Question: Clarify whether ET buffers input on slow connections

### ISSUE THREAD

**Issue by corneliusroemer** [MisterTea/EternalTerminal#673]
I've seen ET recommended as an alternative (or better replacement) to mosh. You compare ET to mosh with the following words: "While mosh provides the same core functionality as ET, it does not support native scrolling nor tmux control mode"

Could you clarify whether ET supports buffered input? I.e., when I have a slow connection, does my input appear on the screen before it has been acked by the server? This is a major feature of mosh for my use cases and I couldn't find out whether ET also has this feature. If it has, great add it somewhere prominently. If it doesn't have that feature, then add it to the mosh comparison here: 
<img width="830" alt="Brave Browser 2024-11-17 15 19 18" src="https://github.com/user-attachments/assets/ec388936-28fa-4be6-b0c8-b0bcbcdbdcf9">

https://eternalterminal.dev/

**Comment by MisterTea** [comment]
Et cannot do type-ahead because it doesn't have control over the terminal like mosh does. Mosh is a remote desktop for the terminal, while et is a wire protocol. This is the same reason why you cannot port forward with mosh but you can with et. 

Feel free to put ^ in a PR and add it to the website.

**Comment by corneliusroemer** [comment]
Thanks for the explanation, would be great to have a bit more on pros/cons wrt mosh in particular. As I haven't used ET it's a bit tricky for me to write this as I likely wouldn't do it justice.
