### ISSUE TITLE
Allow to pass options to SSH

### ISSUE THREAD

**Issue by DmitryKoterov** [MisterTea/EternalTerminal#72]
In the previous et versions, there was a `-s` switch to pass additional options to ssh. E.g. it allowed to pass `-o PasswordAuthentication=no` or something else. (I understand it was mostly used for jumphosts and similar stuff, but its usage was still wider than that.)

In newer versions, this switch is removed, and there is no way to pass options to the initial ssh process except putting them to .ssh/config.

What do you think about adding this feature back? Or allowing `et` to accept `-o aaa=bbb -o ccc=ddd` the same way as ssh does?

**Comment by ailzhang** [comment]
Hi Dmitry,
We think using .ssh/config is a cleaner way, is there any reason that sshconfig is not working for your case?

**Comment by DmitryKoterov** [comment]
Yes, the case is when et is used as a part of some other tool (e.g. to setup a tunnel and then do something else with this tunnel repeatedly - e.g. run Unison over it); this tool is self-contained (and even has an installer) and doesn't want to make changes to user's .ssh/config file.

**Comment by pavel64-sutyrin** [comment]
Same issue here. `/.ssh/config` seems to be not picked up (I am interested in `ForwardAgent`). Pure `ssh` works, `et` does not work, with all the same actions.

**Comment by MisterTea** [comment]
@pavel64-sutyrin We support agent forwarding now

**Comment by MisterTea** [comment]
@DmitryKoterov I'm fine with adding a switch for custom switch for ssh options.  You want to add it to TerminalClientMain.cpp and then pass the options to SshSetuphandler

**Comment by gklanderman** [comment]
close as resolved?
