### ISSUE TITLE
Installation via Homebrew issues

### ISSUE THREAD

**Issue by ayushbgl** [MisterTea/EternalTerminal#82]
brew install MisterTea/et/et
Updating Homebrew...
==> Installing et from mistertea/et
==> Downloading https://github.com/MisterTea/EternalTCP/archive/et-v4.1.2.tar.gz
Already downloaded: /Users/bagla/Library/Caches/Homebrew/et-4.1.2.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/et/4.1.2_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
Last 15 lines from /Users/bagla/Library/Logs/Homebrew/et/01.cmake:
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Glog (missing: GLOG_INCLUDE_DIR GLOG_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGlog.cmake:40 (find_package_handle_standard_args)
  CMakeLists.txt:32 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/et-20180125-36259-1ikm05w/EternalTCP-et-v4.1.2/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mistertea/homebrew-et/issues

**Comment by MisterTea** [comment]
et should depend on glog. Maybe your glog is corrupt?  Can you try to reinstall glog and then install et again?
