### ISSUE TITLE
Log file etclient_err became writeable by root only, requiring sudo to run et

### ISSUE THREAD

**Issue by mdolenga-fb** [MisterTea/EternalTerminal#93]
This issue occurred with an et client installation on Ubuntu 16.04. At some point, I was only able to run et under sudo; otherwise the process segfaulted shortly after authenticating me with the remote server.

After some investigation with Jason, he identified the root cause - the file /tmp/etclient_err was writeable only by root. After changing its permissions to 666 with chmod, the issue was resolved.

I do not specifically recall when I first ran ET as sudo, but it may have been when I was having an unrelated SSH authentication issue where one investigative step was to use sudo; it is quite likely I ran et the same way and precipitated this issue as a result.

**Comment by MisterTea** [comment]
@ailzhang 's logging rewrite will also remove the stderr/stdout logging and thus fix this issue.
