### ISSUE TITLE
Search engines still returning top result for https://mistertea.github.io/EternalTCP/

### ISSUE THREAD

**Issue by nnutter** [MisterTea/EternalTerminal#94]
Both Google and DuckDuckGo return https://mistertea.github.io/EternalTCP/ as the top result for "eternal terminal" so someone searching for this project gets a GitHub 404 error page.

**Comment by nnutter** [comment]
You might want to setup an HTTP meta redirect under the old name and/or look into telling the search engines about the name change.  Unless it just happened and I'm just happening to catch it in transition.

**Comment by MisterTea** [comment]
The name change just happened and unfortunately there's no way to redirect the website :-(. Google and the other engines should update in a few days.

**Comment by telser** [comment]
@MisterTea That is really unfortunate :( My apologies since it seems this was started by the FreeBSD porting. FWIW, the actual repo redirects fine, at least from my end.
